# Generated by Django 5.2.1 on 2025-08-15 14:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fiscalizacao', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigBancaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banco', models.CharField(max_length=100, verbose_name='Banco')),
                ('agencia', models.CharField(max_length=20, verbose_name='Agência')),
                ('conta', models.CharField(max_length=20, verbose_name='Conta')),
                ('convenio', models.CharField(blank=True, max_length=20, verbose_name='Convênio')),
            ],
        ),
        migrations.CreateModel(
            name='ConfigSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chave', models.CharField(max_length=100, unique=True, verbose_name='Chave')),
                ('valor', models.CharField(max_length=255, verbose_name='Valor')),
            ],
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Nome')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
            ],
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razao_social', models.CharField(max_length=255, unique=True, verbose_name='Razão Social')),
                ('nome_fantasia', models.CharField(blank=True, max_length=255, verbose_name='Nome Fantasia')),
                ('cnpj', models.CharField(max_length=18, unique=True, verbose_name='CNPJ')),
                ('endereco', models.CharField(max_length=255, verbose_name='Endereço')),
                ('telefone', models.CharField(blank=True, max_length=20, verbose_name='Telefone')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
        ),
        migrations.CreateModel(
            name='Multa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor (R$)')),
                ('data_emissao', models.DateField(auto_now_add=True, verbose_name='Data de Emissão')),
                ('pago', models.BooleanField(default=False, verbose_name='Pago')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='multas', to='multas.empresa', verbose_name='Empresa')),
                ('processo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='multa', to='fiscalizacao.autoinfracao', verbose_name='Processo (Auto de Infração)')),
            ],
        ),
        migrations.CreateModel(
            name='Cobranca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boleto', models.FileField(upload_to='boletos/%Y/%m/%d/', verbose_name='Arquivo do Boleto')),
                ('remessa', models.FileField(upload_to='remessas/%Y/%m/%d/', verbose_name='Arquivo de Remessa CNAB')),
                ('retorno', models.FileField(blank=True, null=True, upload_to='retornos/%Y/%m/%d/', verbose_name='Arquivo de Retorno CNAB')),
                ('data_vencimento', models.DateField(verbose_name='Vencimento')),
                ('data_pagamento', models.DateField(blank=True, null=True, verbose_name='Pagamento')),
                ('multa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cobrancas', to='multas.multa', verbose_name='Multa')),
            ],
        ),
        migrations.CreateModel(
            name='Peticao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ren_impugn', 'Renúncia à Impugnação'), ('rec1', 'Recurso 1ª Instância'), ('rec2', 'Recurso 2ª Instância')], max_length=20, verbose_name='Tipo')),
                ('texto', models.TextField(verbose_name='Texto')),
                ('documento', models.FileField(upload_to='peticoes/%Y/%m/%d/', verbose_name='Documento')),
                ('data', models.DateField(auto_now_add=True, verbose_name='Data')),
                ('processo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='peticoes', to='fiscalizacao.autoinfracao', verbose_name='Processo (Auto de Infração)')),
            ],
        ),
        migrations.CreateModel(
            name='Recurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('impugnacao', 'Impugnação'), ('rec1', 'Recurso 1ª Instância'), ('rec2', 'Recurso 2ª Instância')], max_length=20, verbose_name='Tipo')),
                ('texto', models.TextField(verbose_name='Texto')),
                ('documento', models.FileField(upload_to='recursos/%Y/%m/%d/', verbose_name='Documento')),
                ('data', models.DateField(auto_now_add=True, verbose_name='Data')),
                ('processo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recursos', to='fiscalizacao.autoinfracao', verbose_name='Processo (Auto de Infração)')),
            ],
        ),
        migrations.CreateModel(
            name='Analise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('rec2', '2ª Instância'), ('rec3', '3ª Instância')], max_length=20, verbose_name='Tipo de Análise')),
                ('parecer', models.TextField(verbose_name='Parecer')),
                ('decisao', models.BooleanField(verbose_name='Deferido')),
                ('data', models.DateField(auto_now_add=True, verbose_name='Data')),
                ('recurso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analises', to='multas.recurso', verbose_name='Recurso')),
            ],
        ),
    ]
