# Generated by Django 4.2.11 on 2025-09-21 04:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fiscalizacao', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigBancaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banco', models.CharField(max_length=100, verbose_name='Banco')),
                ('agencia', models.CharField(max_length=20, verbose_name='Agência')),
                ('conta', models.CharField(max_length=20, verbose_name='Conta')),
                ('convenio', models.CharField(blank=True, max_length=20, verbose_name='Convênio')),
            ],
        ),
        migrations.CreateModel(
            name='ConfigSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chave', models.CharField(max_length=100, unique=True, verbose_name='Chave')),
                ('valor', models.CharField(max_length=255, verbose_name='Valor')),
            ],
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Nome')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
            ],
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razao_social', models.CharField(max_length=255, unique=True, verbose_name='Razão Social')),
                ('nome_fantasia', models.CharField(blank=True, max_length=255, verbose_name='Nome Fantasia')),
                ('cnpj', models.CharField(max_length=18, unique=True, verbose_name='CNPJ')),
                ('endereco', models.CharField(max_length=255, verbose_name='Endereço')),
                ('telefone', models.CharField(blank=True, max_length=20, verbose_name='Telefone')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
        ),
        migrations.CreateModel(
            name='Recurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('impugnacao', 'Impugnação'), ('rec1', 'Recurso 1ª Instância'), ('rec2', 'Recurso 2ª Instância')], max_length=20, verbose_name='Tipo')),
                ('texto', models.TextField(verbose_name='Texto')),
                ('documento', models.FileField(upload_to='recursos/%Y/%m/%d/', verbose_name='Documento')),
                ('data', models.DateField(auto_now_add=True, verbose_name='Data')),
                ('processo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recursos', to='fiscalizacao.processo', verbose_name='Processo Administrativo')),
            ],
        ),
        migrations.CreateModel(
            name='Peticao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ren_impugn', 'Renúncia à Impugnação'), ('rec1', 'Recurso 1ª Instância'), ('rec2', 'Recurso 2ª Instância')], max_length=20, verbose_name='Tipo')),
                ('texto', models.TextField(verbose_name='Texto')),
                ('documento', models.FileField(upload_to='peticoes/%Y/%m/%d/', verbose_name='Documento')),
                ('data', models.DateField(auto_now_add=True, verbose_name='Data')),
                ('processo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='peticoes', to='fiscalizacao.processo', verbose_name='Processo Administrativo')),
            ],
        ),
        migrations.CreateModel(
            name='Multa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, help_text='Valor exato da penalidade financeira', max_digits=12, verbose_name='Valor da Multa (R$)')),
                ('data_emissao', models.DateField(auto_now_add=True, help_text='Data em que a multa foi criada no sistema', verbose_name='Data de Emissão')),
                ('data_vencimento', models.DateField(blank=True, help_text='Prazo final para pagamento da multa', null=True, verbose_name='Data de Vencimento')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('paga', 'Paga'), ('vencida', 'Vencida'), ('cancelada', 'Cancelada')], default='pendente', help_text='Estado atual da multa no ciclo de cobrança', max_length=20, verbose_name='Status da Multa')),
                ('comprovante_pagamento', models.FileField(blank=True, help_text='Arquivo PDF ou imagem do comprovante de pagamento', null=True, upload_to='comprovantes/%Y/%m/%d/', verbose_name='Comprovante de Pagamento')),
                ('observacoes', models.TextField(blank=True, help_text='Anotações administrativas sobre a multa', verbose_name='Observações')),
                ('criado_em', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, null=True, verbose_name='Atualizado em')),
                ('pago', models.BooleanField(default=False, help_text="Campo de compatibilidade - use o campo 'status'", verbose_name='Pago (Legacy)')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='multas', to='multas.empresa', verbose_name='Empresa Autuada')),
                ('processo', models.OneToOneField(help_text='Auto de infração que originou esta multa (será migrado para Processo)', on_delete=django.db.models.deletion.PROTECT, related_name='multa', to='fiscalizacao.autoinfracao', verbose_name='Auto de Infração')),
            ],
            options={
                'verbose_name': 'Multa',
                'verbose_name_plural': 'Multas',
                'ordering': ['-data_emissao', '-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='Cobranca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boleto', models.FileField(upload_to='boletos/%Y/%m/%d/', verbose_name='Arquivo do Boleto')),
                ('remessa', models.FileField(upload_to='remessas/%Y/%m/%d/', verbose_name='Arquivo de Remessa CNAB')),
                ('retorno', models.FileField(blank=True, null=True, upload_to='retornos/%Y/%m/%d/', verbose_name='Arquivo de Retorno CNAB')),
                ('data_vencimento', models.DateField(verbose_name='Vencimento')),
                ('data_pagamento', models.DateField(blank=True, null=True, verbose_name='Pagamento')),
                ('multa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cobrancas', to='multas.multa', verbose_name='Multa')),
            ],
        ),
        migrations.CreateModel(
            name='Analise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('rec2', '2ª Instância'), ('rec3', '3ª Instância')], max_length=20, verbose_name='Tipo de Análise')),
                ('parecer', models.TextField(verbose_name='Parecer')),
                ('decisao', models.BooleanField(verbose_name='Deferido')),
                ('data', models.DateField(auto_now_add=True, verbose_name='Data')),
                ('recurso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analises', to='multas.recurso', verbose_name='Recurso')),
            ],
        ),
    ]
