# Generated by Django 5.2.5 on 2025-08-17 02:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiscalizacao', '0001_initial'),
        ('multas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='multa',
            options={'ordering': ['-data_emissao', '-criado_em'], 'verbose_name': 'Multa', 'verbose_name_plural': 'Multas'},
        ),
        migrations.AddField(
            model_name='multa',
            name='atualizado_em',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Atualizado em'),
        ),
        migrations.AddField(
            model_name='multa',
            name='comprovante_pagamento',
            field=models.FileField(blank=True, help_text='Arquivo PDF ou imagem do comprovante de pagamento', null=True, upload_to='comprovantes/%Y/%m/%d/', verbose_name='Comprovante de Pagamento'),
        ),
        migrations.AddField(
            model_name='multa',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Criado em'),
        ),
        migrations.AddField(
            model_name='multa',
            name='data_vencimento',
            field=models.DateField(blank=True, help_text='Prazo final para pagamento da multa', null=True, verbose_name='Data de Vencimento'),
        ),
        migrations.AddField(
            model_name='multa',
            name='observacoes',
            field=models.TextField(blank=True, help_text='Anotações administrativas sobre a multa', verbose_name='Observações'),
        ),
        migrations.AddField(
            model_name='multa',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('paga', 'Paga'), ('vencida', 'Vencida'), ('cancelada', 'Cancelada')], default='pendente', help_text='Estado atual da multa no ciclo de cobrança', max_length=20, verbose_name='Status da Multa'),
        ),
        migrations.AlterField(
            model_name='multa',
            name='data_emissao',
            field=models.DateField(auto_now_add=True, help_text='Data em que a multa foi criada no sistema', verbose_name='Data de Emissão'),
        ),
        migrations.AlterField(
            model_name='multa',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='multas', to='multas.empresa', verbose_name='Empresa Autuada'),
        ),
        migrations.AlterField(
            model_name='multa',
            name='pago',
            field=models.BooleanField(default=False, help_text="Campo de compatibilidade - use o campo 'status'", verbose_name='Pago (Legacy)'),
        ),
        migrations.AlterField(
            model_name='multa',
            name='processo',
            field=models.OneToOneField(help_text='Auto de infração que originou esta multa (será migrado para Processo)', on_delete=django.db.models.deletion.PROTECT, related_name='multa', to='fiscalizacao.autoinfracao', verbose_name='Auto de Infração'),
        ),
        migrations.AlterField(
            model_name='multa',
            name='valor',
            field=models.DecimalField(decimal_places=2, help_text='Valor exato da penalidade financeira', max_digits=12, verbose_name='Valor da Multa (R$)'),
        ),
        migrations.AlterField(
            model_name='peticao',
            name='processo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='peticoes', to='fiscalizacao.processo', verbose_name='Processo Administrativo'),
        ),
        migrations.AlterField(
            model_name='recurso',
            name='processo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recursos', to='fiscalizacao.processo', verbose_name='Processo Administrativo'),
        ),
    ]
