# Generated by Django 4.2.11 on 2025-10-13 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multas', '0002_add_empresa_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multa',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('pago', 'Pago'), ('vencida', 'Vencida'), ('cancelada', 'Cancelada')], default='pendente', help_text='Estado atual da multa no ciclo de cobrança', max_length=20, verbose_name='Status da Multa'),
        ),
    ]
