# Generated by Django 5.2.5 on 2025-10-09 14:09

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PredictiveModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True, verbose_name='Código')),
                ('nome', models.CharField(max_length=120, verbose_name='Nome')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('tipo_algoritmo', models.CharField(choices=[('REGRESSION', 'Regressão'), ('CLASSIFICATION', 'Classificação'), ('TIME_SERIES', 'Série Temporal'), ('CLUSTERING', 'Clustering'), ('NLP', 'Processamento de Linguagem Natural'), ('RECOMMENDER', 'Recomendação'), ('CUSTOM', 'Customizado')], max_length=20, verbose_name='Tipo de Algoritmo')),
                ('origem_dados', models.CharField(blank=True, max_length=150, verbose_name='Origem dos Dados')),
                ('parametros_treinamento', models.JSONField(blank=True, default=dict, verbose_name='Parâmetros de Treinamento')),
                ('metricas_referencia', models.JSONField(blank=True, default=dict, verbose_name='Métricas de Referência')),
                ('versao', models.PositiveIntegerField(default=1, verbose_name='Versão')),
                ('ativo', models.BooleanField(default=True, verbose_name='Modelo Ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('criado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modelos_criados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Modelo Preditivo',
                'verbose_name_plural': 'Modelos Preditivos',
                'ordering': ['-ativo', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='ForecastResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referencia', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data de Referência')),
                ('horizonte', models.CharField(default='CURTO_PRAZO', max_length=30, verbose_name='Horizonte')),
                ('parametros_entrada', models.JSONField(blank=True, default=dict, verbose_name='Parâmetros de Entrada')),
                ('resultado_previsto', models.JSONField(blank=True, default=dict, verbose_name='Resultado Previsto')),
                ('status', models.CharField(choices=[('GERADO', 'Gerado'), ('ERRO', 'Erro'), ('AGENDADO', 'Agendado')], default='GERADO', max_length=15, verbose_name='Status')),
                ('gerado_em', models.DateTimeField(auto_now_add=True, verbose_name='Gerado em')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('gerado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='previsoes_geradas', to=settings.AUTH_USER_MODEL)),
                ('modelo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='previsoes', to='predictive_analytics.predictivemodel')),
            ],
            options={
                'verbose_name': 'Resultado de Previsão',
                'verbose_name_plural': 'Resultados de Previsão',
                'ordering': ['-gerado_em'],
                'indexes': [models.Index(fields=['modelo', '-gerado_em'], name='predictive__modelo__f1ab4e_idx'), models.Index(fields=['status'], name='predictive__status_4d013c_idx')],
            },
        ),
        migrations.CreateModel(
            name='TrainingJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iniciado_em', models.DateTimeField(auto_now_add=True, verbose_name='Iniciado em')),
                ('finalizado_em', models.DateTimeField(blank=True, null=True, verbose_name='Finalizado em')),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('EXECUTANDO', 'Executando'), ('SUCESSO', 'Sucesso'), ('FALHA', 'Falha'), ('CANCELADO', 'Cancelado')], default='PENDENTE', max_length=15, verbose_name='Status')),
                ('conjunto_dados', models.CharField(max_length=150, verbose_name='Conjunto de Dados')),
                ('parametros_execucao', models.JSONField(blank=True, default=dict, verbose_name='Parâmetros Executados')),
                ('metricas_resultado', models.JSONField(blank=True, default=dict, verbose_name='Métricas de Resultado')),
                ('log_execucao', models.TextField(blank=True, verbose_name='Log da Execução')),
                ('duracao_segundos', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='Duração (s)')),
                ('executado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs_treinamento', to=settings.AUTH_USER_MODEL)),
                ('modelo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs_treinamento', to='predictive_analytics.predictivemodel')),
            ],
            options={
                'verbose_name': 'Job de Treinamento',
                'verbose_name_plural': 'Jobs de Treinamento',
                'ordering': ['-iniciado_em'],
                'indexes': [models.Index(fields=['modelo', '-iniciado_em'], name='predictive__modelo__807bd0_idx'), models.Index(fields=['status', '-iniciado_em'], name='predictive__status_a73629_idx')],
            },
        ),
    ]
