# Generated by Django 5.2.5 on 2025-10-21 14:43

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiscalizacao', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MobileDeviceToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('device_id', models.CharField(max_length=100, verbose_name='ID do dispositivo')),
                ('expo_token', models.CharField(max_length=255, unique=True, verbose_name='Token de push')),
                ('plataforma', models.CharField(choices=[('android', 'Android'), ('ios', 'iOS'), ('web', 'Web')], max_length=20, verbose_name='Plataforma')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('ultimo_registro', models.DateTimeField(auto_now=True, verbose_name='Último registro')),
            ],
            options={
                'verbose_name': 'Token de Dispositivo Mobile',
                'verbose_name_plural': 'Tokens de Dispositivo Mobile',
            },
        ),
        migrations.CreateModel(
            name='MobileUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Token')),
                ('arquivo', models.FileField(upload_to='mobile_uploads/%Y/%m/%d', verbose_name='Arquivo')),
                ('mime_type', models.CharField(max_length=100, verbose_name='MIME type')),
                ('tamanho', models.PositiveIntegerField(verbose_name='Tamanho (bytes)')),
                ('device_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='ID do dispositivo')),
            ],
            options={
                'verbose_name': 'Upload Mobile',
                'verbose_name_plural': 'Uploads Mobile',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='PedidoNotificacaoMobile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('uuid_local', models.UUIDField(blank=True, default=uuid.uuid4, help_text='Identificador gerado pelo mobile para conciliação offline', null=True, unique=True, verbose_name='UUID local')),
                ('criado_no_mobile', models.BooleanField(default=False, help_text='Indica se o pedido se originou no aplicativo mobile', verbose_name='Criado pelo mobile')),
                ('device_id', models.CharField(blank=True, help_text='Identificador enviado via cabeçalho X-Device-Id', max_length=100, null=True, verbose_name='ID do dispositivo')),
                ('offline_em', models.DateTimeField(blank=True, help_text='Timestamp informado pelo app quando sem conexão', null=True, verbose_name='Registrado offline em')),
                ('sincronizado_em', models.DateTimeField(blank=True, help_text='Momento em que o backend recebeu o registro', null=True, verbose_name='Primeira sincronização')),
                ('tipo', models.CharField(max_length=50, verbose_name='Tipo de notificação')),
                ('canal_preferencial', models.CharField(max_length=50, verbose_name='Canal preferencial')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('anexos', models.JSONField(blank=True, default=list, help_text='Lista de tokens de upload enviados pelo mobile', verbose_name='Anexos')),
                ('status', models.CharField(choices=[('EM_ANALISE', 'Em análise'), ('EMITIDA', 'Emitida'), ('CANCELADA', 'Cancelada')], default='EM_ANALISE', max_length=20, verbose_name='Status')),
                ('notificacao_numero', models.CharField(blank=True, max_length=50, verbose_name='Número da notificação')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Pedido de Notificação Mobile',
                'verbose_name_plural': 'Pedidos de Notificação Mobile',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.AlterModelOptions(
            name='autoapreensaoinutilizacao',
            options={'ordering': ['-created_at'], 'verbose_name': 'Auto de ApreensÃ£o/InutilizaÃ§Ã£o', 'verbose_name_plural': 'Autos de ApreensÃ£o/InutilizaÃ§Ã£o'},
        ),
        migrations.AlterModelOptions(
            name='autoinfracao',
            options={'ordering': ['-data_fiscalizacao', '-numero'], 'verbose_name': 'Auto de InfraÃ§Ã£o', 'verbose_name_plural': 'Autos de InfraÃ§Ã£o'},
        ),
        migrations.AlterModelOptions(
            name='autoinfracaoavancado',
            options={'ordering': ['-data_modificacao'], 'verbose_name': 'Auto de InfraÃ§Ã£o AvanÃ§ado', 'verbose_name_plural': 'Autos de InfraÃ§Ã£o AvanÃ§ados'},
        ),
        migrations.AlterModelOptions(
            name='configuracaofiscalizacao',
            options={'verbose_name': 'ConfiguraÃ§Ã£o de FiscalizaÃ§Ã£o', 'verbose_name_plural': 'ConfiguraÃ§Ãµes de FiscalizaÃ§Ã£o'},
        ),
        migrations.AlterModelOptions(
            name='evidenciafiscalizacao',
            options={'ordering': ['-data_upload'], 'verbose_name': 'EvidÃªncia de FiscalizaÃ§Ã£o', 'verbose_name_plural': 'EvidÃªncias de FiscalizaÃ§Ã£o'},
        ),
        migrations.AlterModelOptions(
            name='evidenciafotografica',
            options={'ordering': ['-data_upload'], 'verbose_name': 'EvidÃªncia FotogrÃ¡fica', 'verbose_name_plural': 'EvidÃªncias FotogrÃ¡ficas'},
        ),
        migrations.AlterModelOptions(
            name='historicoautoinfracao',
            options={'ordering': ['-data_acao'], 'verbose_name': 'HistÃ³rico de Auto de InfraÃ§Ã£o', 'verbose_name_plural': 'HistÃ³rico de Autos de InfraÃ§Ã£o'},
        ),
        migrations.AlterModelOptions(
            name='historicoprocesso',
            options={'ordering': ['-data_mudanca'], 'verbose_name': 'HistÃ³rico do Processo', 'verbose_name_plural': 'HistÃ³ricos dos Processos'},
        ),
        migrations.AlterModelOptions(
            name='historicostatusinfracao',
            options={'ordering': ['-data_mudanca'], 'verbose_name': 'HistÃ³rico de Status', 'verbose_name_plural': 'HistÃ³ricos de Status'},
        ),
        migrations.AlterModelOptions(
            name='notificacaoeletronica',
            options={'ordering': ['-data_envio'], 'verbose_name': 'NotificaÃ§Ã£o EletrÃ´nica', 'verbose_name_plural': 'NotificaÃ§Ãµes EletrÃ´nicas'},
        ),
        migrations.AlterModelOptions(
            name='sequenciaautos',
            options={'ordering': ['-ano'], 'verbose_name': 'SequÃªncia de Auto', 'verbose_name_plural': 'SequÃªncias de Autos'},
        ),
        migrations.AlterModelOptions(
            name='sequenciaautosapreensao',
            options={'ordering': ['-ano'], 'verbose_name': 'SequÃªncia de Auto de ApreensÃ£o', 'verbose_name_plural': 'SequÃªncias de Autos de ApreensÃ£o'},
        ),
        migrations.AlterModelOptions(
            name='templateautoinfracao',
            options={'ordering': ['nome'], 'verbose_name': 'Template de Auto de InfraÃ§Ã£o', 'verbose_name_plural': 'Templates de Autos de InfraÃ§Ã£o'},
        ),
        migrations.AlterModelOptions(
            name='tipofiscalizacao',
            options={'ordering': ['nome'], 'verbose_name': 'Tipo de FiscalizaÃ§Ã£o', 'verbose_name_plural': 'Tipos de FiscalizaÃ§Ã£o'},
        ),
        migrations.AddField(
            model_name='autoapreensaoinutilizacao',
            name='criado_no_mobile',
            field=models.BooleanField(default=False, help_text='Indica se o registro veio do aplicativo mobile', verbose_name='Criado pelo mobile'),
        ),
        migrations.AddField(
            model_name='autoapreensaoinutilizacao',
            name='device_id',
            field=models.CharField(blank=True, help_text='Identificador enviado via cabecalho X-Device-Id', max_length=100, null=True, verbose_name='ID do dispositivo'),
        ),
        migrations.AddField(
            model_name='autoapreensaoinutilizacao',
            name='emitido_em',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Emitido em'),
        ),
        migrations.AddField(
            model_name='autoapreensaoinutilizacao',
            name='offline_em',
            field=models.DateTimeField(blank=True, help_text='Timestamp informado pelo app quando sem conexao', null=True, verbose_name='Registrado offline em'),
        ),
        migrations.AddField(
            model_name='autoapreensaoinutilizacao',
            name='sincronizado_em',
            field=models.DateTimeField(blank=True, help_text='Momento em que o backend recebeu o registro', null=True, verbose_name='Primeira sincronizacao'),
        ),
        migrations.AddField(
            model_name='autoapreensaoinutilizacao',
            name='uuid_local',
            field=models.UUIDField(blank=True, help_text='Identificador gerado no mobile para conciliacao offline', null=True, unique=True, verbose_name='UUID local'),
        ),
        migrations.AddField(
            model_name='autobanco',
            name='criado_no_mobile',
            field=models.BooleanField(default=False, help_text='Indica se o auto foi originado no aplicativo mobile', verbose_name='Criado pelo mobile'),
        ),
        migrations.AddField(
            model_name='autobanco',
            name='device_id',
            field=models.CharField(blank=True, help_text='Identificador enviado via cabeçalho X-Device-Id', max_length=100, null=True, verbose_name='ID do dispositivo'),
        ),
        migrations.AddField(
            model_name='autobanco',
            name='emitido_em',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Emitido em'),
        ),
        migrations.AddField(
            model_name='autobanco',
            name='offline_em',
            field=models.DateTimeField(blank=True, help_text='Timestamp local informado pelo app', null=True, verbose_name='Registrado offline em'),
        ),
        migrations.AddField(
            model_name='autobanco',
            name='sincronizado_em',
            field=models.DateTimeField(blank=True, help_text='Momento em que os dados chegaram ao backend', null=True, verbose_name='Primeira sincronização'),
        ),
        migrations.AddField(
            model_name='autobanco',
            name='uuid_local',
            field=models.UUIDField(blank=True, help_text='Identificador gerado no mobile para conciliação offline', null=True, unique=True, verbose_name='UUID local'),
        ),
        migrations.AddField(
            model_name='autodiversos',
            name='criado_no_mobile',
            field=models.BooleanField(default=False, help_text='Indica se o auto foi originado no aplicativo mobile', verbose_name='Criado pelo mobile'),
        ),
        migrations.AddField(
            model_name='autodiversos',
            name='device_id',
            field=models.CharField(blank=True, help_text='Identificador enviado via cabeçalho X-Device-Id', max_length=100, null=True, verbose_name='ID do dispositivo'),
        ),
        migrations.AddField(
            model_name='autodiversos',
            name='emitido_em',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Emitido em'),
        ),
        migrations.AddField(
            model_name='autodiversos',
            name='offline_em',
            field=models.DateTimeField(blank=True, help_text='Timestamp local informado pelo app', null=True, verbose_name='Registrado offline em'),
        ),
        migrations.AddField(
            model_name='autodiversos',
            name='sincronizado_em',
            field=models.DateTimeField(blank=True, help_text='Momento em que os dados chegaram ao backend', null=True, verbose_name='Primeira sincronização'),
        ),
        migrations.AddField(
            model_name='autodiversos',
            name='uuid_local',
            field=models.UUIDField(blank=True, help_text='Identificador gerado no mobile para conciliação offline', null=True, unique=True, verbose_name='UUID local'),
        ),
        migrations.AddField(
            model_name='autoinfracao',
            name='criado_no_mobile',
            field=models.BooleanField(default=False, help_text='Indica se o registro veio do aplicativo mobile', verbose_name='Criado pelo mobile'),
        ),
        migrations.AddField(
            model_name='autoinfracao',
            name='device_id',
            field=models.CharField(blank=True, help_text='Identificador enviado via cabecalho X-Device-Id', max_length=100, null=True, verbose_name='ID do dispositivo'),
        ),
        migrations.AddField(
            model_name='autoinfracao',
            name='emitido_em',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Emitido em'),
        ),
        migrations.AddField(
            model_name='autoinfracao',
            name='offline_em',
            field=models.DateTimeField(blank=True, help_text='Timestamp informado pelo app quando sem conexao', null=True, verbose_name='Registrado offline em'),
        ),
        migrations.AddField(
            model_name='autoinfracao',
            name='sincronizado_em',
            field=models.DateTimeField(blank=True, help_text='Momento em que o backend recebeu o registro', null=True, verbose_name='Primeira sincronizacao'),
        ),
        migrations.AddField(
            model_name='autoinfracao',
            name='uuid_local',
            field=models.UUIDField(blank=True, help_text='Identificador gerado no mobile para conciliacao offline', null=True, unique=True, verbose_name='UUID local'),
        ),
        migrations.AddField(
            model_name='autoposto',
            name='criado_no_mobile',
            field=models.BooleanField(default=False, help_text='Indica se o auto foi originado no aplicativo mobile', verbose_name='Criado pelo mobile'),
        ),
        migrations.AddField(
            model_name='autoposto',
            name='device_id',
            field=models.CharField(blank=True, help_text='Identificador enviado via cabeçalho X-Device-Id', max_length=100, null=True, verbose_name='ID do dispositivo'),
        ),
        migrations.AddField(
            model_name='autoposto',
            name='emitido_em',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Emitido em'),
        ),
        migrations.AddField(
            model_name='autoposto',
            name='offline_em',
            field=models.DateTimeField(blank=True, help_text='Timestamp local informado pelo app', null=True, verbose_name='Registrado offline em'),
        ),
        migrations.AddField(
            model_name='autoposto',
            name='sincronizado_em',
            field=models.DateTimeField(blank=True, help_text='Momento em que os dados chegaram ao backend', null=True, verbose_name='Primeira sincronização'),
        ),
        migrations.AddField(
            model_name='autoposto',
            name='uuid_local',
            field=models.UUIDField(blank=True, help_text='Identificador gerado no mobile para conciliação offline', null=True, unique=True, verbose_name='UUID local'),
        ),
        migrations.AddField(
            model_name='autosupermercado',
            name='criado_no_mobile',
            field=models.BooleanField(default=False, help_text='Indica se o auto foi originado no aplicativo mobile', verbose_name='Criado pelo mobile'),
        ),
        migrations.AddField(
            model_name='autosupermercado',
            name='device_id',
            field=models.CharField(blank=True, help_text='Identificador enviado via cabeçalho X-Device-Id', max_length=100, null=True, verbose_name='ID do dispositivo'),
        ),
        migrations.AddField(
            model_name='autosupermercado',
            name='emitido_em',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Emitido em'),
        ),
        migrations.AddField(
            model_name='autosupermercado',
            name='offline_em',
            field=models.DateTimeField(blank=True, help_text='Timestamp local informado pelo app', null=True, verbose_name='Registrado offline em'),
        ),
        migrations.AddField(
            model_name='autosupermercado',
            name='sincronizado_em',
            field=models.DateTimeField(blank=True, help_text='Momento em que os dados chegaram ao backend', null=True, verbose_name='Primeira sincronização'),
        ),
        migrations.AddField(
            model_name='autosupermercado',
            name='uuid_local',
            field=models.UUIDField(blank=True, help_text='Identificador gerado no mobile para conciliação offline', null=True, unique=True, verbose_name='UUID local'),
        ),
        migrations.AlterField(
            model_name='anexoauto',
            name='descricao',
            field=models.CharField(blank=True, max_length=255, verbose_name='DescriÃ§Ã£o'),
        ),
        migrations.AlterField(
            model_name='assinaturadigital',
            name='data_expiracao',
            field=models.DateTimeField(verbose_name='Data de ExpiraÃ§Ã£o'),
        ),
        migrations.AlterField(
            model_name='assinaturadigital',
            name='tipo_assinatura',
            field=models.CharField(choices=[('fiscal_1', 'Fiscal 1'), ('fiscal_2', 'Fiscal 2'), ('responsavel', 'ResponsÃ¡vel'), ('testemunha', 'Testemunha')], max_length=20, verbose_name='Tipo de Assinatura'),
        ),
        migrations.AlterField(
            model_name='atendimentocaixabanco',
            name='horario_atendimento',
            field=models.TimeField(verbose_name='HorÃ¡rio de Atendimento'),
        ),
        migrations.AlterField(
            model_name='atendimentocaixabanco',
            name='horario_chegada',
            field=models.TimeField(verbose_name='HorÃ¡rio de Chegada'),
        ),
        migrations.AlterField(
            model_name='autoapreensaoinutilizacao',
            name='auto_constatacao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='autos_apreensao_inutilizacao', to='fiscalizacao.autosupermercado', verbose_name='Auto de ConstataÃ§Ã£o'),
        ),
        migrations.AlterField(
            model_name='autoapreensaoinutilizacao',
            name='auto_constatacao_numero',
            field=models.CharField(max_length=20, verbose_name='Auto de ConstataÃ§Ã£o NÂº'),
        ),
        migrations.AlterField(
            model_name='autoapreensaoinutilizacao',
            name='cominacao_legal',
            field=models.TextField(verbose_name='CominaÃ§Ã£o Legal'),
        ),
        migrations.AlterField(
            model_name='autoapreensaoinutilizacao',
            name='cpf_responsavel',
            field=models.CharField(max_length=14, verbose_name='CPF do ResponsÃ¡vel'),
        ),
        migrations.AlterField(
            model_name='autoapreensaoinutilizacao',
            name='endereco',
            field=models.TextField(verbose_name='EndereÃ§o'),
        ),
        migrations.AlterField(
            model_name='autoapreensaoinutilizacao',
            name='hora_inicio',
            field=models.TimeField(verbose_name='Hora do InÃ\xadcio'),
        ),
        migrations.AlterField(
            model_name='autoapreensaoinutilizacao',
            name='hora_termino',
            field=models.TimeField(verbose_name='Hora do TÃ©rmino'),
        ),
        migrations.AlterField(
            model_name='autoapreensaoinutilizacao',
            name='municipio',
            field=models.CharField(max_length=100, verbose_name='MunicÃ\xadpio'),
        ),
        migrations.AlterField(
            model_name='autoapreensaoinutilizacao',
            name='necessita_pericia',
            field=models.BooleanField(default=False, verbose_name='Necessita PerÃ\xadcia'),
        ),
        migrations.AlterField(
            model_name='autoapreensaoinutilizacao',
            name='razao_social',
            field=models.CharField(max_length=200, verbose_name='RazÃ£o Social'),
        ),
        migrations.AlterField(
            model_name='autoapreensaoinutilizacao',
            name='responsavel_estabelecimento',
            field=models.CharField(max_length=100, verbose_name='Nome do ResponsÃ¡vel'),
        ),
        migrations.AlterField(
            model_name='autoapreensaoinutilizacao',
            name='tipo_documento',
            field=models.CharField(choices=[('apreensao', 'Auto de ApreensÃ£o'), ('inutilizacao', 'InutilizaÃ§Ã£o')], default='apreensao', max_length=20),
        ),
        migrations.AlterField(
            model_name='autobanco',
            name='atuacao',
            field=models.CharField(blank=True, max_length=100, verbose_name='AtuaÃ§Ã£o'),
        ),
        migrations.AlterField(
            model_name='autobanco',
            name='ausencia_cartaz_informativo',
            field=models.BooleanField(default=False, verbose_name='AusÃªncia de Cartaz Informativo?'),
        ),
        migrations.AlterField(
            model_name='autobanco',
            name='ausencia_profissional_libras',
            field=models.BooleanField(default=False, verbose_name='AusÃªncia de profissional de LIBRAS?'),
        ),
        migrations.AlterField(
            model_name='autobanco',
            name='data_fiscalizacao',
            field=models.DateField(verbose_name='Data da FiscalizaÃ§Ã£o'),
        ),
        migrations.AlterField(
            model_name='autobanco',
            name='distribuiu_senha_fora_padrao',
            field=models.BooleanField(blank=True, null=True, verbose_name='Distribuiu senha fora do padrÃ£o?'),
        ),
        migrations.AlterField(
            model_name='autobanco',
            name='endereco',
            field=models.CharField(max_length=255, verbose_name='EndereÃ§o'),
        ),
        migrations.AlterField(
            model_name='autobanco',
            name='fiscal_nome_1',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome do 1Âº Fiscal'),
        ),
        migrations.AlterField(
            model_name='autobanco',
            name='fiscal_nome_2',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome do 2Âº Fiscal'),
        ),
        migrations.AlterField(
            model_name='autobanco',
            name='hora_fiscalizacao',
            field=models.TimeField(verbose_name='Hora da FiscalizaÃ§Ã£o'),
        ),
        migrations.AlterField(
            model_name='autobanco',
            name='municipio',
            field=models.CharField(max_length=100, verbose_name='MunicÃ\xadpio'),
        ),
        migrations.AlterField(
            model_name='autobanco',
            name='numero',
            field=models.CharField(blank=True, max_length=20, unique=True, verbose_name='NÃºmero do Auto'),
        ),
        migrations.AlterField(
            model_name='autobanco',
            name='observacoes',
            field=models.TextField(blank=True, verbose_name='ObservaÃ§Ãµes'),
        ),
        migrations.AlterField(
            model_name='autobanco',
            name='origem',
            field=models.CharField(choices=[('acao', 'AÃ§Ã£o FiscalizatÃ³ria'), ('denuncia', 'DenÃºncia'), ('forca_tarefa', 'ForÃ§a Tarefa'), ('outros', 'Outros')], default='acao', max_length=20, verbose_name='Origem'),
        ),
        migrations.AlterField(
            model_name='autobanco',
            name='porte',
            field=models.CharField(blank=True, choices=[('microempresa', 'Microempresa'), ('pequeno', 'Pequeno Porte'), ('medio', 'MÃ©dio Porte'), ('grande', 'Grande Porte')], max_length=100, verbose_name='Porte'),
        ),
        migrations.AlterField(
            model_name='autobanco',
            name='razao_social',
            field=models.CharField(max_length=255, verbose_name='RazÃ£o Social'),
        ),
        migrations.AlterField(
            model_name='autobanco',
            name='responsavel_cpf',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='CPF/RG do ResponsÃ¡vel'),
        ),
        migrations.AlterField(
            model_name='autobanco',
            name='responsavel_nome',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome do ResponsÃ¡vel'),
        ),
        migrations.AlterField(
            model_name='autobanco',
            name='sem_irregularidades',
            field=models.BooleanField(default=False, verbose_name='NÃ£o foram encontradas irregularidades'),
        ),
        migrations.AlterField(
            model_name='autobanco',
            name='senha_sem_horarios',
            field=models.BooleanField(default=False, verbose_name='Senha sem horÃ¡rios?'),
        ),
        migrations.AlterField(
            model_name='autodiversos',
            name='advertencia',
            field=models.BooleanField(default=False, verbose_name='Houve AdvertÃªncia?'),
        ),
        migrations.AlterField(
            model_name='autodiversos',
            name='afixacao_precos_eletronico_fora_padrao',
            field=models.BooleanField(default=False, verbose_name='AfixaÃ§Ã£o de preÃ§os no comÃ©rcio eletrÃ´nico fora do padrÃ£o'),
        ),
        migrations.AlterField(
            model_name='autodiversos',
            name='afixacao_precos_fora_padrao',
            field=models.BooleanField(default=False, verbose_name='AfixaÃ§Ã£o de preÃ§os fora do padrÃ£o'),
        ),
        migrations.AlterField(
            model_name='autodiversos',
            name='afixacao_precos_fracionados_fora_padrao',
            field=models.BooleanField(default=False, verbose_name='AfixaÃ§Ã£o de preÃ§os na venda a varejo de produtos fracionados fora do padrÃ£o'),
        ),
        migrations.AlterField(
            model_name='autodiversos',
            name='atuacao',
            field=models.CharField(blank=True, max_length=100, verbose_name='AtuaÃ§Ã£o'),
        ),
        migrations.AlterField(
            model_name='autodiversos',
            name='ausencia_afixacao_precos',
            field=models.BooleanField(default=False, verbose_name='AusÃªncia de afixaÃ§Ã£o de preÃ§os'),
        ),
        migrations.AlterField(
            model_name='autodiversos',
            name='ausencia_afixacao_precos_eletronico',
            field=models.BooleanField(default=False, verbose_name='AusÃªncia de afixaÃ§Ã£o de preÃ§os no comÃ©rcio eletrÃ´nico'),
        ),
        migrations.AlterField(
            model_name='autodiversos',
            name='ausencia_exemplar_cdc',
            field=models.BooleanField(default=False, verbose_name='AusÃªncia do exemplar do CDC em local visÃ\xadvel'),
        ),
        migrations.AlterField(
            model_name='autodiversos',
            name='ausencia_visibilidade_descontos',
            field=models.BooleanField(default=False, verbose_name='AusÃªncia de visibilidade de descontos'),
        ),
        migrations.AlterField(
            model_name='autodiversos',
            name='data_fiscalizacao',
            field=models.DateField(verbose_name='Data da FiscalizaÃ§Ã£o'),
        ),
        migrations.AlterField(
            model_name='autodiversos',
            name='endereco',
            field=models.CharField(max_length=255, verbose_name='EndereÃ§o'),
        ),
        migrations.AlterField(
            model_name='autodiversos',
            name='fiscal_nome_1',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome do 1Âº Fiscal'),
        ),
        migrations.AlterField(
            model_name='autodiversos',
            name='fiscal_nome_2',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome do 2Âº Fiscal'),
        ),
        migrations.AlterField(
            model_name='autodiversos',
            name='hora_fiscalizacao',
            field=models.TimeField(verbose_name='Hora da FiscalizaÃ§Ã£o'),
        ),
        migrations.AlterField(
            model_name='autodiversos',
            name='municipio',
            field=models.CharField(max_length=100, verbose_name='MunicÃ\xadpio'),
        ),
        migrations.AlterField(
            model_name='autodiversos',
            name='numero',
            field=models.CharField(blank=True, max_length=20, unique=True, verbose_name='NÃºmero do Auto'),
        ),
        migrations.AlterField(
            model_name='autodiversos',
            name='origem',
            field=models.CharField(choices=[('acao', 'AÃ§Ã£o FiscalizatÃ³ria'), ('denuncia', 'DenÃºncia'), ('forca_tarefa', 'ForÃ§a Tarefa'), ('outros', 'Outros')], default='acao', max_length=20, verbose_name='Origem'),
        ),
        migrations.AlterField(
            model_name='autodiversos',
            name='outras_irregularidades',
            field=models.TextField(blank=True, verbose_name='Outras Irregularidades Constatadas/Outras CominaÃ§Ãµes Legais'),
        ),
        migrations.AlterField(
            model_name='autodiversos',
            name='porte',
            field=models.CharField(blank=True, choices=[('microempresa', 'Microempresa'), ('pequeno', 'Pequeno Porte'), ('medio', 'MÃ©dio Porte'), ('grande', 'Grande Porte')], max_length=100, verbose_name='Porte'),
        ),
        migrations.AlterField(
            model_name='autodiversos',
            name='razao_social',
            field=models.CharField(max_length=255, verbose_name='RazÃ£o Social'),
        ),
        migrations.AlterField(
            model_name='autodiversos',
            name='responsavel_cpf',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='CPF/RG do ResponsÃ¡vel'),
        ),
        migrations.AlterField(
            model_name='autodiversos',
            name='responsavel_nome',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome do ResponsÃ¡vel'),
        ),
        migrations.AlterField(
            model_name='autodiversos',
            name='substituicao_troco',
            field=models.BooleanField(default=False, verbose_name='SubstituiÃ§Ã£o do troco em dinheiro por outros produtos nÃ£o consentidos'),
        ),
        migrations.AlterField(
            model_name='autoinfracao',
            name='assinatura_fiscal',
            field=models.ImageField(blank=True, null=True, upload_to='assinaturas/infracoes/', verbose_name='Assinatura do Fiscal'),
        ),
        migrations.AlterField(
            model_name='autoinfracao',
            name='assinatura_responsavel',
            field=models.ImageField(blank=True, null=True, upload_to='assinaturas/infracoes/', verbose_name='Assinatura do Responsavel'),
        ),
        migrations.AlterField(
            model_name='autoinfracao',
            name='atividade',
            field=models.CharField(default='NÃ£o informado', max_length=255, verbose_name='Atividade'),
        ),
        migrations.AlterField(
            model_name='autoinfracao',
            name='base_legal_outras',
            field=models.TextField(blank=True, help_text='Outras leis e decretos aplicÃ¡veis', verbose_name='Outras Bases Legais'),
        ),
        migrations.AlterField(
            model_name='autoinfracao',
            name='data_fiscalizacao',
            field=models.DateField(verbose_name='Data da FiscalizaÃ§Ã£o'),
        ),
        migrations.AlterField(
            model_name='autoinfracao',
            name='data_notificacao',
            field=models.DateField(blank=True, null=True, verbose_name='Data de NotificaÃ§Ã£o'),
        ),
        migrations.AlterField(
            model_name='autoinfracao',
            name='descricao_anexo',
            field=models.TextField(blank=True, verbose_name='DescriÃ§Ã£o dos Anexos'),
        ),
        migrations.AlterField(
            model_name='autoinfracao',
            name='endereco',
            field=models.CharField(max_length=500, verbose_name='EndereÃ§o'),
        ),
        migrations.AlterField(
            model_name='autoinfracao',
            name='estabelecimento_responsavel',
            field=models.CharField(blank=True, max_length=255, verbose_name='ResponsÃ¡vel pelo Estabelecimento'),
        ),
        migrations.AlterField(
            model_name='autoinfracao',
            name='fiscal_cargo',
            field=models.CharField(default='Agente de FiscalizaÃ§Ã£o', max_length=100, verbose_name='Cargo do Fiscal'),
        ),
        migrations.AlterField(
            model_name='autoinfracao',
            name='fundamentacao_juridica',
            field=models.TextField(blank=True, help_text='FundamentaÃ§Ã£o jurÃ\xaddica da autuaÃ§Ã£o', verbose_name='FundamentaÃ§Ã£o JurÃ\xaddica'),
        ),
        migrations.AlterField(
            model_name='autoinfracao',
            name='fundamentacao_tecnica',
            field=models.TextField(blank=True, help_text='FundamentaÃ§Ã£o tÃ©cnica da autuaÃ§Ã£o', verbose_name='FundamentaÃ§Ã£o TÃ©cnica'),
        ),
        migrations.AlterField(
            model_name='autoinfracao',
            name='hora_fiscalizacao',
            field=models.TimeField(verbose_name='Hora da FiscalizaÃ§Ã£o'),
        ),
        migrations.AlterField(
            model_name='autoinfracao',
            name='infracao_falta_informacao',
            field=models.BooleanField(default=False, verbose_name='Falta de InformaÃ§Ã£o'),
        ),
        migrations.AlterField(
            model_name='autoinfracao',
            name='infracao_precos_abusivos',
            field=models.BooleanField(default=False, verbose_name='PreÃ§os Abusivos'),
        ),
        migrations.AlterField(
            model_name='autoinfracao',
            name='municipio',
            field=models.CharField(default='MANAUS', max_length=100, verbose_name='MunicÃ\xadpio'),
        ),
        migrations.AlterField(
            model_name='autoinfracao',
            name='numero',
            field=models.CharField(blank=True, max_length=20, unique=True, verbose_name='NÃºmero da InfraÃ§Ã£o'),
        ),
        migrations.AlterField(
            model_name='autoinfracao',
            name='observacoes',
            field=models.TextField(blank=True, verbose_name='ObservaÃ§Ãµes'),
        ),
        migrations.AlterField(
            model_name='autoinfracao',
            name='outras_infracoes',
            field=models.TextField(blank=True, verbose_name='Outras InfraÃ§Ãµes'),
        ),
        migrations.AlterField(
            model_name='autoinfracao',
            name='parecer_numero',
            field=models.CharField(blank=True, help_text='Ex: 152/2025', max_length=50, verbose_name='NÃºmero do Parecer'),
        ),
        migrations.AlterField(
            model_name='autoinfracao',
            name='parecer_origem',
            field=models.CharField(default='FISCALIZAÃ\x87Ã\x83O/PROCON/AM', max_length=100, verbose_name='Origem do Parecer'),
        ),
        migrations.AlterField(
            model_name='autoinfracao',
            name='razao_social',
            field=models.CharField(max_length=255, verbose_name='RazÃ£o Social'),
        ),
        migrations.AlterField(
            model_name='autoinfracao',
            name='relatorio',
            field=models.TextField(help_text='Narrativa detalhada dos fatos constatados durante a fiscalizaÃ§Ã£o', verbose_name='RelatÃ³rio'),
        ),
        migrations.AlterField(
            model_name='autoinfracao',
            name='responsavel_cpf',
            field=models.CharField(max_length=14, verbose_name='CPF do ResponsÃ¡vel'),
        ),
        migrations.AlterField(
            model_name='autoinfracao',
            name='responsavel_funcao',
            field=models.CharField(blank=True, max_length=100, verbose_name='FunÃ§Ã£o/Cargo'),
        ),
        migrations.AlterField(
            model_name='autoinfracao',
            name='responsavel_nome',
            field=models.CharField(max_length=255, verbose_name='Nome do ResponsÃ¡vel'),
        ),
        migrations.AlterField(
            model_name='autoinfracaoavancado',
            name='data_geracao',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data de GeraÃ§Ã£o'),
        ),
        migrations.AlterField(
            model_name='autoinfracaoavancado',
            name='data_modificacao',
            field=models.DateTimeField(auto_now=True, verbose_name='Data de ModificaÃ§Ã£o'),
        ),
        migrations.AlterField(
            model_name='autoinfracaoavancado',
            name='data_notificacao',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data de NotificaÃ§Ã£o'),
        ),
        migrations.AlterField(
            model_name='autoinfracaoavancado',
            name='email_notificacao',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email de NotificaÃ§Ã£o'),
        ),
        migrations.AlterField(
            model_name='autoinfracaoavancado',
            name='notificacao_eletronica',
            field=models.BooleanField(default=False, verbose_name='NotificaÃ§Ã£o EletrÃ´nica'),
        ),
        migrations.AlterField(
            model_name='autoinfracaoavancado',
            name='protocolo_notificacao',
            field=models.CharField(blank=True, max_length=100, verbose_name='Protocolo de NotificaÃ§Ã£o'),
        ),
        migrations.AlterField(
            model_name='autoinfracaoavancado',
            name='status_workflow',
            field=models.CharField(choices=[('RASCUNHO', 'Rascunho'), ('EM_ANALISE', 'Em AnÃ¡lise'), ('APROVADO', 'Aprovado'), ('ASSINADO', 'Assinado'), ('NOTIFICADO', 'Notificado'), ('EM_DEFESA', 'Em Defesa'), ('JULGADO', 'Julgado'), ('PAGO', 'Pago'), ('CANCELADO', 'Cancelado')], default='RASCUNHO', max_length=20, verbose_name='Status do Workflow'),
        ),
        migrations.AlterField(
            model_name='autoinfracaoavancado',
            name='versao_documento',
            field=models.CharField(default='1.0', max_length=20, verbose_name='VersÃ£o do Documento'),
        ),
        migrations.AlterField(
            model_name='autoposto',
            name='atuacao',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='AtuaÃ§Ã£o'),
        ),
        migrations.AlterField(
            model_name='autoposto',
            name='data_fiscalizacao',
            field=models.DateField(verbose_name='Data da FiscalizaÃ§Ã£o'),
        ),
        migrations.AlterField(
            model_name='autoposto',
            name='endereco',
            field=models.CharField(max_length=255, verbose_name='EndereÃ§o'),
        ),
        migrations.AlterField(
            model_name='autoposto',
            name='fiscal_nome_1',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome do 1Âº Fiscal'),
        ),
        migrations.AlterField(
            model_name='autoposto',
            name='fiscal_nome_2',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome do 2Âº Fiscal'),
        ),
        migrations.AlterField(
            model_name='autoposto',
            name='hora_fiscalizacao',
            field=models.TimeField(verbose_name='Hora da FiscalizaÃ§Ã£o'),
        ),
        migrations.AlterField(
            model_name='autoposto',
            name='info_adicionais',
            field=models.TextField(blank=True, null=True, verbose_name='InformaÃ§Ãµes Adicionais'),
        ),
        migrations.AlterField(
            model_name='autoposto',
            name='matricula_fiscal_1',
            field=models.CharField(blank=True, help_text='MatrÃ\xadcula do fiscal responsÃ¡vel pela fiscalizaÃ§Ã£o', max_length=20, null=True, verbose_name='MatrÃ\xadcula do Fiscal 1'),
        ),
        migrations.AlterField(
            model_name='autoposto',
            name='municipio',
            field=models.CharField(max_length=100, verbose_name='MunicÃ\xadpio'),
        ),
        migrations.AlterField(
            model_name='autoposto',
            name='nao_vende_diesel_comum',
            field=models.BooleanField(default=False, verbose_name='NÃ£o vende Diesel Comum'),
        ),
        migrations.AlterField(
            model_name='autoposto',
            name='nao_vende_diesel_s10',
            field=models.BooleanField(default=False, verbose_name='NÃ£o vende Diesel S-10'),
        ),
        migrations.AlterField(
            model_name='autoposto',
            name='nao_vende_etanol',
            field=models.BooleanField(default=False, verbose_name='NÃ£o vende Etanol'),
        ),
        migrations.AlterField(
            model_name='autoposto',
            name='nao_vende_gas_aditivada',
            field=models.BooleanField(default=False, verbose_name='NÃ£o vende Gasolina Aditivada'),
        ),
        migrations.AlterField(
            model_name='autoposto',
            name='nao_vende_gas_comum',
            field=models.BooleanField(default=False, verbose_name='NÃ£o vende Gasolina Comum'),
        ),
        migrations.AlterField(
            model_name='autoposto',
            name='nao_vende_gnv',
            field=models.BooleanField(default=False, verbose_name='NÃ£o vende GNV'),
        ),
        migrations.AlterField(
            model_name='autoposto',
            name='numero',
            field=models.CharField(blank=True, max_length=20, unique=True, verbose_name='NÃºmero do Auto'),
        ),
        migrations.AlterField(
            model_name='autoposto',
            name='origem',
            field=models.CharField(choices=[('acao', 'AÃ§Ã£o FiscalizatÃ³ria'), ('denuncia', 'DenÃºncia'), ('forca_tarefa', 'ForÃ§a Tarefa'), ('outros', 'Outros')], default='acao', max_length=20, verbose_name='Origem'),
        ),
        migrations.AlterField(
            model_name='autoposto',
            name='porte',
            field=models.CharField(blank=True, choices=[('microempresa', 'Microempresa'), ('pequeno', 'Pequeno Porte'), ('medio', 'MÃ©dio Porte'), ('grande', 'Grande Porte')], max_length=20, null=True, verbose_name='Porte da Empresa'),
        ),
        migrations.AlterField(
            model_name='autoposto',
            name='preco_diesel_comum',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True, verbose_name='PreÃ§o Diesel Comum (R$/litro)'),
        ),
        migrations.AlterField(
            model_name='autoposto',
            name='preco_diesel_s10',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True, verbose_name='PreÃ§o Diesel S-10 (R$/litro)'),
        ),
        migrations.AlterField(
            model_name='autoposto',
            name='preco_etanol',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True, verbose_name='PreÃ§o Etanol (R$/litro)'),
        ),
        migrations.AlterField(
            model_name='autoposto',
            name='preco_gasolina_aditivada',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True, verbose_name='PreÃ§o Gasolina Aditivada (R$/litro)'),
        ),
        migrations.AlterField(
            model_name='autoposto',
            name='preco_gasolina_comum',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True, verbose_name='PreÃ§o Gasolina Comum (R$/litro)'),
        ),
        migrations.AlterField(
            model_name='autoposto',
            name='preco_gnv',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True, verbose_name='PreÃ§o GNV (R$/mÂ³)'),
        ),
        migrations.AlterField(
            model_name='autoposto',
            name='razao_social',
            field=models.CharField(max_length=255, verbose_name='RazÃ£o Social'),
        ),
        migrations.AlterField(
            model_name='autoposto',
            name='responsavel_cpf',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='CPF/RG do ResponsÃ¡vel'),
        ),
        migrations.AlterField(
            model_name='autoposto',
            name='responsavel_nome',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome do ResponsÃ¡vel'),
        ),
        migrations.AlterField(
            model_name='autosupermercado',
            name='afixacao_precos_fora_padrao',
            field=models.BooleanField(default=False, verbose_name='AfixaÃ§Ã£o de preÃ§os fora do padrÃ£o'),
        ),
        migrations.AlterField(
            model_name='autosupermercado',
            name='afixacao_precos_fracionados_fora_padrao',
            field=models.BooleanField(default=False, verbose_name='AfixaÃ§Ã£o de preÃ§os na venda a varejo de produtos fracionados fora do padrÃ£o'),
        ),
        migrations.AlterField(
            model_name='autosupermercado',
            name='ausencia_afixacao_precos',
            field=models.BooleanField(default=False, verbose_name='AusÃªncia de afixaÃ§Ã£o de preÃ§os'),
        ),
        migrations.AlterField(
            model_name='autosupermercado',
            name='ausencia_placas_promocao_vencimento',
            field=models.BooleanField(default=False, verbose_name='AusÃªncia das placas ou cartazes informativos acerca da data de validade de produtos em promoÃ§Ã£o'),
        ),
        migrations.AlterField(
            model_name='autosupermercado',
            name='ausencia_visibilidade_descontos',
            field=models.BooleanField(default=False, verbose_name='AusÃªncia de visibilidade de descontos'),
        ),
        migrations.AlterField(
            model_name='autosupermercado',
            name='auto_apreensao',
            field=models.BooleanField(default=False, verbose_name='Gerou Auto de ApreensÃ£o/InutilizaÃ§Ã£o?'),
        ),
        migrations.AlterField(
            model_name='autosupermercado',
            name='auto_apreensao_numero',
            field=models.CharField(blank=True, max_length=50, verbose_name='NÂº do Auto de ApreensÃ£o'),
        ),
        migrations.AlterField(
            model_name='autosupermercado',
            name='comercializar_sem_validade',
            field=models.BooleanField(default=False, verbose_name='Comercializar produtos sem validade ou com validade ilegÃ\xadvel'),
        ),
        migrations.AlterField(
            model_name='autosupermercado',
            name='cominacao_legal',
            field=models.TextField(blank=True, verbose_name='CominaÃ§Ã£o Legal'),
        ),
        migrations.AlterField(
            model_name='autosupermercado',
            name='data_fiscalizacao',
            field=models.DateField(verbose_name='Data da FiscalizaÃ§Ã£o'),
        ),
        migrations.AlterField(
            model_name='autosupermercado',
            name='endereco',
            field=models.CharField(max_length=255, verbose_name='EndereÃ§o'),
        ),
        migrations.AlterField(
            model_name='autosupermercado',
            name='fiscal_nome_1',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome do 1Âº Fiscal'),
        ),
        migrations.AlterField(
            model_name='autosupermercado',
            name='fiscal_nome_2',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome do 2Âº Fiscal'),
        ),
        migrations.AlterField(
            model_name='autosupermercado',
            name='hora_fiscalizacao',
            field=models.TimeField(verbose_name='Hora da FiscalizaÃ§Ã£o'),
        ),
        migrations.AlterField(
            model_name='autosupermercado',
            name='instrucoes_fiscalizado',
            field=models.TextField(blank=True, verbose_name='InstruÃ§Ãµes ao Fiscalizado'),
        ),
        migrations.AlterField(
            model_name='autosupermercado',
            name='justificativa_pericia',
            field=models.TextField(blank=True, verbose_name='Justificativa da PerÃ\xadcia'),
        ),
        migrations.AlterField(
            model_name='autosupermercado',
            name='municipio',
            field=models.CharField(max_length=100, verbose_name='MunicÃ\xadpio'),
        ),
        migrations.AlterField(
            model_name='autosupermercado',
            name='necessita_pericia',
            field=models.BooleanField(blank=True, null=True, verbose_name='Os itens apreendidos necessitam de perÃ\xadcia?'),
        ),
        migrations.AlterField(
            model_name='autosupermercado',
            name='numero',
            field=models.CharField(blank=True, max_length=20, unique=True, verbose_name='NÃºmero do Auto'),
        ),
        migrations.AlterField(
            model_name='autosupermercado',
            name='obstrucao_monitor',
            field=models.BooleanField(default=False, verbose_name='ObstruÃ§Ã£o do monitor'),
        ),
        migrations.AlterField(
            model_name='autosupermercado',
            name='origem',
            field=models.CharField(choices=[('acao', 'AÃ§Ã£o FiscalizatÃ³ria'), ('denuncia', 'DenÃºncia'), ('forca_tarefa', 'ForÃ§a Tarefa'), ('outros', 'Outros')], default='acao', max_length=20, verbose_name='Origem'),
        ),
        migrations.AlterField(
            model_name='autosupermercado',
            name='outras_irregularidades',
            field=models.TextField(blank=True, verbose_name='Outras Irregularidades Constatadas/Outras CominaÃ§Ãµes Legais'),
        ),
        migrations.AlterField(
            model_name='autosupermercado',
            name='razao_social',
            field=models.CharField(max_length=255, verbose_name='RazÃ£o Social'),
        ),
        migrations.AlterField(
            model_name='autosupermercado',
            name='responsavel_cpf',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='CPF/RG do ResponsÃ¡vel'),
        ),
        migrations.AlterField(
            model_name='autosupermercado',
            name='responsavel_nome',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome do ResponsÃ¡vel'),
        ),
        migrations.AlterField(
            model_name='configuracaofiscalizacao',
            name='assinatura_digital_obrigatoria',
            field=models.BooleanField(default=True, verbose_name='Assinatura Digital ObrigatÃ³ria'),
        ),
        migrations.AlterField(
            model_name='configuracaofiscalizacao',
            name='backup_automatico',
            field=models.BooleanField(default=True, verbose_name='Backup AutomÃ¡tico'),
        ),
        migrations.AlterField(
            model_name='configuracaofiscalizacao',
            name='certificado_digital_obrigatorio',
            field=models.BooleanField(default=False, verbose_name='Certificado Digital ObrigatÃ³rio'),
        ),
        migrations.AlterField(
            model_name='configuracaofiscalizacao',
            name='email_notificacao',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email para NotificaÃ§Ãµes'),
        ),
        migrations.AlterField(
            model_name='configuracaofiscalizacao',
            name='max_arquivos_por_auto',
            field=models.IntegerField(default=20, verbose_name='MÃ¡ximo de Arquivos por Auto'),
        ),
        migrations.AlterField(
            model_name='configuracaofiscalizacao',
            name='max_tamanho_arquivo',
            field=models.IntegerField(default=10, verbose_name='Tamanho MÃ¡ximo de Arquivo (MB)'),
        ),
        migrations.AlterField(
            model_name='configuracaofiscalizacao',
            name='notificacao_automatica',
            field=models.BooleanField(default=True, verbose_name='NotificaÃ§Ã£o AutomÃ¡tica'),
        ),
        migrations.AlterField(
            model_name='configuracaofiscalizacao',
            name='retencao_backup_dias',
            field=models.IntegerField(default=365, verbose_name='RetenÃ§Ã£o de Backup (dias)'),
        ),
        migrations.AlterField(
            model_name='configuracaofiscalizacao',
            name='sms_notificacao',
            field=models.CharField(blank=True, max_length=20, verbose_name='SMS para NotificaÃ§Ãµes'),
        ),
        migrations.AlterField(
            model_name='controleprazos',
            name='data_inicio',
            field=models.DateTimeField(verbose_name='Data de InÃ\xadcio'),
        ),
        migrations.AlterField(
            model_name='controleprazos',
            name='data_prorrogacao',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data de ProrrogaÃ§Ã£o'),
        ),
        migrations.AlterField(
            model_name='controleprazos',
            name='descricao',
            field=models.TextField(verbose_name='DescriÃ§Ã£o do Prazo'),
        ),
        migrations.AlterField(
            model_name='controleprazos',
            name='historico_alteracoes',
            field=models.JSONField(blank=True, default=list, verbose_name='HistÃ³rico de AlteraÃ§Ãµes'),
        ),
        migrations.AlterField(
            model_name='controleprazos',
            name='notificar_emails',
            field=models.JSONField(blank=True, default=list, verbose_name='Emails para NotificaÃ§Ã£o'),
        ),
        migrations.AlterField(
            model_name='controleprazos',
            name='responsavel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ResponsÃ¡vel'),
        ),
        migrations.AlterField(
            model_name='cupomfiscalposto',
            name='numero_cupom',
            field=models.CharField(max_length=50, verbose_name='NÂº do Cupom'),
        ),
        migrations.AlterField(
            model_name='cupomfiscalposto',
            name='percentual_diferenca',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='DiferenÃ§a (%)'),
        ),
        migrations.AlterField(
            model_name='documentoprocesso',
            name='descricao',
            field=models.TextField(blank=True, verbose_name='DescriÃ§Ã£o'),
        ),
        migrations.AlterField(
            model_name='documentoprocesso',
            name='tipo',
            field=models.CharField(choices=[('defesa', 'Defesa'), ('recurso', 'Recurso'), ('parecer', 'Parecer TÃ©cnico'), ('decisao', 'DecisÃ£o'), ('outros', 'Outros')], max_length=20, verbose_name='Tipo do Documento'),
        ),
        migrations.AlterField(
            model_name='documentoprocesso',
            name='titulo',
            field=models.CharField(max_length=255, verbose_name='TÃ\xadtulo'),
        ),
        migrations.AlterField(
            model_name='documentoprocesso',
            name='usuario_upload',
            field=models.CharField(blank=True, max_length=255, verbose_name='UsuÃ¡rio'),
        ),
        migrations.AlterField(
            model_name='evidenciafiscalizacao',
            name='descricao',
            field=models.TextField(blank=True, verbose_name='DescriÃ§Ã£o'),
        ),
        migrations.AlterField(
            model_name='evidenciafiscalizacao',
            name='tipo',
            field=models.CharField(choices=[('FOTO', 'Foto'), ('VIDEO', 'VÃ\xaddeo'), ('DOCUMENTO', 'Documento'), ('AUDIO', 'Ã\x81udio'), ('OUTROS', 'Outros')], max_length=20, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='evidenciafiscalizacao',
            name='titulo',
            field=models.CharField(max_length=200, verbose_name='TÃ\xadtulo'),
        ),
        migrations.AlterField(
            model_name='evidenciafotografica',
            name='descricao',
            field=models.TextField(verbose_name='DescriÃ§Ã£o da EvidÃªncia'),
        ),
        migrations.AlterField(
            model_name='evidenciafotografica',
            name='fiscal_upload',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Fiscal ResponsÃ¡vel'),
        ),
        migrations.AlterField(
            model_name='evidenciafotografica',
            name='tipo_evidencia',
            field=models.CharField(choices=[('irregularidade', 'Irregularidade'), ('documento', 'Documento'), ('ambiente', 'Ambiente'), ('produto', 'Produto'), ('outros', 'Outros')], max_length=20, verbose_name='Tipo de EvidÃªncia'),
        ),
        migrations.AlterField(
            model_name='historicoautoinfracao',
            name='acao',
            field=models.CharField(max_length=100, verbose_name='AÃ§Ã£o'),
        ),
        migrations.AlterField(
            model_name='historicoautoinfracao',
            name='data_acao',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data da AÃ§Ã£o'),
        ),
        migrations.AlterField(
            model_name='historicoautoinfracao',
            name='descricao',
            field=models.TextField(verbose_name='DescriÃ§Ã£o'),
        ),
        migrations.AlterField(
            model_name='historicoprocesso',
            name='data_mudanca',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data da MudanÃ§a'),
        ),
        migrations.AlterField(
            model_name='historicoprocesso',
            name='observacao',
            field=models.TextField(blank=True, verbose_name='ObservaÃ§Ã£o'),
        ),
        migrations.AlterField(
            model_name='historicoprocesso',
            name='usuario',
            field=models.CharField(blank=True, help_text='UsuÃ¡rio que fez a alteraÃ§Ã£o', max_length=255, verbose_name='UsuÃ¡rio'),
        ),
        migrations.AlterField(
            model_name='historicostatusinfracao',
            name='data_mudanca',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data da MudanÃ§a'),
        ),
        migrations.AlterField(
            model_name='historicostatusinfracao',
            name='observacoes',
            field=models.TextField(blank=True, verbose_name='ObservaÃ§Ãµes'),
        ),
        migrations.AlterField(
            model_name='historicostatusinfracao',
            name='usuario',
            field=models.CharField(blank=True, max_length=255, verbose_name='UsuÃ¡rio'),
        ),
        migrations.AlterField(
            model_name='itemapreensaoinutilizacao',
            name='especificacao',
            field=models.TextField(verbose_name='EspecificaÃ§Ã£o'),
        ),
        migrations.AlterField(
            model_name='itemapreensaoinutilizacao',
            name='motivo_apreensao',
            field=models.TextField(verbose_name='Motivo da ApreensÃ£o/InutilizaÃ§Ã£o'),
        ),
        migrations.AlterField(
            model_name='itemapreensaoinutilizacao',
            name='valor_unitario',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor UnitÃ¡rio'),
        ),
        migrations.AlterField(
            model_name='notafiscalposto',
            name='numero_nota',
            field=models.CharField(max_length=50, verbose_name='NÃºmero da Nota Fiscal'),
        ),
        migrations.AlterField(
            model_name='notafiscalposto',
            name='preco',
            field=models.DecimalField(decimal_places=3, max_digits=6, verbose_name='PreÃ§o por Litro'),
        ),
        migrations.AlterField(
            model_name='notafiscalposto',
            name='tipo_nota',
            field=models.CharField(choices=[('aumento', 'Ã\x9altimo Aumento'), ('anterior', 'Anteriores')], max_length=10, verbose_name='Tipo da Nota'),
        ),
        migrations.AlterField(
            model_name='notificacaoeletronica',
            name='destinatario_cpf_cnpj',
            field=models.CharField(blank=True, max_length=18, null=True, verbose_name='CPF/CNPJ do DestinatÃ¡rio'),
        ),
        migrations.AlterField(
            model_name='notificacaoeletronica',
            name='destinatario_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email do DestinatÃ¡rio'),
        ),
        migrations.AlterField(
            model_name='notificacaoeletronica',
            name='destinatario_nome',
            field=models.CharField(max_length=255, verbose_name='Nome do DestinatÃ¡rio'),
        ),
        migrations.AlterField(
            model_name='notificacaoeletronica',
            name='max_tentativas',
            field=models.IntegerField(default=3, verbose_name='MÃ¡ximo de Tentativas'),
        ),
        migrations.AlterField(
            model_name='notificacaoeletronica',
            name='proxima_tentativa',
            field=models.DateTimeField(blank=True, null=True, verbose_name='PrÃ³xima Tentativa'),
        ),
        migrations.AlterField(
            model_name='notificacaoeletronica',
            name='tipo_notificacao',
            field=models.CharField(choices=[('auto_infracao', 'Auto de InfraÃ§Ã£o'), ('prazo_vencendo', 'Prazo Vencendo'), ('prazo_vencido', 'Prazo Vencido'), ('defesa_apresentada', 'Defesa Apresentada'), ('recurso_apresentado', 'Recurso Apresentado'), ('decisao_proferida', 'DecisÃ£o Proferida')], max_length=20, verbose_name='Tipo de NotificaÃ§Ã£o'),
        ),
        migrations.AlterField(
            model_name='processo',
            name='analista_responsavel',
            field=models.CharField(blank=True, help_text='Analista responsÃ¡vel pela anÃ¡lise do processo', max_length=255, verbose_name='Analista ResponsÃ¡vel'),
        ),
        migrations.AlterField(
            model_name='processo',
            name='auto_infracao',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='processo', to='fiscalizacao.autoinfracao', verbose_name='Auto de InfraÃ§Ã£o'),
        ),
        migrations.AlterField(
            model_name='processo',
            name='autuado',
            field=models.CharField(help_text='RazÃ£o social da empresa autuada', max_length=255, verbose_name='Autuado (RazÃ£o Social)'),
        ),
        migrations.AlterField(
            model_name='processo',
            name='data_finalizacao',
            field=models.DateField(blank=True, null=True, verbose_name='Data de FinalizaÃ§Ã£o'),
        ),
        migrations.AlterField(
            model_name='processo',
            name='data_notificacao',
            field=models.DateField(blank=True, null=True, verbose_name='Data de NotificaÃ§Ã£o'),
        ),
        migrations.AlterField(
            model_name='processo',
            name='fiscal_responsavel',
            field=models.CharField(blank=True, help_text='Fiscal que conduziu a fiscalizaÃ§Ã£o', max_length=255, verbose_name='Fiscal ResponsÃ¡vel'),
        ),
        migrations.AlterField(
            model_name='processo',
            name='numero_processo',
            field=models.CharField(blank=True, help_text='Gerado automaticamente no formato PROC-00001/2025', max_length=25, unique=True, verbose_name='NÃºmero do Processo'),
        ),
        migrations.AlterField(
            model_name='processo',
            name='observacoes',
            field=models.TextField(blank=True, help_text='ObservaÃ§Ãµes gerais sobre o processo', verbose_name='ObservaÃ§Ãµes'),
        ),
        migrations.AlterField(
            model_name='processo',
            name='observacoes_internas',
            field=models.TextField(blank=True, help_text='ObservaÃ§Ãµes internas nÃ£o incluÃ\xaddas nos documentos', verbose_name='ObservaÃ§Ãµes Internas'),
        ),
        migrations.AlterField(
            model_name='processo',
            name='prazo_defesa',
            field=models.DateField(blank=True, help_text='Data limite para apresentaÃ§Ã£o da defesa', null=True, verbose_name='Prazo para Defesa'),
        ),
        migrations.AlterField(
            model_name='processo',
            name='prazo_recurso',
            field=models.DateField(blank=True, help_text='Data limite para apresentaÃ§Ã£o do recurso', null=True, verbose_name='Prazo para Recurso'),
        ),
        migrations.AlterField(
            model_name='processo',
            name='status',
            field=models.CharField(choices=[('aguardando_defesa', 'Aguardando Defesa'), ('defesa_apresentada', 'Defesa Apresentada'), ('em_analise', 'Em AnÃ¡lise'), ('aguardando_recurso', 'Aguardando Recurso'), ('recurso_apresentado', 'Recurso Apresentado'), ('julgamento', 'Em Julgamento'), ('finalizado_procedente', 'Finalizado - Procedente'), ('finalizado_improcedente', 'Finalizado - Improcedente'), ('arquivado', 'Arquivado'), ('prescrito', 'Prescrito')], default='aguardando_defesa', max_length=50, verbose_name='Status do Processo'),
        ),
        migrations.AlterField(
            model_name='processo',
            name='valor_final',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Valor apÃ³s recursos e decisÃ£o final', max_digits=10, null=True, verbose_name='Valor Final (R$)'),
        ),
        migrations.AlterField(
            model_name='sequenciaautos',
            name='ultimo_numero',
            field=models.IntegerField(default=0, verbose_name='Ã\x9altimo NÃºmero Gerado'),
        ),
        migrations.AlterField(
            model_name='sequenciaautosapreensao',
            name='ultimo_numero',
            field=models.IntegerField(default=0, verbose_name='Ã\x9altimo NÃºmero Gerado'),
        ),
        migrations.AlterField(
            model_name='templateautoinfracao',
            name='base_legal_padrao',
            field=models.TextField(blank=True, verbose_name='Base Legal PadrÃ£o'),
        ),
        migrations.AlterField(
            model_name='templateautoinfracao',
            name='campos_obrigatorios',
            field=models.JSONField(default=list, verbose_name='Campos ObrigatÃ³rios'),
        ),
        migrations.AlterField(
            model_name='templateautoinfracao',
            name='configuracao',
            field=models.JSONField(default=dict, verbose_name='ConfiguraÃ§Ã£o'),
        ),
        migrations.AlterField(
            model_name='templateautoinfracao',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data de CriaÃ§Ã£o'),
        ),
        migrations.AlterField(
            model_name='templateautoinfracao',
            name='descricao',
            field=models.TextField(blank=True, verbose_name='DescriÃ§Ã£o'),
        ),
        migrations.AlterField(
            model_name='templateautoinfracao',
            name='fundamentacao_padrao',
            field=models.TextField(blank=True, verbose_name='FundamentaÃ§Ã£o PadrÃ£o'),
        ),
        migrations.AlterField(
            model_name='templateautoinfracao',
            name='padrao',
            field=models.BooleanField(default=False, verbose_name='Template PadrÃ£o'),
        ),
        migrations.AlterField(
            model_name='templateautoinfracao',
            name='prazo_defesa_padrao',
            field=models.IntegerField(default=30, verbose_name='Prazo para Defesa PadrÃ£o (dias)'),
        ),
        migrations.AlterField(
            model_name='templateautoinfracao',
            name='prazo_pagamento_padrao',
            field=models.IntegerField(default=30, verbose_name='Prazo para Pagamento PadrÃ£o (dias)'),
        ),
        migrations.AlterField(
            model_name='templateautoinfracao',
            name='valor_multa_padrao',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Valor da Multa PadrÃ£o'),
        ),
        migrations.AlterField(
            model_name='tipofiscalizacao',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data de CriaÃ§Ã£o'),
        ),
        migrations.AlterField(
            model_name='tipofiscalizacao',
            name='descricao',
            field=models.TextField(blank=True, verbose_name='DescriÃ§Ã£o'),
        ),
        migrations.AlterField(
            model_name='tipofiscalizacao',
            name='tipo',
            field=models.CharField(choices=[('PRESENCIAL', 'FiscalizaÃ§Ã£o Presencial'), ('REMOTA', 'FiscalizaÃ§Ã£o Remota'), ('DENUNCIA', 'DenÃºncia'), ('ACAO_PREVENTIVA', 'AÃ§Ã£o Preventiva'), ('FORCA_TAREFA', 'ForÃ§a Tarefa'), ('MONITORAMENTO', 'Monitoramento'), ('AUDITORIA', 'Auditoria')], max_length=20, verbose_name='Tipo'),
        ),
        migrations.AddIndex(
            model_name='autoapreensaoinutilizacao',
            index=models.Index(fields=['numero_documento'], name='fiscalizaca_numero__696b52_idx'),
        ),
        migrations.AddIndex(
            model_name='autoapreensaoinutilizacao',
            index=models.Index(fields=['uuid_local'], name='fiscalizaca_uuid_lo_02262b_idx'),
        ),
        migrations.AddIndex(
            model_name='autoapreensaoinutilizacao',
            index=models.Index(fields=['criado_no_mobile'], name='fiscalizaca_criado__4eb58c_idx'),
        ),
        migrations.AddIndex(
            model_name='autoapreensaoinutilizacao',
            index=models.Index(fields=['data_fiscalizacao'], name='fiscalizaca_data_fi_cccad3_idx'),
        ),
        migrations.AddIndex(
            model_name='autoinfracao',
            index=models.Index(fields=['uuid_local'], name='fiscalizaca_uuid_lo_15a1c2_idx'),
        ),
        migrations.AddIndex(
            model_name='autoinfracao',
            index=models.Index(fields=['criado_no_mobile'], name='fiscalizaca_criado__27e4fe_idx'),
        ),
        migrations.AddField(
            model_name='mobiledevicetoken',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mobile_device_tokens', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mobileupload',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mobile_uploads', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pedidonotificacaomobile',
            name='atualizado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos_notificacao_mobile_atualizados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pedidonotificacaomobile',
            name='auto_constatacao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos_notificacao_mobile', to='fiscalizacao.autosupermercado'),
        ),
        migrations.AddField(
            model_name='pedidonotificacaomobile',
            name='auto_infracao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos_notificacao_mobile', to='fiscalizacao.autoinfracao'),
        ),
        migrations.AddField(
            model_name='pedidonotificacaomobile',
            name='solicitado_por',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos_notificacao_mobile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='mobiledevicetoken',
            index=models.Index(fields=['usuario', 'ativo'], name='fiscalizaca_usuario_de267e_idx'),
        ),
        migrations.AddIndex(
            model_name='mobiledevicetoken',
            index=models.Index(fields=['device_id'], name='fiscalizaca_device__27bb34_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='mobiledevicetoken',
            unique_together={('usuario', 'device_id')},
        ),
        migrations.AddIndex(
            model_name='mobileupload',
            index=models.Index(fields=['usuario'], name='fiscalizaca_usuario_fab199_idx'),
        ),
        migrations.AddIndex(
            model_name='mobileupload',
            index=models.Index(fields=['token'], name='fiscalizaca_token_94122d_idx'),
        ),
        migrations.AddIndex(
            model_name='pedidonotificacaomobile',
            index=models.Index(fields=['status'], name='fiscalizaca_status_1455f6_idx'),
        ),
        migrations.AddIndex(
            model_name='pedidonotificacaomobile',
            index=models.Index(fields=['uuid_local'], name='fiscalizaca_uuid_lo_d537a3_idx'),
        ),
        migrations.AddIndex(
            model_name='pedidonotificacaomobile',
            index=models.Index(fields=['criado_no_mobile'], name='fiscalizaca_criado__4dc065_idx'),
        ),
    ]
