# Generated by Django 4.2.11 on 2025-08-26 01:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fiscalizacao', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoFiscalizacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('tipo', models.CharField(choices=[('PRESENCIAL', 'Fiscalização Presencial'), ('REMOTA', 'Fiscalização Remota'), ('DENUNCIA', 'Denúncia'), ('ACAO_PREVENTIVA', 'Ação Preventiva'), ('FORCA_TAREFA', 'Força Tarefa'), ('MONITORAMENTO', 'Monitoramento'), ('AUDITORIA', 'Auditoria')], max_length=20, verbose_name='Tipo')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
            ],
            options={
                'verbose_name': 'Tipo de Fiscalização',
                'verbose_name_plural': 'Tipos de Fiscalização',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='TemplateAutoInfracao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('configuracao', models.JSONField(default=dict, verbose_name='Configuração')),
                ('campos_obrigatorios', models.JSONField(default=list, verbose_name='Campos Obrigatórios')),
                ('campos_opcionais', models.JSONField(default=list, verbose_name='Campos Opcionais')),
                ('base_legal_padrao', models.TextField(blank=True, verbose_name='Base Legal Padrão')),
                ('fundamentacao_padrao', models.TextField(blank=True, verbose_name='Fundamentação Padrão')),
                ('valor_multa_padrao', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Valor da Multa Padrão')),
                ('prazo_defesa_padrao', models.IntegerField(default=30, verbose_name='Prazo para Defesa Padrão (dias)')),
                ('prazo_pagamento_padrao', models.IntegerField(default=30, verbose_name='Prazo para Pagamento Padrão (dias)')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('padrao', models.BooleanField(default=False, verbose_name='Template Padrão')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('criado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='templates_fiscalizacao_criados', to=settings.AUTH_USER_MODEL)),
                ('tipo_fiscalizacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='templates', to='fiscalizacao.tipofiscalizacao')),
            ],
            options={
                'verbose_name': 'Template de Auto de Infração',
                'verbose_name_plural': 'Templates de Autos de Infração',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='NotificacaoEletronica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('EMAIL', 'Email'), ('SMS', 'SMS'), ('PUSH', 'Push Notification'), ('WHATSAPP', 'WhatsApp')], max_length=20, verbose_name='Tipo')),
                ('destinatario', models.CharField(max_length=255, verbose_name='Destinatário')),
                ('assunto', models.CharField(max_length=200, verbose_name='Assunto')),
                ('mensagem', models.TextField(verbose_name='Mensagem')),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('ENVIADA', 'Enviada'), ('ENTREGUE', 'Entregue'), ('ERRO', 'Erro'), ('CANCELADA', 'Cancelada')], default='PENDENTE', max_length=20, verbose_name='Status')),
                ('protocolo', models.CharField(blank=True, max_length=100, verbose_name='Protocolo')),
                ('data_envio', models.DateTimeField(blank=True, null=True, verbose_name='Data de Envio')),
                ('data_entrega', models.DateTimeField(blank=True, null=True, verbose_name='Data de Entrega')),
                ('tentativas', models.IntegerField(default=0, verbose_name='Tentativas')),
                ('erro_mensagem', models.TextField(blank=True, verbose_name='Mensagem de Erro')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('auto_infracao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificacoes', to='fiscalizacao.autoinfracao')),
                ('enviado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notificacoes_fiscalizacao_enviadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notificação Eletrônica',
                'verbose_name_plural': 'Notificações Eletrônicas',
                'ordering': ['-data_criacao'],
            },
        ),
        migrations.CreateModel(
            name='HistoricoAutoInfracao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acao', models.CharField(max_length=100, verbose_name='Ação')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('dados_anteriores', models.JSONField(blank=True, null=True, verbose_name='Dados Anteriores')),
                ('dados_novos', models.JSONField(blank=True, null=True, verbose_name='Dados Novos')),
                ('data_acao', models.DateTimeField(auto_now_add=True, verbose_name='Data da Ação')),
                ('ip_origem', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP de Origem')),
                ('auto_infracao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico', to='fiscalizacao.autoinfracao')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historico_autos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Histórico de Auto de Infração',
                'verbose_name_plural': 'Histórico de Autos de Infração',
                'ordering': ['-data_acao'],
            },
        ),
        migrations.CreateModel(
            name='EvidenciaFiscalizacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('FOTO', 'Foto'), ('VIDEO', 'Vídeo'), ('DOCUMENTO', 'Documento'), ('AUDIO', 'Áudio'), ('OUTROS', 'Outros')], max_length=20, verbose_name='Tipo')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('arquivo', models.FileField(upload_to='evidencias_fiscalizacao/', verbose_name='Arquivo')),
                ('nome_arquivo', models.CharField(blank=True, max_length=255, verbose_name='Nome do Arquivo')),
                ('tamanho_arquivo', models.IntegerField(blank=True, null=True, verbose_name='Tamanho (bytes)')),
                ('data_upload', models.DateTimeField(auto_now_add=True, verbose_name='Data de Upload')),
                ('auto_infracao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidencias', to='fiscalizacao.autoinfracao')),
                ('upload_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evidencias_upload', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Evidência de Fiscalização',
                'verbose_name_plural': 'Evidências de Fiscalização',
                'ordering': ['-data_upload'],
            },
        ),
        migrations.CreateModel(
            name='ConfiguracaoFiscalizacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_evidencias_por_auto', models.IntegerField(default=10, verbose_name='Máximo de Evidências por Auto')),
                ('max_tamanho_arquivo', models.IntegerField(default=50, verbose_name='Máximo Tamanho de Arquivo (MB)')),
                ('tipos_arquivo_permitidos', models.JSONField(default=list, verbose_name='Tipos de Arquivo Permitidos')),
                ('notificar_prazos', models.BooleanField(default=True, verbose_name='Notificar Prazos')),
                ('dias_antecedencia_prazo', models.IntegerField(default=5, verbose_name='Dias de Antecedência para Prazo')),
                ('notificar_atrasos', models.BooleanField(default=True, verbose_name='Notificar Atrasos')),
                ('assinatura_digital_obrigatoria', models.BooleanField(default=False, verbose_name='Assinatura Digital Obrigatória')),
                ('certificado_padrao', models.CharField(blank=True, max_length=255, verbose_name='Certificado Padrão')),
                ('workflow_automatico', models.BooleanField(default=True, verbose_name='Workflow Automático')),
                ('aprovacao_obrigatoria', models.BooleanField(default=True, verbose_name='Aprovação Obrigatória')),
                ('data_configuracao', models.DateTimeField(auto_now=True, verbose_name='Data de Configuração')),
                ('configurado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='configuracoes_fiscalizacao', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Configuração de Fiscalização',
                'verbose_name_plural': 'Configurações de Fiscalização',
            },
        ),
        migrations.CreateModel(
            name='AutoInfracaoAvancado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gerado_automaticamente', models.BooleanField(default=False, verbose_name='Gerado Automaticamente')),
                ('template_utilizado', models.CharField(blank=True, max_length=100, verbose_name='Template Utilizado')),
                ('data_geracao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Geração')),
                ('assinatura_digital', models.BooleanField(default=False, verbose_name='Assinatura Digital')),
                ('certificado_assinatura', models.CharField(blank=True, max_length=255, verbose_name='Certificado de Assinatura')),
                ('data_assinatura', models.DateTimeField(blank=True, null=True, verbose_name='Data de Assinatura')),
                ('notificacao_eletronica', models.BooleanField(default=False, verbose_name='Notificação Eletrônica')),
                ('email_notificacao', models.EmailField(blank=True, max_length=254, verbose_name='Email de Notificação')),
                ('data_notificacao', models.DateTimeField(blank=True, null=True, verbose_name='Data de Notificação')),
                ('protocolo_notificacao', models.CharField(blank=True, max_length=100, verbose_name='Protocolo de Notificação')),
                ('prazo_defesa', models.IntegerField(default=30, verbose_name='Prazo para Defesa (dias)')),
                ('data_limite_defesa', models.DateField(blank=True, null=True, verbose_name='Data Limite para Defesa')),
                ('prazo_pagamento', models.IntegerField(default=30, verbose_name='Prazo para Pagamento (dias)')),
                ('data_limite_pagamento', models.DateField(blank=True, null=True, verbose_name='Data Limite para Pagamento')),
                ('status_workflow', models.CharField(choices=[('RASCUNHO', 'Rascunho'), ('EM_ANALISE', 'Em Análise'), ('APROVADO', 'Aprovado'), ('ASSINADO', 'Assinado'), ('NOTIFICADO', 'Notificado'), ('EM_DEFESA', 'Em Defesa'), ('JULGADO', 'Julgado'), ('PAGO', 'Pago'), ('CANCELADO', 'Cancelado')], default='RASCUNHO', max_length=20, verbose_name='Status do Workflow')),
                ('versao_documento', models.CharField(default='1.0', max_length=20, verbose_name='Versão do Documento')),
                ('hash_documento', models.CharField(blank=True, max_length=64, verbose_name='Hash do Documento')),
                ('data_modificacao', models.DateTimeField(auto_now=True, verbose_name='Data de Modificação')),
                ('assinado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='autos_assinados', to=settings.AUTH_USER_MODEL)),
                ('auto_infracao', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='avancado', to='fiscalizacao.autoinfracao')),
                ('gerado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='autos_gerados', to=settings.AUTH_USER_MODEL)),
                ('modificado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='autos_modificados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Auto de Infração Avançado',
                'verbose_name_plural': 'Autos de Infração Avançados',
                'ordering': ['-data_modificacao'],
            },
        ),
    ]
