# Generated by Django 5.2.1 on 2025-08-28 14:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiscalizacao', '0002_tipofiscalizacao_templateautoinfracao_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='autosupermercado',
            name='cominacao_legal',
            field=models.TextField(blank=True, verbose_name='Cominação Legal'),
        ),
        migrations.AddField(
            model_name='autosupermercado',
            name='instrucoes_fiscalizado',
            field=models.TextField(blank=True, verbose_name='Instruções ao Fiscalizado'),
        ),
        migrations.AddField(
            model_name='autosupermercado',
            name='justificativa_pericia',
            field=models.TextField(blank=True, verbose_name='Justificativa da Perícia'),
        ),
        migrations.AlterField(
            model_name='autosupermercado',
            name='prazo_cumprimento_dias',
            field=models.IntegerField(default=5, verbose_name='Prazo para Cumprimento (dias)'),
        ),
        migrations.CreateModel(
            name='AutoApreensaoInutilizacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_documento', models.CharField(choices=[('apreensao', 'Auto de Apreensão'), ('inutilizacao', 'Inutilização')], default='apreensao', max_length=20)),
                ('numero_documento', models.CharField(blank=True, max_length=20)),
                ('ano_documento', models.IntegerField(default=2025)),
                ('razao_social', models.CharField(max_length=200, verbose_name='Razão Social')),
                ('nome_fantasia', models.CharField(max_length=200, verbose_name='Nome Fantasia')),
                ('atividade', models.CharField(max_length=200, verbose_name='Atividade')),
                ('endereco', models.TextField(verbose_name='Endereço')),
                ('cep', models.CharField(max_length=10, verbose_name='CEP')),
                ('municipio', models.CharField(max_length=100, verbose_name='Município')),
                ('estado', models.CharField(default='AM', max_length=2, verbose_name='Estado')),
                ('cnpj', models.CharField(max_length=18, verbose_name='CNPJ')),
                ('telefone', models.CharField(max_length=20, verbose_name='Telefone')),
                ('cominacao_legal', models.TextField(verbose_name='Cominação Legal')),
                ('auto_constatacao_numero', models.CharField(max_length=20, verbose_name='Auto de Constatação Nº')),
                ('itens', models.JSONField(default=list, verbose_name='Lista de Itens')),
                ('necessita_pericia', models.BooleanField(default=False, verbose_name='Necessita Perícia')),
                ('justificativa_pericia', models.TextField(blank=True, verbose_name='Justificativa')),
                ('local', models.CharField(max_length=200, verbose_name='Local')),
                ('data_fiscalizacao', models.DateField(verbose_name='Data')),
                ('hora_inicio', models.TimeField(verbose_name='Hora do Início')),
                ('hora_termino', models.TimeField(verbose_name='Hora do Término')),
                ('fiscal_1', models.CharField(max_length=100, verbose_name='Fiscal 1')),
                ('fiscal_2', models.CharField(max_length=100, verbose_name='Fiscal 2')),
                ('responsavel_estabelecimento', models.CharField(max_length=100, verbose_name='Nome do Responsável')),
                ('cpf_responsavel', models.CharField(max_length=14, verbose_name='CPF do Responsável')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Auto de Apreensão/Inutilização',
                'verbose_name_plural': 'Autos de Apreensão/Inutilização',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ItemApreensaoInutilizacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=100, verbose_name='Item')),
                ('quantidade', models.IntegerField(verbose_name='Quantidade')),
                ('unidade', models.CharField(max_length=20, verbose_name='Unidade')),
                ('especificacao', models.TextField(verbose_name='Especificação')),
                ('valor_unitario', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Unitário')),
                ('motivo_apreensao', models.TextField(verbose_name='Motivo da Apreensão/Inutilização')),
                ('auto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens_detalhados', to='fiscalizacao.autoapreensaoinutilizacao')),
            ],
            options={
                'verbose_name': 'Item Apreendido/Inutilizado',
                'verbose_name_plural': 'Itens Apreendidos/Inutilizados',
            },
        ),
    ]
