# Generated by Django 4.2.11 on 2025-10-23 18:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fiscalizacao', '0002_mobiledevicetoken_mobileupload_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='autoapreensaoinutilizacao',
            options={'ordering': ['-created_at'], 'verbose_name': 'Auto de Apreensão/Inutilização', 'verbose_name_plural': 'Autos de Apreensão/Inutilização'},
        ),
        migrations.AlterModelOptions(
            name='autoinfracao',
            options={'ordering': ['-data_fiscalizacao', '-numero'], 'verbose_name': 'Auto de Infração', 'verbose_name_plural': 'Autos de Infração'},
        ),
        migrations.AlterModelOptions(
            name='autoinfracaoavancado',
            options={'ordering': ['-data_modificacao'], 'verbose_name': 'Auto de Infração Avançado', 'verbose_name_plural': 'Autos de Infração Avançados'},
        ),
        migrations.AlterModelOptions(
            name='configuracaofiscalizacao',
            options={'verbose_name': 'Configuração de Fiscalização', 'verbose_name_plural': 'Configurações de Fiscalização'},
        ),
        migrations.AlterModelOptions(
            name='evidenciafiscalizacao',
            options={'ordering': ['-data_upload'], 'verbose_name': 'Evidência de Fiscalização', 'verbose_name_plural': 'Evidências de Fiscalização'},
        ),
        migrations.AlterModelOptions(
            name='evidenciafotografica',
            options={'ordering': ['-data_upload'], 'verbose_name': 'Evidência Fotográfica', 'verbose_name_plural': 'Evidências Fotográficas'},
        ),
        migrations.AlterModelOptions(
            name='historicoautoinfracao',
            options={'ordering': ['-data_acao'], 'verbose_name': 'Histórico de Auto de Infração', 'verbose_name_plural': 'Histórico de Autos de Infração'},
        ),
        migrations.AlterModelOptions(
            name='historicoprocesso',
            options={'ordering': ['-data_mudanca'], 'verbose_name': 'Histórico do Processo', 'verbose_name_plural': 'Históricos dos Processos'},
        ),
        migrations.AlterModelOptions(
            name='historicostatusinfracao',
            options={'ordering': ['-data_mudanca'], 'verbose_name': 'Histórico de Status', 'verbose_name_plural': 'Históricos de Status'},
        ),
        migrations.AlterModelOptions(
            name='notificacaoeletronica',
            options={'ordering': ['-data_envio'], 'verbose_name': 'Notificação Eletrônica', 'verbose_name_plural': 'Notificações Eletrônicas'},
        ),
        migrations.AlterModelOptions(
            name='pedidonotificacaomobile',
            options={'ordering': ['-criado_em'], 'verbose_name': 'Pedido de Notificacao Mobile', 'verbose_name_plural': 'Pedidos de Notificacao Mobile'},
        ),
        migrations.AlterModelOptions(
            name='sequenciaautos',
            options={'ordering': ['-ano'], 'verbose_name': 'Sequência de Auto', 'verbose_name_plural': 'Sequências de Autos'},
        ),
        migrations.AlterModelOptions(
            name='sequenciaautosapreensao',
            options={'ordering': ['-ano'], 'verbose_name': 'Sequência de Auto de Apreensão', 'verbose_name_plural': 'Sequências de Autos de Apreensão'},
        ),
        migrations.AlterModelOptions(
            name='templateautoinfracao',
            options={'ordering': ['nome'], 'verbose_name': 'Template de Auto de Infração', 'verbose_name_plural': 'Templates de Autos de Infração'},
        ),
        migrations.AlterModelOptions(
            name='tipofiscalizacao',
            options={'ordering': ['nome'], 'verbose_name': 'Tipo de Fiscalização', 'verbose_name_plural': 'Tipos de Fiscalização'},
        ),
        migrations.AlterField(
            model_name='anexoauto',
            name='descricao',
            field=models.CharField(blank=True, max_length=255, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='assinaturadigital',
            name='data_expiracao',
            field=models.DateTimeField(verbose_name='Data de Expiração'),
        ),
        migrations.AlterField(
            model_name='assinaturadigital',
            name='tipo_assinatura',
            field=models.CharField(choices=[('fiscal_1', 'Fiscal 1'), ('fiscal_2', 'Fiscal 2'), ('responsavel', 'Responsável'), ('testemunha', 'Testemunha')], max_length=20, verbose_name='Tipo de Assinatura'),
        ),
        migrations.AlterField(
            model_name='atendimentocaixabanco',
            name='horario_atendimento',
            field=models.TimeField(verbose_name='Horário de Atendimento'),
        ),
        migrations.AlterField(
            model_name='atendimentocaixabanco',
            name='horario_chegada',
            field=models.TimeField(verbose_name='Horário de Chegada'),
        ),
        migrations.AlterField(
            model_name='autoapreensaoinutilizacao',
            name='auto_constatacao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='autos_apreensao_inutilizacao', to='fiscalizacao.autosupermercado', verbose_name='Auto de Constatação'),
        ),
        migrations.AlterField(
            model_name='autoapreensaoinutilizacao',
            name='auto_constatacao_numero',
            field=models.CharField(max_length=20, verbose_name='Auto de Constatação Nº'),
        ),
        migrations.AlterField(
            model_name='autoapreensaoinutilizacao',
            name='cominacao_legal',
            field=models.TextField(verbose_name='Cominação Legal'),
        ),
        migrations.AlterField(
            model_name='autoapreensaoinutilizacao',
            name='cpf_responsavel',
            field=models.CharField(max_length=14, verbose_name='CPF do Responsável'),
        ),
        migrations.AlterField(
            model_name='autoapreensaoinutilizacao',
            name='endereco',
            field=models.TextField(verbose_name='Endereço'),
        ),
        migrations.AlterField(
            model_name='autoapreensaoinutilizacao',
            name='hora_inicio',
            field=models.TimeField(verbose_name='Hora do Início'),
        ),
        migrations.AlterField(
            model_name='autoapreensaoinutilizacao',
            name='hora_termino',
            field=models.TimeField(verbose_name='Hora do Término'),
        ),
        migrations.AlterField(
            model_name='autoapreensaoinutilizacao',
            name='municipio',
            field=models.CharField(max_length=100, verbose_name='Município'),
        ),
        migrations.AlterField(
            model_name='autoapreensaoinutilizacao',
            name='necessita_pericia',
            field=models.BooleanField(default=False, verbose_name='Necessita Perícia'),
        ),
        migrations.AlterField(
            model_name='autoapreensaoinutilizacao',
            name='razao_social',
            field=models.CharField(max_length=200, verbose_name='Razão Social'),
        ),
        migrations.AlterField(
            model_name='autoapreensaoinutilizacao',
            name='responsavel_estabelecimento',
            field=models.CharField(max_length=100, verbose_name='Nome do Responsável'),
        ),
        migrations.AlterField(
            model_name='autoapreensaoinutilizacao',
            name='tipo_documento',
            field=models.CharField(choices=[('apreensao', 'Auto de Apreensão'), ('inutilizacao', 'Inutilização')], default='apreensao', max_length=20),
        ),
        migrations.AlterField(
            model_name='autobanco',
            name='atuacao',
            field=models.CharField(blank=True, max_length=100, verbose_name='Atuação'),
        ),
        migrations.AlterField(
            model_name='autobanco',
            name='ausencia_cartaz_informativo',
            field=models.BooleanField(default=False, verbose_name='Ausência de Cartaz Informativo?'),
        ),
        migrations.AlterField(
            model_name='autobanco',
            name='ausencia_profissional_libras',
            field=models.BooleanField(default=False, verbose_name='Ausência de profissional de LIBRAS?'),
        ),
        migrations.AlterField(
            model_name='autobanco',
            name='data_fiscalizacao',
            field=models.DateField(verbose_name='Data da Fiscalização'),
        ),
        migrations.AlterField(
            model_name='autobanco',
            name='device_id',
            field=models.CharField(blank=True, help_text='Identificador enviado via cabecalho X-Device-Id', max_length=100, null=True, verbose_name='ID do dispositivo'),
        ),
        migrations.AlterField(
            model_name='autobanco',
            name='distribuiu_senha_fora_padrao',
            field=models.BooleanField(blank=True, null=True, verbose_name='Distribuiu senha fora do padrão?'),
        ),
        migrations.AlterField(
            model_name='autobanco',
            name='endereco',
            field=models.CharField(max_length=255, verbose_name='Endereço'),
        ),
        migrations.AlterField(
            model_name='autobanco',
            name='fiscal_nome_1',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome do 1º Fiscal'),
        ),
        migrations.AlterField(
            model_name='autobanco',
            name='fiscal_nome_2',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome do 2º Fiscal'),
        ),
        migrations.AlterField(
            model_name='autobanco',
            name='hora_fiscalizacao',
            field=models.TimeField(verbose_name='Hora da Fiscalização'),
        ),
        migrations.AlterField(
            model_name='autobanco',
            name='municipio',
            field=models.CharField(max_length=100, verbose_name='Município'),
        ),
        migrations.AlterField(
            model_name='autobanco',
            name='numero',
            field=models.CharField(blank=True, max_length=20, unique=True, verbose_name='Número do Auto'),
        ),
        migrations.AlterField(
            model_name='autobanco',
            name='observacoes',
            field=models.TextField(blank=True, verbose_name='Observações'),
        ),
        migrations.AlterField(
            model_name='autobanco',
            name='origem',
            field=models.CharField(choices=[('acao', 'Ação Fiscalizatória'), ('denuncia', 'Denúncia'), ('forca_tarefa', 'Força Tarefa'), ('outros', 'Outros')], default='acao', max_length=20, verbose_name='Origem'),
        ),
        migrations.AlterField(
            model_name='autobanco',
            name='porte',
            field=models.CharField(blank=True, choices=[('microempresa', 'Microempresa'), ('pequeno', 'Pequeno Porte'), ('medio', 'Médio Porte'), ('grande', 'Grande Porte')], max_length=100, verbose_name='Porte'),
        ),
        migrations.AlterField(
            model_name='autobanco',
            name='razao_social',
            field=models.CharField(max_length=255, verbose_name='Razão Social'),
        ),
        migrations.AlterField(
            model_name='autobanco',
            name='responsavel_cpf',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='CPF/RG do Responsável'),
        ),
        migrations.AlterField(
            model_name='autobanco',
            name='responsavel_nome',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome do Responsável'),
        ),
        migrations.AlterField(
            model_name='autobanco',
            name='sem_irregularidades',
            field=models.BooleanField(default=False, verbose_name='Não foram encontradas irregularidades'),
        ),
        migrations.AlterField(
            model_name='autobanco',
            name='senha_sem_horarios',
            field=models.BooleanField(default=False, verbose_name='Senha sem horários?'),
        ),
        migrations.AlterField(
            model_name='autobanco',
            name='sincronizado_em',
            field=models.DateTimeField(blank=True, help_text='Momento em que os dados chegaram ao backend', null=True, verbose_name='Primeira sincronizacao'),
        ),
        migrations.AlterField(
            model_name='autobanco',
            name='uuid_local',
            field=models.UUIDField(blank=True, help_text='Identificador gerado no mobile para conciliacao offline', null=True, unique=True, verbose_name='UUID local'),
        ),
        migrations.AlterField(
            model_name='autodiversos',
            name='advertencia',
            field=models.BooleanField(default=False, verbose_name='Houve Advertência?'),
        ),
        migrations.AlterField(
            model_name='autodiversos',
            name='afixacao_precos_eletronico_fora_padrao',
            field=models.BooleanField(default=False, verbose_name='Afixação de preços no comércio eletrônico fora do padrão'),
        ),
        migrations.AlterField(
            model_name='autodiversos',
            name='afixacao_precos_fora_padrao',
            field=models.BooleanField(default=False, verbose_name='Afixação de preços fora do padrão'),
        ),
        migrations.AlterField(
            model_name='autodiversos',
            name='afixacao_precos_fracionados_fora_padrao',
            field=models.BooleanField(default=False, verbose_name='Afixação de preços na venda a varejo de produtos fracionados fora do padrão'),
        ),
        migrations.AlterField(
            model_name='autodiversos',
            name='atuacao',
            field=models.CharField(blank=True, max_length=100, verbose_name='Atuação'),
        ),
        migrations.AlterField(
            model_name='autodiversos',
            name='ausencia_afixacao_precos',
            field=models.BooleanField(default=False, verbose_name='Ausência de afixação de preços'),
        ),
        migrations.AlterField(
            model_name='autodiversos',
            name='ausencia_afixacao_precos_eletronico',
            field=models.BooleanField(default=False, verbose_name='Ausência de afixação de preços no comércio eletrônico'),
        ),
        migrations.AlterField(
            model_name='autodiversos',
            name='ausencia_exemplar_cdc',
            field=models.BooleanField(default=False, verbose_name='Ausência do exemplar do CDC em local visível'),
        ),
        migrations.AlterField(
            model_name='autodiversos',
            name='ausencia_visibilidade_descontos',
            field=models.BooleanField(default=False, verbose_name='Ausência de visibilidade de descontos'),
        ),
        migrations.AlterField(
            model_name='autodiversos',
            name='data_fiscalizacao',
            field=models.DateField(verbose_name='Data da Fiscalização'),
        ),
        migrations.AlterField(
            model_name='autodiversos',
            name='device_id',
            field=models.CharField(blank=True, help_text='Identificador enviado via cabecalho X-Device-Id', max_length=100, null=True, verbose_name='ID do dispositivo'),
        ),
        migrations.AlterField(
            model_name='autodiversos',
            name='endereco',
            field=models.CharField(max_length=255, verbose_name='Endereço'),
        ),
        migrations.AlterField(
            model_name='autodiversos',
            name='fiscal_nome_1',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome do 1º Fiscal'),
        ),
        migrations.AlterField(
            model_name='autodiversos',
            name='fiscal_nome_2',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome do 2º Fiscal'),
        ),
        migrations.AlterField(
            model_name='autodiversos',
            name='hora_fiscalizacao',
            field=models.TimeField(verbose_name='Hora da Fiscalização'),
        ),
        migrations.AlterField(
            model_name='autodiversos',
            name='municipio',
            field=models.CharField(max_length=100, verbose_name='Município'),
        ),
        migrations.AlterField(
            model_name='autodiversos',
            name='numero',
            field=models.CharField(blank=True, max_length=20, unique=True, verbose_name='Número do Auto'),
        ),
        migrations.AlterField(
            model_name='autodiversos',
            name='origem',
            field=models.CharField(choices=[('acao', 'Ação Fiscalizatória'), ('denuncia', 'Denúncia'), ('forca_tarefa', 'Força Tarefa'), ('outros', 'Outros')], default='acao', max_length=20, verbose_name='Origem'),
        ),
        migrations.AlterField(
            model_name='autodiversos',
            name='outras_irregularidades',
            field=models.TextField(blank=True, verbose_name='Outras Irregularidades Constatadas/Outras Cominações Legais'),
        ),
        migrations.AlterField(
            model_name='autodiversos',
            name='porte',
            field=models.CharField(blank=True, choices=[('microempresa', 'Microempresa'), ('pequeno', 'Pequeno Porte'), ('medio', 'Médio Porte'), ('grande', 'Grande Porte')], max_length=100, verbose_name='Porte'),
        ),
        migrations.AlterField(
            model_name='autodiversos',
            name='razao_social',
            field=models.CharField(max_length=255, verbose_name='Razão Social'),
        ),
        migrations.AlterField(
            model_name='autodiversos',
            name='responsavel_cpf',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='CPF/RG do Responsável'),
        ),
        migrations.AlterField(
            model_name='autodiversos',
            name='responsavel_nome',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome do Responsável'),
        ),
        migrations.AlterField(
            model_name='autodiversos',
            name='sincronizado_em',
            field=models.DateTimeField(blank=True, help_text='Momento em que os dados chegaram ao backend', null=True, verbose_name='Primeira sincronizacao'),
        ),
        migrations.AlterField(
            model_name='autodiversos',
            name='substituicao_troco',
            field=models.BooleanField(default=False, verbose_name='Substituição do troco em dinheiro por outros produtos não consentidos'),
        ),
        migrations.AlterField(
            model_name='autodiversos',
            name='uuid_local',
            field=models.UUIDField(blank=True, help_text='Identificador gerado no mobile para conciliacao offline', null=True, unique=True, verbose_name='UUID local'),
        ),
        migrations.AlterField(
            model_name='autoinfracao',
            name='atividade',
            field=models.CharField(default='Não informado', max_length=255, verbose_name='Atividade'),
        ),
        migrations.AlterField(
            model_name='autoinfracao',
            name='base_legal_outras',
            field=models.TextField(blank=True, help_text='Outras leis e decretos aplicáveis', verbose_name='Outras Bases Legais'),
        ),
        migrations.AlterField(
            model_name='autoinfracao',
            name='data_fiscalizacao',
            field=models.DateField(verbose_name='Data da Fiscalização'),
        ),
        migrations.AlterField(
            model_name='autoinfracao',
            name='data_notificacao',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Notificação'),
        ),
        migrations.AlterField(
            model_name='autoinfracao',
            name='descricao_anexo',
            field=models.TextField(blank=True, verbose_name='Descrição dos Anexos'),
        ),
        migrations.AlterField(
            model_name='autoinfracao',
            name='endereco',
            field=models.CharField(max_length=500, verbose_name='Endereço'),
        ),
        migrations.AlterField(
            model_name='autoinfracao',
            name='estabelecimento_responsavel',
            field=models.CharField(blank=True, max_length=255, verbose_name='Responsável pelo Estabelecimento'),
        ),
        migrations.AlterField(
            model_name='autoinfracao',
            name='fiscal_cargo',
            field=models.CharField(default='Agente de Fiscalização', max_length=100, verbose_name='Cargo do Fiscal'),
        ),
        migrations.AlterField(
            model_name='autoinfracao',
            name='fundamentacao_juridica',
            field=models.TextField(blank=True, help_text='Fundamentação jurídica da autuação', verbose_name='Fundamentação Jurídica'),
        ),
        migrations.AlterField(
            model_name='autoinfracao',
            name='fundamentacao_tecnica',
            field=models.TextField(blank=True, help_text='Fundamentação técnica da autuação', verbose_name='Fundamentação Técnica'),
        ),
        migrations.AlterField(
            model_name='autoinfracao',
            name='hora_fiscalizacao',
            field=models.TimeField(verbose_name='Hora da Fiscalização'),
        ),
        migrations.AlterField(
            model_name='autoinfracao',
            name='infracao_falta_informacao',
            field=models.BooleanField(default=False, verbose_name='Falta de Informação'),
        ),
        migrations.AlterField(
            model_name='autoinfracao',
            name='infracao_precos_abusivos',
            field=models.BooleanField(default=False, verbose_name='Preços Abusivos'),
        ),
        migrations.AlterField(
            model_name='autoinfracao',
            name='municipio',
            field=models.CharField(default='MANAUS', max_length=100, verbose_name='Município'),
        ),
        migrations.AlterField(
            model_name='autoinfracao',
            name='numero',
            field=models.CharField(blank=True, max_length=20, unique=True, verbose_name='Número da Infração'),
        ),
        migrations.AlterField(
            model_name='autoinfracao',
            name='observacoes',
            field=models.TextField(blank=True, verbose_name='Observações'),
        ),
        migrations.AlterField(
            model_name='autoinfracao',
            name='outras_infracoes',
            field=models.TextField(blank=True, verbose_name='Outras Infrações'),
        ),
        migrations.AlterField(
            model_name='autoinfracao',
            name='parecer_numero',
            field=models.CharField(blank=True, help_text='Ex: 152/2025', max_length=50, verbose_name='Número do Parecer'),
        ),
        migrations.AlterField(
            model_name='autoinfracao',
            name='parecer_origem',
            field=models.CharField(default='FISCALIZAÇÃO/PROCON/AM', max_length=100, verbose_name='Origem do Parecer'),
        ),
        migrations.AlterField(
            model_name='autoinfracao',
            name='razao_social',
            field=models.CharField(max_length=255, verbose_name='Razão Social'),
        ),
        migrations.AlterField(
            model_name='autoinfracao',
            name='relatorio',
            field=models.TextField(help_text='Narrativa detalhada dos fatos constatados durante a fiscalização', verbose_name='Relatório'),
        ),
        migrations.AlterField(
            model_name='autoinfracao',
            name='responsavel_cpf',
            field=models.CharField(max_length=14, verbose_name='CPF do Responsável'),
        ),
        migrations.AlterField(
            model_name='autoinfracao',
            name='responsavel_funcao',
            field=models.CharField(blank=True, max_length=100, verbose_name='Função/Cargo'),
        ),
        migrations.AlterField(
            model_name='autoinfracao',
            name='responsavel_nome',
            field=models.CharField(max_length=255, verbose_name='Nome do Responsável'),
        ),
        migrations.AlterField(
            model_name='autoinfracaoavancado',
            name='data_geracao',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data de Geração'),
        ),
        migrations.AlterField(
            model_name='autoinfracaoavancado',
            name='data_modificacao',
            field=models.DateTimeField(auto_now=True, verbose_name='Data de Modificação'),
        ),
        migrations.AlterField(
            model_name='autoinfracaoavancado',
            name='data_notificacao',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data de Notificação'),
        ),
        migrations.AlterField(
            model_name='autoinfracaoavancado',
            name='email_notificacao',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email de Notificação'),
        ),
        migrations.AlterField(
            model_name='autoinfracaoavancado',
            name='notificacao_eletronica',
            field=models.BooleanField(default=False, verbose_name='Notificação Eletrônica'),
        ),
        migrations.AlterField(
            model_name='autoinfracaoavancado',
            name='protocolo_notificacao',
            field=models.CharField(blank=True, max_length=100, verbose_name='Protocolo de Notificação'),
        ),
        migrations.AlterField(
            model_name='autoinfracaoavancado',
            name='status_workflow',
            field=models.CharField(choices=[('RASCUNHO', 'Rascunho'), ('EM_ANALISE', 'Em Análise'), ('APROVADO', 'Aprovado'), ('ASSINADO', 'Assinado'), ('NOTIFICADO', 'Notificado'), ('EM_DEFESA', 'Em Defesa'), ('JULGADO', 'Julgado'), ('PAGO', 'Pago'), ('CANCELADO', 'Cancelado')], default='RASCUNHO', max_length=20, verbose_name='Status do Workflow'),
        ),
        migrations.AlterField(
            model_name='autoinfracaoavancado',
            name='versao_documento',
            field=models.CharField(default='1.0', max_length=20, verbose_name='Versão do Documento'),
        ),
        migrations.AlterField(
            model_name='autoposto',
            name='atuacao',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Atuação'),
        ),
        migrations.AlterField(
            model_name='autoposto',
            name='data_fiscalizacao',
            field=models.DateField(verbose_name='Data da Fiscalização'),
        ),
        migrations.AlterField(
            model_name='autoposto',
            name='device_id',
            field=models.CharField(blank=True, help_text='Identificador enviado via cabecalho X-Device-Id', max_length=100, null=True, verbose_name='ID do dispositivo'),
        ),
        migrations.AlterField(
            model_name='autoposto',
            name='endereco',
            field=models.CharField(max_length=255, verbose_name='Endereço'),
        ),
        migrations.AlterField(
            model_name='autoposto',
            name='fiscal_nome_1',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome do 1º Fiscal'),
        ),
        migrations.AlterField(
            model_name='autoposto',
            name='fiscal_nome_2',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome do 2º Fiscal'),
        ),
        migrations.AlterField(
            model_name='autoposto',
            name='hora_fiscalizacao',
            field=models.TimeField(verbose_name='Hora da Fiscalização'),
        ),
        migrations.AlterField(
            model_name='autoposto',
            name='info_adicionais',
            field=models.TextField(blank=True, null=True, verbose_name='Informações Adicionais'),
        ),
        migrations.AlterField(
            model_name='autoposto',
            name='matricula_fiscal_1',
            field=models.CharField(blank=True, help_text='Matrícula do fiscal responsável pela fiscalização', max_length=20, null=True, verbose_name='Matrícula do Fiscal 1'),
        ),
        migrations.AlterField(
            model_name='autoposto',
            name='municipio',
            field=models.CharField(max_length=100, verbose_name='Município'),
        ),
        migrations.AlterField(
            model_name='autoposto',
            name='nao_vende_diesel_comum',
            field=models.BooleanField(default=False, verbose_name='Não vende Diesel Comum'),
        ),
        migrations.AlterField(
            model_name='autoposto',
            name='nao_vende_diesel_s10',
            field=models.BooleanField(default=False, verbose_name='Não vende Diesel S-10'),
        ),
        migrations.AlterField(
            model_name='autoposto',
            name='nao_vende_etanol',
            field=models.BooleanField(default=False, verbose_name='Não vende Etanol'),
        ),
        migrations.AlterField(
            model_name='autoposto',
            name='nao_vende_gas_aditivada',
            field=models.BooleanField(default=False, verbose_name='Não vende Gasolina Aditivada'),
        ),
        migrations.AlterField(
            model_name='autoposto',
            name='nao_vende_gas_comum',
            field=models.BooleanField(default=False, verbose_name='Não vende Gasolina Comum'),
        ),
        migrations.AlterField(
            model_name='autoposto',
            name='nao_vende_gnv',
            field=models.BooleanField(default=False, verbose_name='Não vende GNV'),
        ),
        migrations.AlterField(
            model_name='autoposto',
            name='numero',
            field=models.CharField(blank=True, max_length=20, unique=True, verbose_name='Número do Auto'),
        ),
        migrations.AlterField(
            model_name='autoposto',
            name='origem',
            field=models.CharField(choices=[('acao', 'Ação Fiscalizatória'), ('denuncia', 'Denúncia'), ('forca_tarefa', 'Força Tarefa'), ('outros', 'Outros')], default='acao', max_length=20, verbose_name='Origem'),
        ),
        migrations.AlterField(
            model_name='autoposto',
            name='porte',
            field=models.CharField(blank=True, choices=[('microempresa', 'Microempresa'), ('pequeno', 'Pequeno Porte'), ('medio', 'Médio Porte'), ('grande', 'Grande Porte')], max_length=20, null=True, verbose_name='Porte da Empresa'),
        ),
        migrations.AlterField(
            model_name='autoposto',
            name='preco_diesel_comum',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True, verbose_name='Preço Diesel Comum (R$/litro)'),
        ),
        migrations.AlterField(
            model_name='autoposto',
            name='preco_diesel_s10',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True, verbose_name='Preço Diesel S-10 (R$/litro)'),
        ),
        migrations.AlterField(
            model_name='autoposto',
            name='preco_etanol',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True, verbose_name='Preço Etanol (R$/litro)'),
        ),
        migrations.AlterField(
            model_name='autoposto',
            name='preco_gasolina_aditivada',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True, verbose_name='Preço Gasolina Aditivada (R$/litro)'),
        ),
        migrations.AlterField(
            model_name='autoposto',
            name='preco_gasolina_comum',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True, verbose_name='Preço Gasolina Comum (R$/litro)'),
        ),
        migrations.AlterField(
            model_name='autoposto',
            name='preco_gnv',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True, verbose_name='Preço GNV (R$/m³)'),
        ),
        migrations.AlterField(
            model_name='autoposto',
            name='razao_social',
            field=models.CharField(max_length=255, verbose_name='Razão Social'),
        ),
        migrations.AlterField(
            model_name='autoposto',
            name='responsavel_cpf',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='CPF/RG do Responsável'),
        ),
        migrations.AlterField(
            model_name='autoposto',
            name='responsavel_nome',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome do Responsável'),
        ),
        migrations.AlterField(
            model_name='autoposto',
            name='sincronizado_em',
            field=models.DateTimeField(blank=True, help_text='Momento em que os dados chegaram ao backend', null=True, verbose_name='Primeira sincronizacao'),
        ),
        migrations.AlterField(
            model_name='autoposto',
            name='uuid_local',
            field=models.UUIDField(blank=True, help_text='Identificador gerado no mobile para conciliacao offline', null=True, unique=True, verbose_name='UUID local'),
        ),
        migrations.AlterField(
            model_name='autosupermercado',
            name='afixacao_precos_fora_padrao',
            field=models.BooleanField(default=False, verbose_name='Afixação de preços fora do padrão'),
        ),
        migrations.AlterField(
            model_name='autosupermercado',
            name='afixacao_precos_fracionados_fora_padrao',
            field=models.BooleanField(default=False, verbose_name='Afixação de preços na venda a varejo de produtos fracionados fora do padrão'),
        ),
        migrations.AlterField(
            model_name='autosupermercado',
            name='ausencia_afixacao_precos',
            field=models.BooleanField(default=False, verbose_name='Ausência de afixação de preços'),
        ),
        migrations.AlterField(
            model_name='autosupermercado',
            name='ausencia_placas_promocao_vencimento',
            field=models.BooleanField(default=False, verbose_name='Ausência das placas ou cartazes informativos acerca da data de validade de produtos em promoção'),
        ),
        migrations.AlterField(
            model_name='autosupermercado',
            name='ausencia_visibilidade_descontos',
            field=models.BooleanField(default=False, verbose_name='Ausência de visibilidade de descontos'),
        ),
        migrations.AlterField(
            model_name='autosupermercado',
            name='auto_apreensao',
            field=models.BooleanField(default=False, verbose_name='Gerou Auto de Apreensão/Inutilização?'),
        ),
        migrations.AlterField(
            model_name='autosupermercado',
            name='auto_apreensao_numero',
            field=models.CharField(blank=True, max_length=50, verbose_name='Nº do Auto de Apreensão'),
        ),
        migrations.AlterField(
            model_name='autosupermercado',
            name='comercializar_sem_validade',
            field=models.BooleanField(default=False, verbose_name='Comercializar produtos sem validade ou com validade ilegível'),
        ),
        migrations.AlterField(
            model_name='autosupermercado',
            name='cominacao_legal',
            field=models.TextField(blank=True, verbose_name='Cominação Legal'),
        ),
        migrations.AlterField(
            model_name='autosupermercado',
            name='data_fiscalizacao',
            field=models.DateField(verbose_name='Data da Fiscalização'),
        ),
        migrations.AlterField(
            model_name='autosupermercado',
            name='device_id',
            field=models.CharField(blank=True, help_text='Identificador enviado via cabecalho X-Device-Id', max_length=100, null=True, verbose_name='ID do dispositivo'),
        ),
        migrations.AlterField(
            model_name='autosupermercado',
            name='endereco',
            field=models.CharField(max_length=255, verbose_name='Endereço'),
        ),
        migrations.AlterField(
            model_name='autosupermercado',
            name='fiscal_nome_1',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome do 1º Fiscal'),
        ),
        migrations.AlterField(
            model_name='autosupermercado',
            name='fiscal_nome_2',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome do 2º Fiscal'),
        ),
        migrations.AlterField(
            model_name='autosupermercado',
            name='hora_fiscalizacao',
            field=models.TimeField(verbose_name='Hora da Fiscalização'),
        ),
        migrations.AlterField(
            model_name='autosupermercado',
            name='instrucoes_fiscalizado',
            field=models.TextField(blank=True, verbose_name='Instruções ao Fiscalizado'),
        ),
        migrations.AlterField(
            model_name='autosupermercado',
            name='justificativa_pericia',
            field=models.TextField(blank=True, verbose_name='Justificativa da Perícia'),
        ),
        migrations.AlterField(
            model_name='autosupermercado',
            name='municipio',
            field=models.CharField(max_length=100, verbose_name='Município'),
        ),
        migrations.AlterField(
            model_name='autosupermercado',
            name='necessita_pericia',
            field=models.BooleanField(blank=True, null=True, verbose_name='Os itens apreendidos necessitam de perícia?'),
        ),
        migrations.AlterField(
            model_name='autosupermercado',
            name='numero',
            field=models.CharField(blank=True, max_length=20, unique=True, verbose_name='Número do Auto'),
        ),
        migrations.AlterField(
            model_name='autosupermercado',
            name='obstrucao_monitor',
            field=models.BooleanField(default=False, verbose_name='Obstrução do monitor'),
        ),
        migrations.AlterField(
            model_name='autosupermercado',
            name='origem',
            field=models.CharField(choices=[('acao', 'Ação Fiscalizatória'), ('denuncia', 'Denúncia'), ('forca_tarefa', 'Força Tarefa'), ('outros', 'Outros')], default='acao', max_length=20, verbose_name='Origem'),
        ),
        migrations.AlterField(
            model_name='autosupermercado',
            name='outras_irregularidades',
            field=models.TextField(blank=True, verbose_name='Outras Irregularidades Constatadas/Outras Cominações Legais'),
        ),
        migrations.AlterField(
            model_name='autosupermercado',
            name='razao_social',
            field=models.CharField(max_length=255, verbose_name='Razão Social'),
        ),
        migrations.AlterField(
            model_name='autosupermercado',
            name='responsavel_cpf',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='CPF/RG do Responsável'),
        ),
        migrations.AlterField(
            model_name='autosupermercado',
            name='responsavel_nome',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome do Responsável'),
        ),
        migrations.AlterField(
            model_name='autosupermercado',
            name='sincronizado_em',
            field=models.DateTimeField(blank=True, help_text='Momento em que os dados chegaram ao backend', null=True, verbose_name='Primeira sincronizacao'),
        ),
        migrations.AlterField(
            model_name='autosupermercado',
            name='uuid_local',
            field=models.UUIDField(blank=True, help_text='Identificador gerado no mobile para conciliacao offline', null=True, unique=True, verbose_name='UUID local'),
        ),
        migrations.AlterField(
            model_name='configuracaofiscalizacao',
            name='assinatura_digital_obrigatoria',
            field=models.BooleanField(default=True, verbose_name='Assinatura Digital Obrigatória'),
        ),
        migrations.AlterField(
            model_name='configuracaofiscalizacao',
            name='backup_automatico',
            field=models.BooleanField(default=True, verbose_name='Backup Automático'),
        ),
        migrations.AlterField(
            model_name='configuracaofiscalizacao',
            name='certificado_digital_obrigatorio',
            field=models.BooleanField(default=False, verbose_name='Certificado Digital Obrigatório'),
        ),
        migrations.AlterField(
            model_name='configuracaofiscalizacao',
            name='email_notificacao',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email para Notificações'),
        ),
        migrations.AlterField(
            model_name='configuracaofiscalizacao',
            name='max_arquivos_por_auto',
            field=models.IntegerField(default=20, verbose_name='Máximo de Arquivos por Auto'),
        ),
        migrations.AlterField(
            model_name='configuracaofiscalizacao',
            name='max_tamanho_arquivo',
            field=models.IntegerField(default=10, verbose_name='Tamanho Máximo de Arquivo (MB)'),
        ),
        migrations.AlterField(
            model_name='configuracaofiscalizacao',
            name='notificacao_automatica',
            field=models.BooleanField(default=True, verbose_name='Notificação Automática'),
        ),
        migrations.AlterField(
            model_name='configuracaofiscalizacao',
            name='retencao_backup_dias',
            field=models.IntegerField(default=365, verbose_name='Retenção de Backup (dias)'),
        ),
        migrations.AlterField(
            model_name='configuracaofiscalizacao',
            name='sms_notificacao',
            field=models.CharField(blank=True, max_length=20, verbose_name='SMS para Notificações'),
        ),
        migrations.AlterField(
            model_name='controleprazos',
            name='data_inicio',
            field=models.DateTimeField(verbose_name='Data de Início'),
        ),
        migrations.AlterField(
            model_name='controleprazos',
            name='data_prorrogacao',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data de Prorrogação'),
        ),
        migrations.AlterField(
            model_name='controleprazos',
            name='descricao',
            field=models.TextField(verbose_name='Descrição do Prazo'),
        ),
        migrations.AlterField(
            model_name='controleprazos',
            name='historico_alteracoes',
            field=models.JSONField(blank=True, default=list, verbose_name='Histórico de Alterações'),
        ),
        migrations.AlterField(
            model_name='controleprazos',
            name='notificar_emails',
            field=models.JSONField(blank=True, default=list, verbose_name='Emails para Notificação'),
        ),
        migrations.AlterField(
            model_name='controleprazos',
            name='responsavel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Responsável'),
        ),
        migrations.AlterField(
            model_name='cupomfiscalposto',
            name='numero_cupom',
            field=models.CharField(max_length=50, verbose_name='Nº do Cupom'),
        ),
        migrations.AlterField(
            model_name='cupomfiscalposto',
            name='percentual_diferenca',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Diferença (%)'),
        ),
        migrations.AlterField(
            model_name='documentoprocesso',
            name='descricao',
            field=models.TextField(blank=True, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='documentoprocesso',
            name='tipo',
            field=models.CharField(choices=[('defesa', 'Defesa'), ('recurso', 'Recurso'), ('parecer', 'Parecer Técnico'), ('decisao', 'Decisão'), ('outros', 'Outros')], max_length=20, verbose_name='Tipo do Documento'),
        ),
        migrations.AlterField(
            model_name='documentoprocesso',
            name='titulo',
            field=models.CharField(max_length=255, verbose_name='Título'),
        ),
        migrations.AlterField(
            model_name='documentoprocesso',
            name='usuario_upload',
            field=models.CharField(blank=True, max_length=255, verbose_name='Usuário'),
        ),
        migrations.AlterField(
            model_name='evidenciafiscalizacao',
            name='descricao',
            field=models.TextField(blank=True, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='evidenciafiscalizacao',
            name='tipo',
            field=models.CharField(choices=[('FOTO', 'Foto'), ('VIDEO', 'Vídeo'), ('DOCUMENTO', 'Documento'), ('AUDIO', 'Áudio'), ('OUTROS', 'Outros')], max_length=20, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='evidenciafiscalizacao',
            name='titulo',
            field=models.CharField(max_length=200, verbose_name='Título'),
        ),
        migrations.AlterField(
            model_name='evidenciafotografica',
            name='descricao',
            field=models.TextField(verbose_name='Descrição da Evidência'),
        ),
        migrations.AlterField(
            model_name='evidenciafotografica',
            name='fiscal_upload',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Fiscal Responsável'),
        ),
        migrations.AlterField(
            model_name='evidenciafotografica',
            name='tipo_evidencia',
            field=models.CharField(choices=[('irregularidade', 'Irregularidade'), ('documento', 'Documento'), ('ambiente', 'Ambiente'), ('produto', 'Produto'), ('outros', 'Outros')], max_length=20, verbose_name='Tipo de Evidência'),
        ),
        migrations.AlterField(
            model_name='historicoautoinfracao',
            name='acao',
            field=models.CharField(max_length=100, verbose_name='Ação'),
        ),
        migrations.AlterField(
            model_name='historicoautoinfracao',
            name='data_acao',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data da Ação'),
        ),
        migrations.AlterField(
            model_name='historicoautoinfracao',
            name='descricao',
            field=models.TextField(verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='historicoprocesso',
            name='data_mudanca',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data da Mudança'),
        ),
        migrations.AlterField(
            model_name='historicoprocesso',
            name='observacao',
            field=models.TextField(blank=True, verbose_name='Observação'),
        ),
        migrations.AlterField(
            model_name='historicoprocesso',
            name='usuario',
            field=models.CharField(blank=True, help_text='Usuário que fez a alteração', max_length=255, verbose_name='Usuário'),
        ),
        migrations.AlterField(
            model_name='historicostatusinfracao',
            name='data_mudanca',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data da Mudança'),
        ),
        migrations.AlterField(
            model_name='historicostatusinfracao',
            name='observacoes',
            field=models.TextField(blank=True, verbose_name='Observações'),
        ),
        migrations.AlterField(
            model_name='historicostatusinfracao',
            name='usuario',
            field=models.CharField(blank=True, max_length=255, verbose_name='Usuário'),
        ),
        migrations.AlterField(
            model_name='itemapreensaoinutilizacao',
            name='especificacao',
            field=models.TextField(verbose_name='Especificação'),
        ),
        migrations.AlterField(
            model_name='itemapreensaoinutilizacao',
            name='motivo_apreensao',
            field=models.TextField(verbose_name='Motivo da Apreensão/Inutilização'),
        ),
        migrations.AlterField(
            model_name='itemapreensaoinutilizacao',
            name='valor_unitario',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Unitário'),
        ),
        migrations.AlterField(
            model_name='mobiledevicetoken',
            name='ultimo_registro',
            field=models.DateTimeField(auto_now=True, verbose_name='ltimo registro'),
        ),
        migrations.AlterField(
            model_name='notafiscalposto',
            name='numero_nota',
            field=models.CharField(max_length=50, verbose_name='Número da Nota Fiscal'),
        ),
        migrations.AlterField(
            model_name='notafiscalposto',
            name='preco',
            field=models.DecimalField(decimal_places=3, max_digits=6, verbose_name='Preço por Litro'),
        ),
        migrations.AlterField(
            model_name='notafiscalposto',
            name='tipo_nota',
            field=models.CharField(choices=[('aumento', 'Último Aumento'), ('anterior', 'Anteriores')], max_length=10, verbose_name='Tipo da Nota'),
        ),
        migrations.AlterField(
            model_name='notificacaoeletronica',
            name='destinatario_cpf_cnpj',
            field=models.CharField(blank=True, max_length=18, null=True, verbose_name='CPF/CNPJ do Destinatário'),
        ),
        migrations.AlterField(
            model_name='notificacaoeletronica',
            name='destinatario_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email do Destinatário'),
        ),
        migrations.AlterField(
            model_name='notificacaoeletronica',
            name='destinatario_nome',
            field=models.CharField(max_length=255, verbose_name='Nome do Destinatário'),
        ),
        migrations.AlterField(
            model_name='notificacaoeletronica',
            name='max_tentativas',
            field=models.IntegerField(default=3, verbose_name='Máximo de Tentativas'),
        ),
        migrations.AlterField(
            model_name='notificacaoeletronica',
            name='proxima_tentativa',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Próxima Tentativa'),
        ),
        migrations.AlterField(
            model_name='notificacaoeletronica',
            name='tipo_notificacao',
            field=models.CharField(choices=[('auto_infracao', 'Auto de Infração'), ('prazo_vencendo', 'Prazo Vencendo'), ('prazo_vencido', 'Prazo Vencido'), ('defesa_apresentada', 'Defesa Apresentada'), ('recurso_apresentado', 'Recurso Apresentado'), ('decisao_proferida', 'Decisão Proferida')], max_length=20, verbose_name='Tipo de Notificação'),
        ),
        migrations.AlterField(
            model_name='pedidonotificacaomobile',
            name='device_id',
            field=models.CharField(blank=True, help_text='Identificador enviado via cabecalho X-Device-Id', max_length=100, null=True, verbose_name='ID do dispositivo'),
        ),
        migrations.AlterField(
            model_name='pedidonotificacaomobile',
            name='notificacao_numero',
            field=models.CharField(blank=True, max_length=50, verbose_name='Numero da notificacao'),
        ),
        migrations.AlterField(
            model_name='pedidonotificacaomobile',
            name='observacoes',
            field=models.TextField(blank=True, verbose_name='Observacoes'),
        ),
        migrations.AlterField(
            model_name='pedidonotificacaomobile',
            name='offline_em',
            field=models.DateTimeField(blank=True, help_text='Timestamp informado pelo app quando sem conexao', null=True, verbose_name='Registrado offline em'),
        ),
        migrations.AlterField(
            model_name='pedidonotificacaomobile',
            name='sincronizado_em',
            field=models.DateTimeField(blank=True, help_text='Momento em que o backend recebeu o registro', null=True, verbose_name='Primeira sincronizacao'),
        ),
        migrations.AlterField(
            model_name='pedidonotificacaomobile',
            name='status',
            field=models.CharField(choices=[('EM_ANALISE', 'Em analise'), ('EMITIDA', 'Emitida'), ('CANCELADA', 'Cancelada')], default='EM_ANALISE', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='pedidonotificacaomobile',
            name='tipo',
            field=models.CharField(max_length=50, verbose_name='Tipo de notificacao'),
        ),
        migrations.AlterField(
            model_name='pedidonotificacaomobile',
            name='uuid_local',
            field=models.UUIDField(blank=True, default=uuid.uuid4, help_text='Identificador gerado pelo mobile para conciliacao offline', null=True, unique=True, verbose_name='UUID local'),
        ),
        migrations.AlterField(
            model_name='processo',
            name='analista_responsavel',
            field=models.CharField(blank=True, help_text='Analista responsável pela análise do processo', max_length=255, verbose_name='Analista Responsável'),
        ),
        migrations.AlterField(
            model_name='processo',
            name='auto_infracao',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='processo', to='fiscalizacao.autoinfracao', verbose_name='Auto de Infração'),
        ),
        migrations.AlterField(
            model_name='processo',
            name='autuado',
            field=models.CharField(help_text='Razão social da empresa autuada', max_length=255, verbose_name='Autuado (Razão Social)'),
        ),
        migrations.AlterField(
            model_name='processo',
            name='data_finalizacao',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Finalização'),
        ),
        migrations.AlterField(
            model_name='processo',
            name='data_notificacao',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Notificação'),
        ),
        migrations.AlterField(
            model_name='processo',
            name='fiscal_responsavel',
            field=models.CharField(blank=True, help_text='Fiscal que conduziu a fiscalização', max_length=255, verbose_name='Fiscal Responsável'),
        ),
        migrations.AlterField(
            model_name='processo',
            name='numero_processo',
            field=models.CharField(blank=True, help_text='Gerado automaticamente no formato PROC-00001/2025', max_length=25, unique=True, verbose_name='Número do Processo'),
        ),
        migrations.AlterField(
            model_name='processo',
            name='observacoes',
            field=models.TextField(blank=True, help_text='Observações gerais sobre o processo', verbose_name='Observações'),
        ),
        migrations.AlterField(
            model_name='processo',
            name='observacoes_internas',
            field=models.TextField(blank=True, help_text='Observações internas não incluídas nos documentos', verbose_name='Observações Internas'),
        ),
        migrations.AlterField(
            model_name='processo',
            name='prazo_defesa',
            field=models.DateField(blank=True, help_text='Data limite para apresentação da defesa', null=True, verbose_name='Prazo para Defesa'),
        ),
        migrations.AlterField(
            model_name='processo',
            name='prazo_recurso',
            field=models.DateField(blank=True, help_text='Data limite para apresentação do recurso', null=True, verbose_name='Prazo para Recurso'),
        ),
        migrations.AlterField(
            model_name='processo',
            name='status',
            field=models.CharField(choices=[('aguardando_defesa', 'Aguardando Defesa'), ('defesa_apresentada', 'Defesa Apresentada'), ('em_analise', 'Em Análise'), ('aguardando_recurso', 'Aguardando Recurso'), ('recurso_apresentado', 'Recurso Apresentado'), ('julgamento', 'Em Julgamento'), ('finalizado_procedente', 'Finalizado - Procedente'), ('finalizado_improcedente', 'Finalizado - Improcedente'), ('arquivado', 'Arquivado'), ('prescrito', 'Prescrito')], default='aguardando_defesa', max_length=50, verbose_name='Status do Processo'),
        ),
        migrations.AlterField(
            model_name='processo',
            name='valor_final',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Valor após recursos e decisão final', max_digits=10, null=True, verbose_name='Valor Final (R$)'),
        ),
        migrations.AlterField(
            model_name='sequenciaautos',
            name='ultimo_numero',
            field=models.IntegerField(default=0, verbose_name='Último Número Gerado'),
        ),
        migrations.AlterField(
            model_name='sequenciaautosapreensao',
            name='ultimo_numero',
            field=models.IntegerField(default=0, verbose_name='Último Número Gerado'),
        ),
        migrations.AlterField(
            model_name='templateautoinfracao',
            name='base_legal_padrao',
            field=models.TextField(blank=True, verbose_name='Base Legal Padrão'),
        ),
        migrations.AlterField(
            model_name='templateautoinfracao',
            name='campos_obrigatorios',
            field=models.JSONField(default=list, verbose_name='Campos Obrigatórios'),
        ),
        migrations.AlterField(
            model_name='templateautoinfracao',
            name='configuracao',
            field=models.JSONField(default=dict, verbose_name='Configuração'),
        ),
        migrations.AlterField(
            model_name='templateautoinfracao',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação'),
        ),
        migrations.AlterField(
            model_name='templateautoinfracao',
            name='descricao',
            field=models.TextField(blank=True, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='templateautoinfracao',
            name='fundamentacao_padrao',
            field=models.TextField(blank=True, verbose_name='Fundamentação Padrão'),
        ),
        migrations.AlterField(
            model_name='templateautoinfracao',
            name='padrao',
            field=models.BooleanField(default=False, verbose_name='Template Padrão'),
        ),
        migrations.AlterField(
            model_name='templateautoinfracao',
            name='prazo_defesa_padrao',
            field=models.IntegerField(default=30, verbose_name='Prazo para Defesa Padrão (dias)'),
        ),
        migrations.AlterField(
            model_name='templateautoinfracao',
            name='prazo_pagamento_padrao',
            field=models.IntegerField(default=30, verbose_name='Prazo para Pagamento Padrão (dias)'),
        ),
        migrations.AlterField(
            model_name='templateautoinfracao',
            name='valor_multa_padrao',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Valor da Multa Padrão'),
        ),
        migrations.AlterField(
            model_name='tipofiscalizacao',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação'),
        ),
        migrations.AlterField(
            model_name='tipofiscalizacao',
            name='descricao',
            field=models.TextField(blank=True, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='tipofiscalizacao',
            name='tipo',
            field=models.CharField(choices=[('PRESENCIAL', 'Fiscalização Presencial'), ('REMOTA', 'Fiscalização Remota'), ('DENUNCIA', 'Denúncia'), ('ACAO_PREVENTIVA', 'Ação Preventiva'), ('FORCA_TAREFA', 'Força Tarefa'), ('MONITORAMENTO', 'Monitoramento'), ('AUDITORIA', 'Auditoria')], max_length=20, verbose_name='Tipo'),
        ),
    ]
