# Generated by Django 5.2.6 on 2025-11-28 17:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('fiscalizacao', '0003_alter_autoapreensaoinutilizacao_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SequenciaProcesso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.IntegerField(unique=True, verbose_name='Ano')),
                ('ultimo_sequencial_unidade', models.IntegerField(default=0, verbose_name='Último Sequencial da Unidade')),
                ('ultimo_sequencial_orgao', models.IntegerField(default=0, verbose_name='Último Sequencial do Órgão')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Sequência de Processo',
                'verbose_name_plural': 'Sequências de Processos',
                'ordering': ['-ano'],
            },
        ),
        migrations.AddField(
            model_name='processo',
            name='auto_constatacao_content_type',
            field=models.ForeignKey(blank=True, limit_choices_to={'model__in': ['autobanco', 'autoposto', 'autosupermercado', 'autodiversos']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processos_auto_constatacao', to='contenttypes.contenttype', verbose_name='Tipo de Auto de Constatação'),
        ),
        migrations.AddField(
            model_name='processo',
            name='auto_constatacao_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='processo',
            index=models.Index(fields=['auto_constatacao_content_type', 'auto_constatacao_id'], name='fiscalizaca_auto_co_idx'),
        ),
        migrations.AlterField(
            model_name='processo',
            name='auto_infracao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processos', to='fiscalizacao.autoinfracao', verbose_name='Auto de Infração'),
        ),
        migrations.AlterField(
            model_name='processo',
            name='numero_processo',
            field=models.CharField(blank=True, help_text='Gerado automaticamente no padrão SEI: 00001.012345/2025', max_length=50, unique=True, verbose_name='Número do Processo'),
        ),
        migrations.AlterField(
            model_name='processo',
            name='status',
            field=models.CharField(choices=[('sem_infracao', 'Sem Infração - Aguardando Arquivamento'), ('aguardando_auto_infracao', 'Aguardando Auto de Infração'), ('aguardando_defesa', 'Aguardando Defesa'), ('defesa_apresentada', 'Defesa Apresentada'), ('em_analise', 'Em Análise'), ('aguardando_recurso', 'Aguardando Recurso'), ('recurso_apresentado', 'Recurso Apresentado'), ('julgamento', 'Em Julgamento'), ('finalizado_procedente', 'Finalizado - Procedente'), ('finalizado_improcedente', 'Finalizado - Improcedente'), ('arquivado', 'Arquivado'), ('prescrito', 'Prescrito')], default='aguardando_auto_infracao', max_length=50, verbose_name='Status do Processo'),
        ),
    ]
