# Generated by Django 5.2.1 on 2025-08-28 15:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiscalizacao', '0003_autosupermercado_cominacao_legal_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SequenciaAutosApreensao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.IntegerField(unique=True, verbose_name='Ano')),
                ('ultimo_numero', models.IntegerField(default=0, verbose_name='Último Número Gerado')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Sequência de Auto de Apreensão',
                'verbose_name_plural': 'Sequências de Autos de Apreensão',
                'ordering': ['-ano'],
            },
        ),
        migrations.AddField(
            model_name='autoapreensaoinutilizacao',
            name='auto_constatacao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='autos_apreensao_inutilizacao', to='fiscalizacao.autosupermercado', verbose_name='Auto de Constatação'),
        ),
    ]
