# Generated by Django 4.2.11 on 2025-08-29 01:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fiscalizacao', '0004_sequenciaautosapreensao_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notificacaoeletronica',
            options={'ordering': ['-data_envio'], 'verbose_name': 'Notificação Eletrônica', 'verbose_name_plural': 'Notificações Eletrônicas'},
        ),
        migrations.RemoveField(
            model_name='configuracaofiscalizacao',
            name='aprovacao_obrigatoria',
        ),
        migrations.RemoveField(
            model_name='configuracaofiscalizacao',
            name='certificado_padrao',
        ),
        migrations.RemoveField(
            model_name='configuracaofiscalizacao',
            name='configurado_por',
        ),
        migrations.RemoveField(
            model_name='configuracaofiscalizacao',
            name='data_configuracao',
        ),
        migrations.RemoveField(
            model_name='configuracaofiscalizacao',
            name='dias_antecedencia_prazo',
        ),
        migrations.RemoveField(
            model_name='configuracaofiscalizacao',
            name='max_evidencias_por_auto',
        ),
        migrations.RemoveField(
            model_name='configuracaofiscalizacao',
            name='notificar_atrasos',
        ),
        migrations.RemoveField(
            model_name='configuracaofiscalizacao',
            name='notificar_prazos',
        ),
        migrations.RemoveField(
            model_name='configuracaofiscalizacao',
            name='workflow_automatico',
        ),
        migrations.RemoveField(
            model_name='notificacaoeletronica',
            name='auto_infracao',
        ),
        migrations.RemoveField(
            model_name='notificacaoeletronica',
            name='data_criacao',
        ),
        migrations.RemoveField(
            model_name='notificacaoeletronica',
            name='destinatario',
        ),
        migrations.RemoveField(
            model_name='notificacaoeletronica',
            name='enviado_por',
        ),
        migrations.RemoveField(
            model_name='notificacaoeletronica',
            name='erro_mensagem',
        ),
        migrations.RemoveField(
            model_name='notificacaoeletronica',
            name='protocolo',
        ),
        migrations.RemoveField(
            model_name='notificacaoeletronica',
            name='tentativas',
        ),
        migrations.RemoveField(
            model_name='notificacaoeletronica',
            name='tipo',
        ),
        migrations.AddField(
            model_name='configuracaofiscalizacao',
            name='alerta_prazo_dias',
            field=models.IntegerField(default=5, verbose_name='Alerta de Prazo (dias antes)'),
        ),
        migrations.AddField(
            model_name='configuracaofiscalizacao',
            name='backup_automatico',
            field=models.BooleanField(default=True, verbose_name='Backup Automático'),
        ),
        migrations.AddField(
            model_name='configuracaofiscalizacao',
            name='certificado_digital_obrigatorio',
            field=models.BooleanField(default=False, verbose_name='Certificado Digital Obrigatório'),
        ),
        migrations.AddField(
            model_name='configuracaofiscalizacao',
            name='email_notificacao',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email para Notificações'),
        ),
        migrations.AddField(
            model_name='configuracaofiscalizacao',
            name='max_arquivos_por_auto',
            field=models.IntegerField(default=20, verbose_name='Máximo de Arquivos por Auto'),
        ),
        migrations.AddField(
            model_name='configuracaofiscalizacao',
            name='notificacao_automatica',
            field=models.BooleanField(default=True, verbose_name='Notificação Automática'),
        ),
        migrations.AddField(
            model_name='configuracaofiscalizacao',
            name='prazo_assinatura_dias',
            field=models.IntegerField(default=7, verbose_name='Prazo para Assinatura (dias)'),
        ),
        migrations.AddField(
            model_name='configuracaofiscalizacao',
            name='prazo_defesa_dias',
            field=models.IntegerField(default=15, verbose_name='Prazo para Defesa (dias)'),
        ),
        migrations.AddField(
            model_name='configuracaofiscalizacao',
            name='prazo_recurso_dias',
            field=models.IntegerField(default=10, verbose_name='Prazo para Recurso (dias)'),
        ),
        migrations.AddField(
            model_name='configuracaofiscalizacao',
            name='retencao_backup_dias',
            field=models.IntegerField(default=365, verbose_name='Retenção de Backup (dias)'),
        ),
        migrations.AddField(
            model_name='configuracaofiscalizacao',
            name='sms_notificacao',
            field=models.CharField(blank=True, max_length=20, verbose_name='SMS para Notificações'),
        ),
        migrations.AddField(
            model_name='notificacaoeletronica',
            name='anexos',
            field=models.JSONField(blank=True, default=list, verbose_name='Anexos'),
        ),
        migrations.AddField(
            model_name='notificacaoeletronica',
            name='auto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notificacoes', to='fiscalizacao.autobanco'),
        ),
        migrations.AddField(
            model_name='notificacaoeletronica',
            name='auto_diversos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notificacoes', to='fiscalizacao.autodiversos'),
        ),
        migrations.AddField(
            model_name='notificacaoeletronica',
            name='auto_posto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notificacoes', to='fiscalizacao.autoposto'),
        ),
        migrations.AddField(
            model_name='notificacaoeletronica',
            name='auto_supermercado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notificacoes', to='fiscalizacao.autosupermercado'),
        ),
        migrations.AddField(
            model_name='notificacaoeletronica',
            name='data_leitura',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data de Leitura'),
        ),
        migrations.AddField(
            model_name='notificacaoeletronica',
            name='destinatario_cpf_cnpj',
            field=models.CharField(blank=True, max_length=18, null=True, verbose_name='CPF/CNPJ do Destinatário'),
        ),
        migrations.AddField(
            model_name='notificacaoeletronica',
            name='destinatario_email',
            field=models.EmailField(max_length=254, verbose_name='Email do Destinatário'),
        ),
        migrations.AddField(
            model_name='notificacaoeletronica',
            name='destinatario_nome',
            field=models.CharField(max_length=255, verbose_name='Nome do Destinatário'),
        ),
        migrations.AddField(
            model_name='notificacaoeletronica',
            name='logs_envio',
            field=models.JSONField(blank=True, default=list, verbose_name='Logs de Envio'),
        ),
        migrations.AddField(
            model_name='notificacaoeletronica',
            name='max_tentativas',
            field=models.IntegerField(default=3, verbose_name='Máximo de Tentativas'),
        ),
        migrations.AddField(
            model_name='notificacaoeletronica',
            name='proxima_tentativa',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Próxima Tentativa'),
        ),
        migrations.AddField(
            model_name='notificacaoeletronica',
            name='tentativas_envio',
            field=models.IntegerField(default=0, verbose_name='Tentativas de Envio'),
        ),
        migrations.AddField(
            model_name='notificacaoeletronica',
            name='tipo_notificacao',
            field=models.CharField(choices=[('auto_infracao', 'Auto de Infração'), ('prazo_vencendo', 'Prazo Vencendo'), ('prazo_vencido', 'Prazo Vencido'), ('defesa_apresentada', 'Defesa Apresentada'), ('recurso_apresentado', 'Recurso Apresentado'), ('decisao_proferida', 'Decisão Proferida')], max_length=20, verbose_name='Tipo de Notificação'),
        ),
        migrations.AlterField(
            model_name='configuracaofiscalizacao',
            name='assinatura_digital_obrigatoria',
            field=models.BooleanField(default=True, verbose_name='Assinatura Digital Obrigatória'),
        ),
        migrations.AlterField(
            model_name='configuracaofiscalizacao',
            name='max_tamanho_arquivo',
            field=models.IntegerField(default=10, verbose_name='Tamanho Máximo de Arquivo (MB)'),
        ),
        migrations.AlterField(
            model_name='notificacaoeletronica',
            name='assunto',
            field=models.CharField(max_length=255, verbose_name='Assunto'),
        ),
        migrations.AlterField(
            model_name='notificacaoeletronica',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('enviada', 'Enviada'), ('entregue', 'Entregue'), ('lida', 'Lida'), ('erro', 'Erro')], default='pendente', max_length=20, verbose_name='Status'),
        ),
        migrations.CreateModel(
            name='EvidenciaFotografica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_evidencia', models.CharField(choices=[('irregularidade', 'Irregularidade'), ('documento', 'Documento'), ('ambiente', 'Ambiente'), ('produto', 'Produto'), ('outros', 'Outros')], max_length=20, verbose_name='Tipo de Evidência')),
                ('descricao', models.TextField(verbose_name='Descrição da Evidência')),
                ('foto', models.ImageField(upload_to='evidencias_fiscais/', verbose_name='Foto')),
                ('data_upload', models.DateTimeField(auto_now_add=True, verbose_name='Data do Upload')),
                ('auto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evidencias', to='fiscalizacao.autobanco')),
                ('auto_diversos', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evidencias', to='fiscalizacao.autodiversos')),
                ('auto_posto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evidencias', to='fiscalizacao.autoposto')),
                ('auto_supermercado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evidencias', to='fiscalizacao.autosupermercado')),
                ('fiscal_upload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Fiscal Responsável')),
            ],
            options={
                'verbose_name': 'Evidência Fotográfica',
                'verbose_name_plural': 'Evidências Fotográficas',
                'ordering': ['-data_upload'],
            },
        ),
        migrations.CreateModel(
            name='ControlePrazos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_prazo', models.CharField(choices=[('defesa', 'Prazo para Defesa'), ('recurso', 'Prazo para Recurso'), ('envio_documentos', 'Prazo para Envio de Documentos'), ('pagamento', 'Prazo para Pagamento'), ('compliance', 'Prazo para Compliance'), ('outros', 'Outros')], max_length=20, verbose_name='Tipo de Prazo')),
                ('descricao', models.TextField(verbose_name='Descrição do Prazo')),
                ('data_inicio', models.DateTimeField(verbose_name='Data de Início')),
                ('data_fim', models.DateTimeField(verbose_name='Data de Fim')),
                ('data_prorrogacao', models.DateTimeField(blank=True, null=True, verbose_name='Data de Prorrogação')),
                ('status', models.CharField(choices=[('ativo', 'Ativo'), ('vencendo', 'Vencendo'), ('vencido', 'Vencido'), ('prorrogado', 'Prorrogado'), ('suspenso', 'Suspenso'), ('finalizado', 'Finalizado')], default='ativo', max_length=20, verbose_name='Status')),
                ('dias_restantes', models.IntegerField(blank=True, null=True, verbose_name='Dias Restantes')),
                ('alerta_5_dias', models.BooleanField(default=False, verbose_name='Alerta 5 dias antes')),
                ('alerta_3_dias', models.BooleanField(default=False, verbose_name='Alerta 3 dias antes')),
                ('alerta_1_dia', models.BooleanField(default=False, verbose_name='Alerta 1 dia antes')),
                ('alerta_vencido', models.BooleanField(default=False, verbose_name='Alerta vencido')),
                ('notificar_emails', models.JSONField(blank=True, default=list, verbose_name='Emails para Notificação')),
                ('historico_alteracoes', models.JSONField(blank=True, default=list, verbose_name='Histórico de Alterações')),
                ('auto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prazos', to='fiscalizacao.autobanco')),
                ('auto_diversos', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prazos', to='fiscalizacao.autodiversos')),
                ('auto_posto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prazos', to='fiscalizacao.autoposto')),
                ('auto_supermercado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prazos', to='fiscalizacao.autosupermercado')),
                ('responsavel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Responsável')),
            ],
            options={
                'verbose_name': 'Controle de Prazo',
                'verbose_name_plural': 'Controle de Prazos',
                'ordering': ['data_fim'],
            },
        ),
        migrations.CreateModel(
            name='AssinaturaDigital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_assinatura', models.CharField(choices=[('fiscal_1', 'Fiscal 1'), ('fiscal_2', 'Fiscal 2'), ('responsavel', 'Responsável'), ('testemunha', 'Testemunha')], max_length=20, verbose_name='Tipo de Assinatura')),
                ('nome_assinante', models.CharField(max_length=255, verbose_name='Nome do Assinante')),
                ('cpf_assinante', models.CharField(max_length=14, verbose_name='CPF do Assinante')),
                ('email_assinante', models.EmailField(blank=True, max_length=254, verbose_name='Email do Assinante')),
                ('hash_assinatura', models.CharField(blank=True, max_length=255, verbose_name='Hash da Assinatura')),
                ('certificado_digital', models.TextField(blank=True, verbose_name='Certificado Digital')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('assinado', 'Assinado'), ('rejeitado', 'Rejeitado'), ('expirado', 'Expirado')], default='pendente', max_length=20, verbose_name='Status')),
                ('data_assinatura', models.DateTimeField(blank=True, null=True, verbose_name='Data da Assinatura')),
                ('data_expiracao', models.DateTimeField(verbose_name='Data de Expiração')),
                ('ip_assinatura', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP da Assinatura')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('assinatura_manual', models.ImageField(blank=True, null=True, upload_to='assinaturas_manuais/', verbose_name='Assinatura Manual')),
                ('auto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assinaturas_digitais', to='fiscalizacao.autobanco')),
                ('auto_diversos', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assinaturas_digitais', to='fiscalizacao.autodiversos')),
                ('auto_posto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assinaturas_digitais', to='fiscalizacao.autoposto')),
                ('auto_supermercado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assinaturas_digitais', to='fiscalizacao.autosupermercado')),
            ],
            options={
                'verbose_name': 'Assinatura Digital',
                'verbose_name_plural': 'Assinaturas Digitais',
                'ordering': ['-data_assinatura'],
            },
        ),
    ]
