# Generated by Django 5.2.5 on 2025-08-29 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiscalizacao', '0005_alter_notificacaoeletronica_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificacaoeletronica',
            name='destinatario_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email do Destinatário'),
        ),
    ]
