# Generated by Django 4.2.11 on 2026-01-15 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiscalizacao', '0007_notificacao_ppa'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='processo',
            name='fiscalizaca_auto_co_idx',
        ),
        migrations.AlterField(
            model_name='autoapreensaoinutilizacao',
            name='ano_documento',
            field=models.IntegerField(default=2026),
        ),
        migrations.AlterField(
            model_name='processo',
            name='numero_processo',
            field=models.CharField(blank=True, help_text='Gerado automaticamente no padrão SEI: 00001.012345/2025-49', max_length=50, unique=True, verbose_name='Número do Processo'),
        ),
    ]
