# Generated by Django 5.2.5 on 2026-01-15 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiscalizacao', '0008_remove_processo_fiscalizaca_auto_co_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificacaoeletronica',
            name='representante_legal',
            field=models.CharField(blank=True, max_length=255, verbose_name='Representante Legal'),
        ),
    ]
