# Generated by Django 5.2.5 on 2026-01-15 16:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiscalizacao', '0009_notificacaoeletronica_representante_legal'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificacaoeletronica',
            name='auto_infracao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notificacoes', to='fiscalizacao.autoinfracao', verbose_name='Auto de Infracao'),
        ),
    ]
