# Generated by Django 5.2.5 on 2026-01-15 20:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiscalizacao', '0010_notificacaoeletronica_auto_infracao'),
    ]

    operations = [
        migrations.AddField(
            model_name='autobanco',
            name='cominacao_legal',
            field=models.TextField(blank=True, verbose_name='Cominacao Legal'),
        ),
        migrations.AddField(
            model_name='autobanco',
            name='relogio_exposto',
            field=models.BooleanField(blank=True, null=True, verbose_name='Relogio exposto em local visivel?'),
        ),
        migrations.AddField(
            model_name='atendimentocaixabanco',
            name='tipo_servico',
            field=models.CharField(choices=[('simples', 'Servico de caixa'), ('complexo', 'Servico mais complexo')], default='simples', max_length=20, verbose_name='Tipo de servico'),
        ),
        migrations.AddField(
            model_name='atendimentocaixabanco',
            name='limite_tempo',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(300)], verbose_name='Limite de tempo (minutos)'),
        ),
    ]
