# Generated by Django 5.2.5 on 2026-01-21 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiscalizacao', '0011_autobanco_campos_lei_filas'),
    ]

    operations = [
        migrations.AddField(
            model_name='autosupermercado',
            name='atuacao',
            field=models.CharField(blank=True, max_length=100, verbose_name='Atua‡Æo'),
        ),
        migrations.AddField(
            model_name='autosupermercado',
            name='porte',
            field=models.CharField(blank=True, choices=[('microempresa', 'Microempresa'), ('pequeno', 'Pequeno Porte'), ('medio', 'Médio Porte'), ('grande', 'Grande Porte')], max_length=100, verbose_name='Porte'),
        ),
        migrations.AddField(
            model_name='autosupermercado',
            name='vicios_aparentes',
            field=models.BooleanField(blank=True, null=True, verbose_name='Todos os vicios estavam aparentes?'),
        ),
    ]
