# Generated by Django 5.2.5 on 2026-01-23 19:13

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiscalizacao', '0012_autosupermercado_atuacao_autosupermercado_porte_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ParecerProcesso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_parecer', models.CharField(blank=True, max_length=20, unique=True, verbose_name='Número do Parecer')),
                ('sintese_fatica', models.TextField(blank=True, verbose_name='I - Síntese Fática')),
                ('parecer', models.TextField(verbose_name='II - Parecer')),
                ('decisao', models.TextField(verbose_name='III - Decisão')),
                ('elaborado_por_nome', models.CharField(blank=True, max_length=255, verbose_name='Elaborado por')),
                ('cargo_elaborador', models.CharField(blank=True, max_length=100, verbose_name='Cargo')),
                ('data_emissao', models.DateField(default=django.utils.timezone.now, verbose_name='Data')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('elaborado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pareceres_processo', to=settings.AUTH_USER_MODEL)),
                ('processo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pareceres', to='fiscalizacao.processo')),
            ],
            options={
                'verbose_name': 'Parecer Técnico do Processo',
                'verbose_name_plural': 'Pareceres Técnicos do Processo',
                'ordering': ['-criado_em'],
                'indexes': [models.Index(fields=['numero_parecer'], name='fiscalizaca_numero__84a0df_idx'), models.Index(fields=['processo'], name='fiscalizaca_process_deb132_idx')],
            },
        ),
    ]
