# Generated by Django 4.2.11 on 2026-01-24 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiscalizacao', '0013_parecerprocesso'),
    ]

    operations = [
        migrations.AddField(
            model_name='autoinfracao',
            name='auto_constatacao_numero',
            field=models.CharField(blank=True, max_length=20, verbose_name='Auto de Constatação Nº'),
        ),
        migrations.AddField(
            model_name='autoinfracao',
            name='cep',
            field=models.CharField(blank=True, max_length=10, verbose_name='CEP'),
        ),
        migrations.AddField(
            model_name='autoinfracao',
            name='notificacao_numero',
            field=models.CharField(blank=True, max_length=20, verbose_name='Notificação Nº'),
        ),
        migrations.AlterField(
            model_name='autoinfracao',
            name='valor_multa',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Valor da multa aplicada', max_digits=12, null=True, verbose_name='Valor da Multa (R$)'),
        ),
    ]
