# Generated by Django 4.2.11 on 2026-01-24 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiscalizacao', '0014_autoinfracao_auto_constatacao_numero_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autoinfracao',
            name='base_legal_cdc',
            field=models.TextField(blank=True, help_text='Artigos do CDC violados', verbose_name='Base Legal CDC'),
        ),
    ]
