# Generated by Django 5.2.5 on 2026-01-24 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiscalizacao', '0015_alter_autoinfracao_base_legal_cdc'),
    ]

    operations = [
        migrations.AddField(
            model_name='autoinfracao',
            name='texto_origem',
            field=models.TextField(blank=True, verbose_name='Texto de Origem'),
        ),
    ]
