# Generated by Django 5.2.5 on 2026-01-26 15:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiscalizacao', '0016_autoinfracao_texto_origem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='autoinfracao',
            name='validacao_formal_motivo',
            field=models.TextField(blank=True, verbose_name='Motivo da Validação Formal'),
        ),
        migrations.AddField(
            model_name='autoinfracao',
            name='validacao_formal_status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('valido', 'Válido'), ('erro', 'Erro Formal')], default='pendente', max_length=20, verbose_name='Validação Formal'),
        ),
        migrations.AddField(
            model_name='autoinfracao',
            name='validado_em',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Validado em'),
        ),
        migrations.AddField(
            model_name='autoinfracao',
            name='validado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='autos_infracao_validados', to=settings.AUTH_USER_MODEL, verbose_name='Validado por'),
        ),
    ]
