# Generated by Django 5.2.5 on 2026-01-26 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiscalizacao', '0017_autoinfracao_validacao_formal_motivo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificacaoeletronica',
            name='tipo_notificacao',
            field=models.CharField(choices=[('auto_infracao', 'Auto de Infração'), ('arquivamento', 'Arquivamento'), ('prazo_vencendo', 'Prazo Vencendo'), ('prazo_vencido', 'Prazo Vencido'), ('defesa_apresentada', 'Defesa Apresentada'), ('recurso_apresentado', 'Recurso Apresentado'), ('decisao_proferida', 'Decisão Proferida')], max_length=20, verbose_name='Tipo de Notificação'),
        ),
    ]
