# Generated by Django 4.2.11 on 2026-01-26 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiscalizacao', '0018_alter_notificacaoeletronica_tipo_notificacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentoprocesso',
            name='tipo',
            field=models.CharField(choices=[('auto_infracao', 'Auto de Infração'), ('defesa', 'Defesa'), ('recurso', 'Recurso'), ('parecer', 'Parecer Técnico'), ('decisao', 'Decisão'), ('outros', 'Outros')], max_length=20, verbose_name='Tipo do Documento'),
        ),
    ]
