# Generated by Django 5.2.5 on 2026-01-28 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiscalizacao', '0019_alter_documentoprocesso_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentoprocesso',
            name='tipo',
            field=models.CharField(choices=[('auto_infracao', 'Auto de Infração'), ('defesa', 'Defesa'), ('recurso', 'Recurso'), ('parecer', 'Parecer Técnico'), ('decisao', 'Decisão'), ('grm', 'Guia de Recolhimento de Multa (GRM)'), ('outros', 'Outros')], max_length=20, verbose_name='Tipo do Documento'),
        ),
    ]
