# Generated by Django 4.2.11 on 2025-09-21 04:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lei',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=50, unique=True, verbose_name='Número da Lei')),
                ('titulo', models.CharField(max_length=255, verbose_name='Título')),
                ('publicada_em', models.DateField(verbose_name='Data de Publicação')),
                ('link', models.URLField(blank=True, verbose_name='Link')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
            ],
            options={
                'verbose_name': 'Lei',
                'verbose_name_plural': 'Leis',
                'ordering': ['-publicada_em', 'numero'],
            },
        ),
        migrations.CreateModel(
            name='Artigo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_artigo', models.CharField(max_length=20, verbose_name='Artigo')),
                ('texto', models.TextField(verbose_name='Texto do Artigo')),
                ('lei', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artigos', to='legislacao.lei')),
            ],
            options={
                'verbose_name': 'Artigo',
                'verbose_name_plural': 'Artigos',
                'ordering': ['lei', 'numero_artigo'],
                'unique_together': {('lei', 'numero_artigo')},
            },
        ),
    ]
