# Generated by Django 5.2.5 on 2025-08-17 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultaPublica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_consultante', models.GenericIPAddressField(verbose_name='IP do Consultante')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('tipo_consulta', models.CharField(choices=[('empresa', 'Empresa'), ('processo', 'Processo'), ('ranking', 'Ranking'), ('precos', 'Preços'), ('restricoes', 'Restrições')], max_length=20, verbose_name='Tipo de Consulta')),
                ('termo_pesquisado', models.CharField(max_length=255, verbose_name='Termo Pesquisado')),
                ('filtros_aplicados', models.TextField(blank=True, help_text='JSON com filtros', verbose_name='Filtros Aplicados')),
                ('resultados_encontrados', models.IntegerField(default=0, verbose_name='Resultados Encontrados')),
                ('tempo_resposta', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='Tempo de Resposta (ms)')),
                ('data_consulta', models.DateTimeField(auto_now_add=True, verbose_name='Data da Consulta')),
                ('sucesso', models.BooleanField(default=True, verbose_name='Consulta com Sucesso')),
                ('erro', models.TextField(blank=True, verbose_name='Erro')),
            ],
            options={
                'verbose_name': 'Consulta Pública',
                'verbose_name_plural': 'Consultas Públicas',
                'ordering': ['-data_consulta'],
                'indexes': [models.Index(fields=['data_consulta'], name='consulta_pu_data_co_2244bf_idx'), models.Index(fields=['tipo_consulta'], name='consulta_pu_tipo_co_b4a906_idx'), models.Index(fields=['ip_consultante'], name='consulta_pu_ip_cons_e72e25_idx')],
            },
        ),
        migrations.CreateModel(
            name='EmpresaPublica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razao_social', models.CharField(max_length=255, verbose_name='Razão Social')),
                ('nome_fantasia', models.CharField(blank=True, max_length=255, verbose_name='Nome Fantasia')),
                ('cnpj', models.CharField(max_length=18, unique=True, verbose_name='CNPJ')),
                ('endereco', models.CharField(max_length=255, verbose_name='Endereço')),
                ('bairro', models.CharField(max_length=100, verbose_name='Bairro')),
                ('cidade', models.CharField(max_length=100, verbose_name='Cidade')),
                ('estado', models.CharField(default='AM', max_length=2, verbose_name='Estado')),
                ('segmento', models.CharField(blank=True, max_length=100, verbose_name='Segmento')),
                ('porte', models.CharField(blank=True, max_length=50, verbose_name='Porte')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('situacao_publica', models.CharField(choices=[('regular', 'Regular'), ('com_restricoes', 'Com Restrições'), ('suspenso', 'Suspenso'), ('inativo', 'Inativo')], default='regular', max_length=20, verbose_name='Situação')),
                ('total_processos', models.IntegerField(default=0, verbose_name='Total de Processos')),
                ('total_multas', models.IntegerField(default=0, verbose_name='Total de Multas')),
                ('valor_total_multas', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Valor Total Multas')),
                ('data_ultima_infracao', models.DateField(blank=True, null=True, verbose_name='Data da Última Infração')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
                ('exibir_detalhes', models.BooleanField(default=True, help_text='Se falso, só mostra dados básicos', verbose_name='Exibir Detalhes')),
            ],
            options={
                'verbose_name': 'Empresa Pública',
                'verbose_name_plural': 'Empresas Públicas',
                'ordering': ['razao_social'],
                'indexes': [models.Index(fields=['cnpj'], name='consulta_pu_cnpj_dc93d4_idx'), models.Index(fields=['razao_social'], name='consulta_pu_razao_s_54f3cb_idx'), models.Index(fields=['situacao_publica'], name='consulta_pu_situaca_ff5162_idx')],
            },
        ),
        migrations.CreateModel(
            name='MonitoramentoPrecos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(choices=[('combustivel', 'Combustível'), ('supermercado', 'Supermercado'), ('farmacia', 'Farmácia'), ('restaurante', 'Restaurante'), ('construcao', 'Material de Construção'), ('outros', 'Outros')], max_length=20, verbose_name='Categoria')),
                ('produto', models.CharField(max_length=200, verbose_name='Produto/Serviço')),
                ('unidade', models.CharField(default='un', max_length=20, verbose_name='Unidade')),
                ('especificacao', models.TextField(blank=True, verbose_name='Especificação')),
                ('preco_minimo', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço Mínimo')),
                ('preco_maximo', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço Máximo')),
                ('preco_medio', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço Médio')),
                ('regiao', models.CharField(max_length=100, verbose_name='Região')),
                ('total_estabelecimentos', models.IntegerField(verbose_name='Total de Estabelecimentos Pesquisados')),
                ('data_pesquisa', models.DateField(verbose_name='Data da Pesquisa')),
                ('periodo_referencia', models.CharField(max_length=20, verbose_name='Período de Referência')),
                ('variacao_percentual', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Variação %')),
                ('preco_anterior', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Preço Anterior')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('publicar', models.BooleanField(default=True, verbose_name='Publicar')),
            ],
            options={
                'verbose_name': 'Monitoramento de Preços',
                'verbose_name_plural': 'Monitoramento de Preços',
                'ordering': ['-data_pesquisa', 'categoria', 'produto'],
                'indexes': [models.Index(fields=['categoria', 'data_pesquisa'], name='consulta_pu_categor_38a63c_idx'), models.Index(fields=['produto'], name='consulta_pu_produto_ab7fc7_idx')],
            },
        ),
        migrations.CreateModel(
            name='ProcessoPublico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_processo', models.CharField(max_length=50, unique=True, verbose_name='Número do Processo')),
                ('empresa_cnpj', models.CharField(max_length=18, verbose_name='CNPJ da Empresa')),
                ('empresa_nome', models.CharField(max_length=255, verbose_name='Nome da Empresa')),
                ('tipo_auto', models.CharField(max_length=50, verbose_name='Tipo de Auto')),
                ('data_auto', models.DateField(verbose_name='Data do Auto')),
                ('local_infracao', models.CharField(blank=True, max_length=255, verbose_name='Local da Infração')),
                ('status_publico', models.CharField(choices=[('em_andamento', 'Em Andamento'), ('finalizado', 'Finalizado'), ('arquivado', 'Arquivado')], max_length=20, verbose_name='Status')),
                ('tem_multa', models.BooleanField(default=False, verbose_name='Tem Multa')),
                ('valor_multa', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Valor da Multa')),
                ('status_multa', models.CharField(blank=True, max_length=20, verbose_name='Status da Multa')),
                ('visivel_publico', models.BooleanField(default=True, verbose_name='Visível ao Público')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
            ],
            options={
                'verbose_name': 'Processo Público',
                'verbose_name_plural': 'Processos Públicos',
                'ordering': ['-data_auto'],
                'indexes': [models.Index(fields=['numero_processo'], name='consulta_pu_numero__10131d_idx'), models.Index(fields=['empresa_cnpj'], name='consulta_pu_empresa_f611bf_idx'), models.Index(fields=['status_publico'], name='consulta_pu_status__c4e915_idx')],
            },
        ),
        migrations.CreateModel(
            name='RankingPublico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_ranking', models.CharField(choices=[('mais_infracoes', 'Empresas com Mais Infrações'), ('maior_valor_multas', 'Maiores Valores em Multas'), ('reincidentes', 'Empresas Reincidentes'), ('por_segmento', 'Ranking por Segmento')], max_length=30, verbose_name='Tipo de Ranking')),
                ('periodo', models.CharField(choices=[('mensal', 'Mensal'), ('trimestral', 'Trimestral'), ('semestral', 'Semestral'), ('anual', 'Anual')], max_length=15, verbose_name='Período')),
                ('data_referencia', models.DateField(verbose_name='Data de Referência')),
                ('dados_ranking', models.TextField(help_text='JSON com dados do ranking', verbose_name='Dados do Ranking')),
                ('total_empresas', models.IntegerField(default=0, verbose_name='Total de Empresas')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('exibir_valores', models.BooleanField(default=True, verbose_name='Exibir Valores')),
                ('limite_posicoes', models.IntegerField(default=50, verbose_name='Limite de Posições')),
                ('gerado_em', models.DateTimeField(auto_now_add=True, verbose_name='Gerado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Ranking Público',
                'verbose_name_plural': 'Rankings Públicos',
                'ordering': ['-data_referencia'],
                'unique_together': {('tipo_ranking', 'periodo', 'data_referencia')},
            },
        ),
        migrations.CreateModel(
            name='RestricaoEmpresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa_cnpj', models.CharField(max_length=18, verbose_name='CNPJ')),
                ('empresa_nome', models.CharField(max_length=255, verbose_name='Nome da Empresa')),
                ('tipo_restricao', models.CharField(choices=[('multa_pendente', 'Multa Pendente'), ('processo_andamento', 'Processo em Andamento'), ('reincidencia', 'Reincidência'), ('suspensao', 'Suspensão Temporária'), ('advertencia', 'Advertência')], max_length=30, verbose_name='Tipo de Restrição')),
                ('descricao', models.TextField(verbose_name='Descrição da Restrição')),
                ('data_restricao', models.DateField(verbose_name='Data da Restrição')),
                ('data_validade', models.DateField(blank=True, null=True, verbose_name='Válida até')),
                ('ativa', models.BooleanField(default=True, verbose_name='Restrição Ativa')),
                ('nivel_severidade', models.CharField(choices=[('baixo', 'Baixo'), ('medio', 'Médio'), ('alto', 'Alto')], default='medio', max_length=10, verbose_name='Nível')),
                ('numero_processo', models.CharField(blank=True, max_length=50, verbose_name='Número do Processo')),
                ('publicar', models.BooleanField(default=True, verbose_name='Publicar')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
            ],
            options={
                'verbose_name': 'Restrição de Empresa',
                'verbose_name_plural': 'Restrições de Empresas',
                'ordering': ['-data_restricao'],
                'indexes': [models.Index(fields=['empresa_cnpj'], name='consulta_pu_empresa_6305d3_idx'), models.Index(fields=['tipo_restricao'], name='consulta_pu_tipo_re_707206_idx'), models.Index(fields=['ativa'], name='consulta_pu_ativa_13177d_idx')],
            },
        ),
    ]
