# Generated by Django 5.2.5 on 2025-08-25 14:12

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoNotificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('descricao', models.TextField(blank=True)),
                ('template_email', models.TextField(blank=True)),
                ('template_sms', models.TextField(blank=True)),
                ('template_push', models.TextField(blank=True)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tipo de Notificação',
                'verbose_name_plural': 'Tipos de Notificação',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Notificacao',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=200)),
                ('mensagem', models.TextField()),
                ('dados_extras', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('enviada', 'Enviada'), ('lida', 'Lida'), ('falhada', 'Falhada'), ('cancelada', 'Cancelada')], default='pendente', max_length=20)),
                ('prioridade', models.CharField(choices=[('baixa', 'Baixa'), ('normal', 'Normal'), ('alta', 'Alta'), ('urgente', 'Urgente')], default='normal', max_length=20)),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('agendada_para', models.DateTimeField(blank=True, null=True)),
                ('enviada_em', models.DateTimeField(blank=True, null=True)),
                ('lida_em', models.DateTimeField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('destinatario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificacoes_recebidas', to=settings.AUTH_USER_MODEL)),
                ('remetente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notificacoes_enviadas', to=settings.AUTH_USER_MODEL)),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notificacoes.tiponotificacao')),
            ],
            options={
                'verbose_name': 'Notificação',
                'verbose_name_plural': 'Notificações',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='LogNotificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('canal', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), ('push', 'Push'), ('sistema', 'Sistema')], max_length=20)),
                ('resultado', models.CharField(choices=[('sucesso', 'Sucesso'), ('falha', 'Falha'), ('pendente', 'Pendente')], max_length=20)),
                ('mensagem_erro', models.TextField(blank=True)),
                ('tentativas', models.PositiveIntegerField(default=0)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('notificacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notificacoes.notificacao')),
            ],
            options={
                'verbose_name': 'Log de Notificação',
                'verbose_name_plural': 'Logs de Notificação',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='TemplateNotificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('canal', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), ('push', 'Push'), ('sistema', 'Sistema')], max_length=20)),
                ('assunto', models.CharField(blank=True, max_length=200)),
                ('conteudo', models.TextField()),
                ('variaveis', models.JSONField(blank=True, default=list, help_text='Lista de variáveis disponíveis no template')),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('tipo_notificacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notificacoes.tiponotificacao')),
            ],
            options={
                'verbose_name': 'Template de Notificação',
                'verbose_name_plural': 'Templates de Notificação',
                'ordering': ['nome'],
                'unique_together': {('tipo_notificacao', 'canal')},
            },
        ),
        migrations.CreateModel(
            name='PreferenciaNotificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('canal', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), ('push', 'Push'), ('sistema', 'Sistema')], max_length=20)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('tipo_notificacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notificacoes.tiponotificacao')),
            ],
            options={
                'verbose_name': 'Preferência de Notificação',
                'verbose_name_plural': 'Preferências de Notificação',
                'ordering': ['usuario', 'tipo_notificacao'],
                'unique_together': {('usuario', 'tipo_notificacao', 'canal')},
            },
        ),
        migrations.AddIndex(
            model_name='notificacao',
            index=models.Index(fields=['destinatario', 'status'], name='notificacoe_destina_c42c7b_idx'),
        ),
        migrations.AddIndex(
            model_name='notificacao',
            index=models.Index(fields=['agendada_para', 'status'], name='notificacoe_agendad_df1392_idx'),
        ),
        migrations.AddIndex(
            model_name='notificacao',
            index=models.Index(fields=['tipo', 'status'], name='notificacoe_tipo_id_80b70d_idx'),
        ),
    ]
