# Generated by Django 5.2.5 on 2025-10-21 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notificacoes', '0002_dispositivonotificacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispositivonotificacao',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
