repos:
  # Python
  - repo: https://github.com/psf/black
    rev: 24.10.0
    hooks:
      - id: black
        language_version: python3
        files: procon_system/.*\.py$

  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort
        files: procon_system/.*\.py$

  - repo: https://github.com/pycqa/flake8
    rev: 7.1.1
    hooks:
      - id: flake8
        files: procon_system/.*\.py$
        args: [--max-line-length=88, --extend-ignore=E203,W503]

  - repo: https://github.com/PyCQA/bandit
    rev: 1.8.0
    hooks:
      - id: bandit
        files: procon_system/.*\.py$
        args: [--skip=B101,B601]

  # JavaScript/TypeScript
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v9.16.0
    hooks:
      - id: eslint
        files: frontend/.*\.(js|jsx|ts|tsx)$
        types: [file]
        additional_dependencies:
          - eslint@^9.0.0
          - '@eslint/js@^9.0.0'

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v4.0.0-alpha.8
    hooks:
      - id: prettier
        files: frontend/.*\.(js|jsx|ts|tsx|json|css|md)$

  # General
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
        exclude: \.md$
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-json
      - id: check-merge-conflict
      - id: check-added-large-files
        args: ['--maxkb=1000']
      - id: detect-private-key
      - id: check-case-conflict

  # Django specific
  - repo: local
    hooks:
      - id: django-check
        name: Django Check
        entry: python procon_system/manage.py check
        language: system
        pass_filenames: false
        files: procon_system/.*\.py$

      - id: django-migrations-check
        name: Django Migrations Check
        entry: python procon_system/manage.py makemigrations --dry-run --check
        language: system
        pass_filenames: false
        files: procon_system/.*(models|migrations).*\.py$