# Generated by Django 5.2.5 on 2025-10-09 14:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AutomationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, verbose_name='Nome da Regra')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='Slug')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('trigger_type', models.CharField(choices=[('EVENTO', 'Evento'), ('AGENDADO', 'Agendado'), ('METRICA', 'Métrica'), ('THRESHOLD', 'Threshold'), ('CUSTOM', 'Customizado')], max_length=20, verbose_name='Tipo de Trigger')),
                ('trigger_config', models.JSONField(blank=True, default=dict, verbose_name='Configuração do Trigger')),
                ('action_type', models.CharField(choices=[('EMAIL', 'Notificação por E-mail'), ('WEBHOOK', 'Webhook Externo'), ('TASK', 'Tarefa Interna'), ('ALERTA', 'Alerta do Sistema'), ('SCRIPT', 'Script Personalizado')], max_length=20, verbose_name='Tipo de Ação')),
                ('action_config', models.JSONField(blank=True, default=dict, verbose_name='Configuração da Ação')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('prioridade', models.IntegerField(default=0, verbose_name='Prioridade')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('criado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='regras_automatizadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Regra de Automação',
                'verbose_name_plural': 'Regras de Automação',
                'ordering': ['-ativo', '-prioridade', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='AutomationRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('EXECUTANDO', 'Executando'), ('SUCESSO', 'Sucesso'), ('FALHA', 'Falha'), ('IGNORADA', 'Ignorada')], default='PENDENTE', max_length=12, verbose_name='Status')),
                ('disparado_em', models.DateTimeField(auto_now_add=True, verbose_name='Disparado em')),
                ('finalizado_em', models.DateTimeField(blank=True, null=True, verbose_name='Finalizado em')),
                ('entrada', models.JSONField(blank=True, default=dict, verbose_name='Dados de Entrada')),
                ('resultado', models.JSONField(blank=True, default=dict, verbose_name='Resultado')),
                ('mensagem_erro', models.TextField(blank=True, verbose_name='Mensagem de Erro')),
                ('executado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='execucoes_automatizadas', to=settings.AUTH_USER_MODEL)),
                ('regra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='execucoes', to='automated_intelligence.automationrule')),
            ],
            options={
                'verbose_name': 'Execução de Automação',
                'verbose_name_plural': 'Execuções de Automação',
                'ordering': ['-disparado_em'],
                'indexes': [models.Index(fields=['regra', '-disparado_em'], name='automated_i_regra_i_19799c_idx'), models.Index(fields=['status'], name='automated_i_status_48808d_idx')],
            },
        ),
        migrations.CreateModel(
            name='InsightTrigger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150, verbose_name='Título')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('dados_relacionados', models.JSONField(blank=True, default=dict, verbose_name='Dados Relacionados')),
                ('severidade', models.CharField(choices=[('LOW', 'Baixa'), ('MEDIUM', 'Média'), ('HIGH', 'Alta'), ('CRITICAL', 'Crítica')], default='LOW', max_length=10, verbose_name='Severidade')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('reconhecido', models.BooleanField(default=False, verbose_name='Reconhecido')),
                ('reconhecido_em', models.DateTimeField(blank=True, null=True, verbose_name='Reconhecido em')),
                ('reconhecido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='insights_reconhecidos', to=settings.AUTH_USER_MODEL)),
                ('regra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insights', to='automated_intelligence.automationrule')),
            ],
            options={
                'verbose_name': 'Insight de Automação',
                'verbose_name_plural': 'Insights de Automação',
                'ordering': ['-criado_em'],
                'indexes': [models.Index(fields=['regra', 'severidade'], name='automated_i_regra_i_f2d3af_idx'), models.Index(fields=['reconhecido', 'severidade'], name='automated_i_reconhe_aff797_idx')],
            },
        ),
    ]
