# Generated by Django 4.2.11 on 2025-10-23 18:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcedimentoPreAdministrativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('numero', models.CharField(blank=True, max_length=20, unique=True, verbose_name='Número do PPA')),
                ('sigla', models.CharField(choices=[('BANCO', 'Banco'), ('POSTO', 'Posto de Combustível'), ('SUPERMERCADO', 'Supermercado'), ('DIVERSOS', 'Diversos'), ('TELECOMUNICACOES', 'Telecomunicações'), ('ENERGIA', 'Energia'), ('PLANO_SAUDE', 'Plano de Saúde'), ('OUTROS', 'Outros')], max_length=50, verbose_name='Sigla/Tipo')),
                ('assunto', models.TextField(verbose_name='Assunto')),
                ('interessado', models.CharField(max_length=255, verbose_name='Interessado (Empresa)')),
                ('cnpj_interessado', models.CharField(blank=True, max_length=18, verbose_name='CNPJ')),
                ('endereco_interessado', models.TextField(blank=True, verbose_name='Endereço')),
                ('status', models.CharField(choices=[('criado', 'Criado'), ('em_analise', 'Em Análise'), ('notificado', 'Notificado'), ('aguardando_resposta', 'Aguardando Resposta'), ('com_defesa', 'Com Defesa'), ('parecer_elaborado', 'Parecer Elaborado'), ('concluido', 'Concluído'), ('arquivado', 'Arquivado')], default='criado', max_length=30, verbose_name='Status')),
                ('decisao_final', models.CharField(choices=[('pendente', 'Pendente'), ('arquivado', 'Arquivado - Sem Fundamento'), ('auto_criado', 'Auto de Infração Criado'), ('encaminhado', 'Encaminhado para Outro Órgão')], default='pendente', max_length=20, verbose_name='Decisão Final')),
                ('prazo_analise', models.DateField(blank=True, null=True, verbose_name='Prazo para Análise')),
                ('prazo_resposta', models.DateField(blank=True, null=True, verbose_name='Prazo para Resposta Empresa')),
                ('data_conclusao', models.DateTimeField(blank=True, null=True, verbose_name='Data de Conclusão')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações Gerais')),
                ('observacoes_internas', models.TextField(blank=True, verbose_name='Observações Internas')),
                ('fundamentacao_decisao', models.TextField(blank=True, verbose_name='Fundamentação da Decisão')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('analista_responsavel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ppas_responsavel', to=settings.AUTH_USER_MODEL, verbose_name='Analista Responsável')),
                ('criado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ppas_criados', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('supervisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ppas_supervisionados', to=settings.AUTH_USER_MODEL, verbose_name='Supervisor')),
            ],
            options={
                'verbose_name': 'PPA - Procedimento Pré-Administrativo',
                'verbose_name_plural': 'PPAs - Procedimentos Pré-Administrativos',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='ParecerPPA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_parecer', models.CharField(blank=True, max_length=50, verbose_name='Número do Parecer')),
                ('titulo', models.CharField(max_length=300, verbose_name='Título')),
                ('relatorio', models.TextField(verbose_name='Relatório')),
                ('fundamentacao', models.TextField(verbose_name='Fundamentação Legal')),
                ('conclusao', models.CharField(choices=[('procedente', 'Procedente - Criar AI'), ('improcedente', 'Improcedente - Arquivar'), ('mais_informacoes', 'Necessita Mais Informações'), ('encaminhar', 'Encaminhar para Outro Órgão')], max_length=30, verbose_name='Conclusão')),
                ('recomendacoes', models.TextField(blank=True, verbose_name='Recomendações')),
                ('cargo_elaborador', models.CharField(blank=True, max_length=100, verbose_name='Cargo')),
                ('data_aprovacao', models.DateTimeField(blank=True, null=True, verbose_name='Data de Aprovação')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('aprovado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pareceres_ppa_aprovados', to=settings.AUTH_USER_MODEL, verbose_name='Aprovado por')),
                ('elaborado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pareceres_ppa_elaborados', to=settings.AUTH_USER_MODEL, verbose_name='Elaborado por')),
                ('ppa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pareceres', to='ppa.procedimentopreadministrativo', verbose_name='PPA')),
            ],
            options={
                'verbose_name': 'Parecer de PPA',
                'verbose_name_plural': 'Pareceres de PPA',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='MovimentacaoPPA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(default=django.utils.timezone.now, verbose_name='Data')),
                ('hora', models.TimeField(blank=True, null=True, verbose_name='Hora')),
                ('tipo_movimentacao', models.CharField(choices=[('criacao', 'Criação do PPA'), ('anexo_ac', 'Anexo de Auto de Constatação'), ('anexo_ai', 'Anexo de Auto de Infração'), ('anexo_notificacao', 'Anexo de Notificação'), ('anexo_defesa', 'Anexo de Defesa'), ('anexo_parecer', 'Anexo de Parecer'), ('anexo_documento', 'Anexo de Documento'), ('mudanca_status', 'Mudança de Status'), ('observacao', 'Observação'), ('analise', 'Análise'), ('decisao', 'Decisão'), ('outros', 'Outros')], default='outros', max_length=30, verbose_name='Tipo de Movimentação')),
                ('atendimento', models.TextField(verbose_name='Atendimento/Descrição')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('ppa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimentacoes', to='ppa.procedimentopreadministrativo', verbose_name='PPA')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Movimentação de PPA',
                'verbose_name_plural': 'Movimentações de PPA',
                'ordering': ['data', 'hora', '-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='AnexoPPA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_documento', models.CharField(choices=[('AC', 'Auto de Constatação'), ('AI', 'Auto de Infração'), ('NOT', 'Notificação'), ('DEFESA', 'Defesa'), ('PARECER', 'Parecer'), ('RESPOSTA', 'Resposta da Empresa'), ('DOCUMENTO', 'Documento Complementar'), ('IMAGEM', 'Imagem/Foto'), ('COMPROVANTE', 'Comprovante'), ('OUTROS', 'Outros')], max_length=20, verbose_name='Tipo de Documento')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('arquivo', models.FileField(blank=True, null=True, upload_to='ppa/anexos/%Y/%m/', verbose_name='Arquivo')),
                ('nome_arquivo_original', models.CharField(blank=True, max_length=255, verbose_name='Nome Original')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('numero_documento', models.CharField(blank=True, max_length=50, verbose_name='Número do Documento')),
                ('data_anexacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Anexação')),
                ('anexado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Anexado por')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('ppa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anexos', to='ppa.procedimentopreadministrativo', verbose_name='PPA')),
            ],
            options={
                'verbose_name': 'Anexo de PPA',
                'verbose_name_plural': 'Anexos de PPA',
                'ordering': ['-data_anexacao'],
            },
        ),
        migrations.AddIndex(
            model_name='procedimentopreadministrativo',
            index=models.Index(fields=['numero'], name='ppa_procedi_numero_f3962f_idx'),
        ),
        migrations.AddIndex(
            model_name='procedimentopreadministrativo',
            index=models.Index(fields=['status'], name='ppa_procedi_status_f98f88_idx'),
        ),
        migrations.AddIndex(
            model_name='procedimentopreadministrativo',
            index=models.Index(fields=['analista_responsavel'], name='ppa_procedi_analist_83f373_idx'),
        ),
        migrations.AddIndex(
            model_name='procedimentopreadministrativo',
            index=models.Index(fields=['sigla'], name='ppa_procedi_sigla_450228_idx'),
        ),
        migrations.AddIndex(
            model_name='procedimentopreadministrativo',
            index=models.Index(fields=['criado_em'], name='ppa_procedi_criado__04c71c_idx'),
        ),
        migrations.AddIndex(
            model_name='movimentacaoppa',
            index=models.Index(fields=['ppa', 'data'], name='ppa_movimen_ppa_id_f3541b_idx'),
        ),
        migrations.AddIndex(
            model_name='movimentacaoppa',
            index=models.Index(fields=['tipo_movimentacao'], name='ppa_movimen_tipo_mo_3ee02d_idx'),
        ),
        migrations.AddIndex(
            model_name='anexoppa',
            index=models.Index(fields=['ppa', 'tipo_documento'], name='ppa_anexopp_ppa_id_9ff264_idx'),
        ),
        migrations.AddIndex(
            model_name='anexoppa',
            index=models.Index(fields=['data_anexacao'], name='ppa_anexopp_data_an_d5c99a_idx'),
        ),
    ]
