# Generated by Django 5.2.5 on 2025-11-10 14:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ppa', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimentacaoppa',
            name='data',
            field=models.DateField(default=django.utils.timezone.localdate, verbose_name='Data'),
        ),
    ]
