# Generated by Django 5.2.5 on 2025-11-27 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ppa', '0002_alter_movimentacaoppa_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='parecerppa',
            name='sintese_fatica',
            field=models.TextField(blank=True, help_text='Relato cronológico completo dos fatos do caso', verbose_name='I - Síntese Fática'),
        ),
        migrations.AlterField(
            model_name='parecerppa',
            name='conclusao',
            field=models.CharField(choices=[('procedente', 'Procedente - Criar AI'), ('improcedente', 'Improcedente - Arquivar'), ('mais_informacoes', 'Necessita Mais Informações'), ('encaminhar', 'Encaminhar para Outro Órgão')], max_length=30, verbose_name='III - Decisão'),
        ),
        migrations.AlterField(
            model_name='parecerppa',
            name='relatorio',
            field=models.TextField(help_text='Análise jurídica e técnica do caso', verbose_name='II - Parecer'),
        ),
    ]
