# Generated by Django 4.2.11 on 2025-09-21 04:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import protocolo.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoProtocolo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('formato_numero', models.CharField(default='PROT-{ANO}-{SEQUENCIAL}', max_length=50, verbose_name='Formato do Número')),
                ('prefixo_ano', models.CharField(default='', max_length=10, verbose_name='Prefixo do Ano')),
                ('sequencial_ano', models.BooleanField(default=True, verbose_name='Sequencial por Ano')),
                ('sequencial_geral', models.BooleanField(default=False, verbose_name='Sequencial Geral')),
                ('workflow_automatico', models.BooleanField(default=True, verbose_name='Workflow Automático')),
                ('notificar_responsavel', models.BooleanField(default=True, verbose_name='Notificar Responsável')),
                ('notificar_criador', models.BooleanField(default=True, verbose_name='Notificar Criador')),
                ('tamanho_maximo_mb', models.IntegerField(default=10, verbose_name='Tamanho Máximo (MB)')),
                ('tipos_permitidos', models.TextField(default='pdf,doc,docx,jpg,jpeg,png,txt', verbose_name='Tipos Permitidos')),
                ('max_documentos', models.IntegerField(default=10, verbose_name='Máximo de Documentos')),
                ('prazo_padrao_dias', models.IntegerField(default=30, verbose_name='Prazo Padrão (dias)')),
                ('alerta_vencimento_dias', models.IntegerField(default=3, verbose_name='Alerta Vencimento (dias)')),
            ],
            options={
                'verbose_name': 'Configuração do Protocolo',
                'verbose_name_plural': 'Configurações do Protocolo',
            },
        ),
        migrations.CreateModel(
            name='Protocolo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(blank=True, max_length=50, unique=True, verbose_name='Número do Protocolo')),
                ('assunto', models.CharField(max_length=200, verbose_name='Assunto')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('prioridade', models.CharField(choices=[('BAIXA', 'Baixa'), ('NORMAL', 'Normal'), ('ALTA', 'Alta'), ('URGENTE', 'Urgente')], default='NORMAL', max_length=10, verbose_name='Prioridade')),
                ('data_abertura', models.DateTimeField(auto_now_add=True, verbose_name='Data de Abertura')),
                ('data_limite', models.DateTimeField(blank=True, null=True, verbose_name='Data Limite')),
                ('data_conclusao', models.DateTimeField(blank=True, null=True, verbose_name='Data de Conclusão')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('tags', models.JSONField(blank=True, default=list, verbose_name='Tags')),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='protocolos_criados', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('responsavel_atual', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Responsável Atual')),
            ],
            options={
                'verbose_name': 'Protocolo',
                'verbose_name_plural': 'Protocolos',
                'ordering': ['-data_abertura'],
            },
        ),
        migrations.CreateModel(
            name='StatusProtocolo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('cor', models.CharField(default='#007bff', max_length=7, verbose_name='Cor (hex)')),
                ('ordem', models.IntegerField(default=0, verbose_name='Ordem')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Status de Protocolo',
                'verbose_name_plural': 'Status de Protocolo',
                'ordering': ['ordem'],
            },
        ),
        migrations.CreateModel(
            name='TipoProtocolo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('tipo', models.CharField(choices=[('DENUNCIA', 'Denúncia'), ('RECLAMACAO', 'Reclamação'), ('CONSULTA', 'Consulta'), ('PETICAO', 'Petição'), ('RECURSO', 'Recurso'), ('OUTROS', 'Outros')], max_length=20, verbose_name='Tipo')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('prazo_padrao', models.IntegerField(default=30, verbose_name='Prazo Padrão (dias)')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
            ],
            options={
                'verbose_name': 'Tipo de Protocolo',
                'verbose_name_plural': 'Tipos de Protocolo',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='TramitacaoProtocolo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observacao', models.TextField(blank=True, verbose_name='Observação')),
                ('data_tramitacao', models.DateTimeField(auto_now_add=True, verbose_name='Data da Tramitação')),
                ('protocolo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tramitacoes', to='protocolo.protocolo', verbose_name='Protocolo')),
                ('responsavel_anterior', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tramitacoes_anterior', to=settings.AUTH_USER_MODEL, verbose_name='Responsável Anterior')),
                ('responsavel_novo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tramitacoes_novo', to=settings.AUTH_USER_MODEL, verbose_name='Responsável Novo')),
                ('tramitado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Tramitado por')),
            ],
            options={
                'verbose_name': 'Tramitação de Protocolo',
                'verbose_name_plural': 'Tramitações de Protocolo',
                'ordering': ['-data_tramitacao'],
            },
        ),
        migrations.AddField(
            model_name='protocolo',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='protocolo.statusprotocolo', verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='protocolo',
            name='tipo_protocolo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='protocolo.tipoprotocolo', verbose_name='Tipo'),
        ),
        migrations.CreateModel(
            name='DocumentoProtocolo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('PETICAO', 'Petição'), ('DOCUMENTO', 'Documento'), ('COMPROVANTE', 'Comprovante'), ('RESPOSTA', 'Resposta'), ('OUTROS', 'Outros')], default='DOCUMENTO', max_length=20, verbose_name='Tipo')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('arquivo', models.FileField(upload_to=protocolo.models.documento_upload_path, verbose_name='Arquivo')),
                ('tamanho', models.BigIntegerField(default=0, verbose_name='Tamanho (bytes)')),
                ('extensao', models.CharField(blank=True, max_length=10, verbose_name='Extensão')),
                ('texto_extraido', models.TextField(blank=True, verbose_name='Texto Extraído (OCR)')),
                ('indexado', models.BooleanField(default=False, verbose_name='Indexado')),
                ('validado', models.BooleanField(default=False, verbose_name='Validado')),
                ('data_validacao', models.DateTimeField(blank=True, null=True, verbose_name='Data de Validação')),
                ('observacoes_validacao', models.TextField(blank=True, verbose_name='Observações da Validação')),
                ('data_upload', models.DateTimeField(auto_now_add=True, verbose_name='Data de Upload')),
                ('enviado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documentos_enviados', to=settings.AUTH_USER_MODEL, verbose_name='Enviado por')),
                ('protocolo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='protocolo.protocolo', verbose_name='Protocolo')),
                ('validado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos_validados', to=settings.AUTH_USER_MODEL, verbose_name='Validado por')),
            ],
            options={
                'verbose_name': 'Documento do Protocolo',
                'verbose_name_plural': 'Documentos do Protocolo',
                'ordering': ['-data_upload'],
            },
        ),
        migrations.CreateModel(
            name='AlertaProtocolo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('PRAZO', 'Prazo'), ('TRAMITACAO', 'Tramitação'), ('DOCUMENTO', 'Documento'), ('SISTEMA', 'Sistema')], max_length=20, verbose_name='Tipo')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('mensagem', models.TextField(verbose_name='Mensagem')),
                ('lido', models.BooleanField(default=False, verbose_name='Lido')),
                ('data_leitura', models.DateTimeField(blank=True, null=True, verbose_name='Data de Leitura')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('lido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Lido por')),
                ('protocolo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertas', to='protocolo.protocolo', verbose_name='Protocolo')),
            ],
            options={
                'verbose_name': 'Alerta de Protocolo',
                'verbose_name_plural': 'Alertas de Protocolo',
                'ordering': ['-criado_em'],
            },
        ),
    ]
