# Generated by Django 4.2.11 on 2025-08-26 01:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import protocolo.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('protocolo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatusProtocolo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('cor', models.CharField(default='#007bff', max_length=7, verbose_name='Cor (hex)')),
                ('ordem', models.IntegerField(default=0, verbose_name='Ordem')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Status de Protocolo',
                'verbose_name_plural': 'Status de Protocolo',
                'ordering': ['ordem'],
            },
        ),
        migrations.CreateModel(
            name='TipoProtocolo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('tipo', models.CharField(choices=[('DENUNCIA', 'Denúncia'), ('RECLAMACAO', 'Reclamação'), ('CONSULTA', 'Consulta'), ('PETICAO', 'Petição'), ('RECURSO', 'Recurso'), ('OUTROS', 'Outros')], max_length=20, verbose_name='Tipo')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('prazo_padrao', models.IntegerField(default=30, verbose_name='Prazo Padrão (dias)')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
            ],
            options={
                'verbose_name': 'Tipo de Protocolo',
                'verbose_name_plural': 'Tipos de Protocolo',
                'ordering': ['nome'],
            },
        ),
        migrations.AlterModelOptions(
            name='protocolo',
            options={'ordering': ['-data_abertura'], 'verbose_name': 'Protocolo', 'verbose_name_plural': 'Protocolos'},
        ),
        migrations.RenameField(
            model_name='protocolo',
            old_name='data',
            new_name='data_abertura',
        ),
        migrations.AddField(
            model_name='protocolo',
            name='ativo',
            field=models.BooleanField(default=True, verbose_name='Ativo'),
        ),
        migrations.AddField(
            model_name='protocolo',
            name='criado_por',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='protocolos_criados', to=settings.AUTH_USER_MODEL, verbose_name='Criado por'),
        ),
        migrations.AddField(
            model_name='protocolo',
            name='data_conclusao',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data de Conclusão'),
        ),
        migrations.AddField(
            model_name='protocolo',
            name='data_limite',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data Limite'),
        ),
        migrations.AddField(
            model_name='protocolo',
            name='descricao',
            field=models.TextField(blank=True, verbose_name='Descrição'),
        ),
        migrations.AddField(
            model_name='protocolo',
            name='observacoes',
            field=models.TextField(blank=True, verbose_name='Observações'),
        ),
        migrations.AddField(
            model_name='protocolo',
            name='prioridade',
            field=models.CharField(choices=[('BAIXA', 'Baixa'), ('NORMAL', 'Normal'), ('ALTA', 'Alta'), ('URGENTE', 'Urgente')], default='NORMAL', max_length=10, verbose_name='Prioridade'),
        ),
        migrations.AddField(
            model_name='protocolo',
            name='responsavel_atual',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Responsável Atual'),
        ),
        migrations.AddField(
            model_name='protocolo',
            name='tags',
            field=models.JSONField(blank=True, default=list, verbose_name='Tags'),
        ),
        migrations.CreateModel(
            name='TramitacaoProtocolo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('data_tramitacao', models.DateTimeField(auto_now_add=True, verbose_name='Data da Tramitação')),
                ('protocolo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tramitacoes', to='protocolo.protocolo', verbose_name='Protocolo')),
                ('responsavel_anterior', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tramitacoes_responsavel_anterior', to=settings.AUTH_USER_MODEL, verbose_name='Responsável Anterior')),
                ('responsavel_novo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tramitacoes_responsavel_novo', to=settings.AUTH_USER_MODEL, verbose_name='Responsável Novo')),
                ('status_anterior', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tramitacoes_anteriores', to='protocolo.statusprotocolo', verbose_name='Status Anterior')),
                ('status_novo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tramitacoes_novas', to='protocolo.statusprotocolo', verbose_name='Status Novo')),
                ('tramitado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Tramitado por')),
            ],
            options={
                'verbose_name': 'Tramitação de Protocolo',
                'verbose_name_plural': 'Tramitações de Protocolo',
                'ordering': ['-data_tramitacao'],
            },
        ),
        migrations.CreateModel(
            name='DocumentoProtocolo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('PETICAO', 'Petição'), ('DOCUMENTO', 'Documento'), ('COMPROVANTE', 'Comprovante'), ('RESPOSTA', 'Resposta'), ('OUTROS', 'Outros')], default='DOCUMENTO', max_length=20, verbose_name='Tipo')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('arquivo', models.FileField(upload_to=protocolo.models.documento_upload_path, verbose_name='Arquivo')),
                ('tamanho', models.BigIntegerField(default=0, verbose_name='Tamanho (bytes)')),
                ('extensao', models.CharField(blank=True, max_length=10, verbose_name='Extensão')),
                ('texto_extraido', models.TextField(blank=True, verbose_name='Texto Extraído (OCR)')),
                ('indexado', models.BooleanField(default=False, verbose_name='Indexado')),
                ('data_upload', models.DateTimeField(auto_now_add=True, verbose_name='Data de Upload')),
                ('enviado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Enviado por')),
                ('protocolo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='protocolo.protocolo', verbose_name='Protocolo')),
            ],
            options={
                'verbose_name': 'Documento do Protocolo',
                'verbose_name_plural': 'Documentos do Protocolo',
                'ordering': ['-data_upload'],
            },
        ),
        migrations.CreateModel(
            name='AlertaProtocolo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('PRAZO', 'Prazo'), ('ATRASO', 'Atraso'), ('TRAMITACAO', 'Tramitação'), ('DOCUMENTO', 'Documento'), ('OUTROS', 'Outros')], max_length=20, verbose_name='Tipo')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('mensagem', models.TextField(verbose_name='Mensagem')),
                ('nivel', models.CharField(choices=[('INFO', 'Informação'), ('AVISO', 'Aviso'), ('URGENTE', 'Urgente')], default='INFO', max_length=20, verbose_name='Nível')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('data_leitura', models.DateTimeField(blank=True, null=True, verbose_name='Data de Leitura')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('lido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Lido por')),
                ('protocolo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertas', to='protocolo.protocolo', verbose_name='Protocolo')),
            ],
            options={
                'verbose_name': 'Alerta de Protocolo',
                'verbose_name_plural': 'Alertas de Protocolo',
                'ordering': ['-data_criacao'],
            },
        ),
        migrations.AddField(
            model_name='protocolo',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='protocolo.statusprotocolo', verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='protocolo',
            name='tipo_protocolo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='protocolo.tipoprotocolo', verbose_name='Tipo'),
        ),
    ]
