# Generated by Django 5.2.1 on 2025-08-29 13:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protocolo', '0002_statusprotocolo_tipoprotocolo_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoProtocolo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('formato_numero', models.CharField(default='PROT-{ANO}-{SEQUENCIAL}', max_length=50, verbose_name='Formato do Número')),
                ('prefixo_ano', models.CharField(default='', max_length=10, verbose_name='Prefixo do Ano')),
                ('sequencial_ano', models.BooleanField(default=True, verbose_name='Sequencial por Ano')),
                ('sequencial_geral', models.BooleanField(default=False, verbose_name='Sequencial Geral')),
                ('workflow_automatico', models.BooleanField(default=True, verbose_name='Workflow Automático')),
                ('notificar_responsavel', models.BooleanField(default=True, verbose_name='Notificar Responsável')),
                ('notificar_criador', models.BooleanField(default=True, verbose_name='Notificar Criador')),
                ('tamanho_maximo_mb', models.IntegerField(default=10, verbose_name='Tamanho Máximo (MB)')),
                ('tipos_permitidos', models.TextField(default='pdf,doc,docx,jpg,jpeg,png,txt', verbose_name='Tipos Permitidos')),
                ('max_documentos', models.IntegerField(default=10, verbose_name='Máximo de Documentos')),
                ('prazo_padrao_dias', models.IntegerField(default=30, verbose_name='Prazo Padrão (dias)')),
                ('alerta_vencimento_dias', models.IntegerField(default=3, verbose_name='Alerta Vencimento (dias)')),
            ],
            options={
                'verbose_name': 'Configuração do Protocolo',
                'verbose_name_plural': 'Configurações do Protocolo',
            },
        ),
        migrations.AlterModelOptions(
            name='alertaprotocolo',
            options={'ordering': ['-criado_em'], 'verbose_name': 'Alerta de Protocolo', 'verbose_name_plural': 'Alertas de Protocolo'},
        ),
        migrations.RemoveField(
            model_name='alertaprotocolo',
            name='ativo',
        ),
        migrations.RemoveField(
            model_name='alertaprotocolo',
            name='data_criacao',
        ),
        migrations.RemoveField(
            model_name='alertaprotocolo',
            name='nivel',
        ),
        migrations.RemoveField(
            model_name='tramitacaoprotocolo',
            name='observacoes',
        ),
        migrations.RemoveField(
            model_name='tramitacaoprotocolo',
            name='status_anterior',
        ),
        migrations.RemoveField(
            model_name='tramitacaoprotocolo',
            name='status_novo',
        ),
        migrations.AddField(
            model_name='alertaprotocolo',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Criado em'),
        ),
        migrations.AddField(
            model_name='alertaprotocolo',
            name='lido',
            field=models.BooleanField(default=False, verbose_name='Lido'),
        ),
        migrations.AddField(
            model_name='documentoprotocolo',
            name='data_validacao',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data de Validação'),
        ),
        migrations.AddField(
            model_name='documentoprotocolo',
            name='observacoes_validacao',
            field=models.TextField(blank=True, verbose_name='Observações da Validação'),
        ),
        migrations.AddField(
            model_name='documentoprotocolo',
            name='validado',
            field=models.BooleanField(default=False, verbose_name='Validado'),
        ),
        migrations.AddField(
            model_name='documentoprotocolo',
            name='validado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos_validados', to=settings.AUTH_USER_MODEL, verbose_name='Validado por'),
        ),
        migrations.AddField(
            model_name='tramitacaoprotocolo',
            name='observacao',
            field=models.TextField(blank=True, verbose_name='Observação'),
        ),
        migrations.AlterField(
            model_name='alertaprotocolo',
            name='tipo',
            field=models.CharField(choices=[('PRAZO', 'Prazo'), ('TRAMITACAO', 'Tramitação'), ('DOCUMENTO', 'Documento'), ('SISTEMA', 'Sistema')], max_length=20, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='documentoprotocolo',
            name='enviado_por',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documentos_enviados', to=settings.AUTH_USER_MODEL, verbose_name='Enviado por'),
        ),
        migrations.AlterField(
            model_name='protocolo',
            name='numero',
            field=models.CharField(blank=True, max_length=50, unique=True, verbose_name='Número do Protocolo'),
        ),
        migrations.AlterField(
            model_name='tramitacaoprotocolo',
            name='responsavel_anterior',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tramitacoes_anterior', to=settings.AUTH_USER_MODEL, verbose_name='Responsável Anterior'),
        ),
        migrations.AlterField(
            model_name='tramitacaoprotocolo',
            name='responsavel_novo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tramitacoes_novo', to=settings.AUTH_USER_MODEL, verbose_name='Responsável Novo'),
        ),
    ]
