# Generated by Django 5.2.5 on 2025-10-14 17:42

import datetime
import django.core.validators
import django.db.models.deletion
import portal_consumidor.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentosPortal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('tipo_documento', models.CharField(choices=[('CIP_RESPONDIDA', 'CIP Respondida pela Empresa'), ('ACORDO_REALIZADO', 'Acordo Realizado'), ('AUDIENCIA_AGENDADA', 'Audência Agendada'), ('DECISAO_FINAL', 'Decisão Final'), ('ORIENTACAO', 'Orientações'), ('PROTOCOLO_RESPOSTA', 'Resposta ao Protocolo')], max_length=30)),
                ('visibilidade', models.CharField(choices=[('PUBLICO', 'Público'), ('CONSUMIDOR_LOGOUT', 'Consumidor Deslogado'), ('CONSUMIDOR_LOGADO', 'Consumidor Logado'), ('RESTRITO', 'Restrito')], default='PUBLICO', max_length=20)),
                ('titulo_template', models.CharField(max_length=200)),
                ('conteudo_template', models.TextField()),
                ('placeholder_formats', models.JSONField(default=list)),
                ('mostrar_data', models.BooleanField(default=True)),
                ('mostrar_protocolo', models.BooleanField(default=True)),
                ('permitir_download', models.BooleanField(default=True)),
                ('aplicar_watermark', models.BooleanField(default=False)),
                ('categoria', models.CharField(blank=True, max_length=50)),
                ('ordem_exibicao', models.PositiveIntegerField(default=0)),
                ('ativo', models.BooleanField(default=True)),
                ('exigir_validacao_codigo', models.BooleanField(default=False)),
                ('codigo_acesso_padrao', models.CharField(blank=True, max_length=20)),
            ],
            options={
                'verbose_name': 'Documento do Portal',
                'verbose_name_plural': 'Documentos do Portal',
                'ordering': ['categoria', 'ordem_exibicao', 'tipo_documento'],
            },
        ),
        migrations.CreateModel(
            name='NotificacaoConsumidor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('consumidor_email', models.EmailField(max_length=254)),
                ('consumidor_telefone', models.CharField(blank=True, max_length=20)),
                ('consumidor_cpf', models.CharField(blank=True, max_length=15)),
                ('titulo', models.CharField(max_length=150)),
                ('mensagem', models.TextField()),
                ('canal_escolhido', models.CharField(choices=[('EMAIL', 'E-mail'), ('SMS', 'SMS'), ('WHATSAPP', 'WhatsApp'), ('TELEGRAM', 'Telegram'), ('NOTIFICACAO_SITE', 'Notificação no Site'), ('PUSH_MOBILE', 'Push Mobile')], default='EMAIL', max_length=20)),
                ('prioridade', models.CharField(choices=[('BAIXA', 'Baixa'), ('NORMAL', 'Normal'), ('ALTA', 'Alta'), ('CRTICA', 'Crítica')], default='NORMAL', max_length=10)),
                ('protocolo_relacionado', models.CharField(blank=True, max_length=50)),
                ('tipo_reclamacao_relacionada', models.CharField(blank=True, max_length=50)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_envio_programada', models.DateTimeField(blank=True, null=True)),
                ('data_envio_real', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('AGUARDANDO', 'Aguardando'), ('ENVIANDO', 'Enviando'), ('ENVIADA', 'Enviada'), ('FALHA_ENVIO', 'Falha no Envio'), ('ENTREGA_CONFIRMADA', 'Entrega Confirmada'), ('CANCELADA', 'Cancelada')], default='AGUARDANDO', max_length=20)),
                ('tentativas_envio', models.PositiveIntegerField(default=0)),
                ('maximo_tentativas', models.PositiveIntegerField(default=3)),
                ('codigo_entrega', models.CharField(blank=True, max_length=100)),
                ('detalhes_entrega', models.JSONField(default=dict)),
                ('erro_envio', models.TextField(blank=True)),
                ('data_leitura', models.DateTimeField(blank=True, null=True)),
                ('data_interacao', models.DateTimeField(blank=True, null=True)),
                ('tipo_interacao', models.CharField(blank=True, choices=[('CLICOU_LINK', 'Clicou no Link'), ('ABRIU_DOCUMENTO', 'Abriu Documento'), ('RESPONDEU_MENSAGEM', 'Respondeu Mensagem'), ('OUTROS', 'Outros')], max_length=30)),
            ],
            options={
                'verbose_name': 'Notificação do Consumidor',
                'verbose_name_plural': 'Notificações do Consumidor',
                'ordering': ['-data_criacao'],
            },
        ),
        migrations.CreateModel(
            name='SessaoConsulta',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token_consulta', models.CharField(max_length=100, unique=True)),
                ('tipo_consulta', models.CharField(choices=[('PROTOCOLO', 'Por Número de Protocolo'), ('CPF', 'Por CPF'), ('EMAIL', 'Por E-mail'), ('RECLAMACAO', 'Por Tipo de Reclamação'), ('STATUS', 'Por Status')], default='PROTOCOLO', max_length=20)),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField(blank=True)),
                ('localizacao', models.JSONField(default=dict)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_expiracao', models.DateTimeField()),
                ('status', models.CharField(choices=[('ATIVA', 'Ativa'), ('EXPIRADA', 'Expirada'), ('LIMITADA', 'Limitada'), ('BLOQUEADA', 'Bloqueada')], default='ATIVA', max_length=15)),
                ('tentativas_falhadas', models.PositiveIntegerField(default=0)),
                ('limite_maximo_consultas', models.PositiveIntegerField(default=5)),
                ('consultas_realizadas', models.PositiveIntegerField(default=0)),
                ('tempo_total_gastado', models.DurationField(default=datetime.timedelta(0))),
                ('paginas_acessadas', models.JSONField(default=list)),
            ],
            options={
                'verbose_name': 'Sessão de Consulta',
                'verbose_name_plural': 'Sessões de Consulta',
                'ordering': ['-data_criacao'],
            },
        ),
        migrations.CreateModel(
            name='FeedbackConsumidor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('consumidor_email', models.EmailField(blank=True, max_length=254)),
                ('consumidor_cpf', models.CharField(blank=True, max_length=15)),
                ('tipo_feedback', models.CharField(choices=[('USABILIDADE', 'Usabilidade do Portal'), ('PROCESSO_TRAMATACAO', 'Processo de Tramitação'), ('ATENDIMENTO_PROCON', 'Atendimento do PROCON'), ('RESPOSTA_EMPRESA', 'Resposta da Empresa'), ('RESOLYCAO_FINAL', 'Resolução Final'), ('GERAL', 'Feedback Geral')], max_length=30)),
                ('protocolo_relacionado', models.CharField(blank=True, max_length=50)),
                ('nota_geral', models.PositiveIntegerField(help_text='Nota de 1 a 10', validators=[django.core.validators.MaxValueValidator(10)])),
                ('aspecto_positivo', models.TextField(blank=True, help_text='O que funcionou bem?')),
                ('aspecto_melhoria', models.TextField(blank=True, help_text='O que pode ser melhorado?')),
                ('sugestoes', models.TextField(blank=True, help_text='Sugestões específicas')),
                ('analise_sentimento', models.CharField(blank=True, choices=[('MUITO_POSITIVO', 'Muito Positivo'), ('POSITIVO', 'Positivo'), ('NEUTRO', 'Neutro'), ('NEGATIVO', 'Negativo'), ('MUITO_NEGATIVO', 'Muito Negativo')], max_length=20)),
                ('confianca_analise_sentimento', models.FloatField(blank=True, help_text='Confiância da análise (0-1)', null=True)),
                ('data_feedback', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('revisado', models.BooleanField(default=False)),
                ('data_revisao', models.DateTimeField(blank=True, null=True)),
                ('acoes_tomadas', models.TextField(blank=True)),
                ('categoria_feedback', models.CharField(blank=True, max_length=50)),
                ('tags', models.JSONField(default=list)),
                ('revisado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedbacks_revisados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Feedback do Consumidor',
                'verbose_name_plural': 'Feedbacks do Consumidor',
                'ordering': ['-data_feedback'],
            },
        ),
        migrations.CreateModel(
            name='HistoricoConsulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('protocolo_buscado', models.CharField(blank=True, max_length=50)),
                ('cpf_informado', models.CharField(blank=True, max_length=15)),
                ('tipo_reclamacao_buscada', models.CharField(blank=True, max_length=50)),
                ('resultado', models.CharField(choices=[('ENCONTRADO', 'Documento Encontrado'), ('NAO_ENCONTRADO', 'Documento Não Encontrado'), ('ACESSO_NEGADO', 'Acesso Negado'), ('ERRO_TECNICO', 'Erro Técnico')], max_length=20)),
                ('documentos_encontrados', models.JSONField(default=list)),
                ('quantidade_encontrada', models.PositiveIntegerField(default=0)),
                ('data_consulta', models.DateTimeField(auto_now_add=True)),
                ('tempo_gasto_esta_consulta', models.DurationField()),
                ('satisfacao_usuario', models.CharField(blank=True, choices=[('MUITO_SATISFEITO', 'Muito Satisfeito'), ('SATISFEITO', 'Satisfeito'), ('NEUTRO', 'Neutro'), ('INSATISFEITO', 'Insatisfeito'), ('MUITO_INSATISFEITO', 'Muito Insatisfeito')], max_length=20)),
                ('comentario_usuario', models.TextField(blank=True)),
                ('sessao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historicos', to='portal_consumidor.sessaoconsulta')),
            ],
            options={
                'verbose_name': 'Histórico de Consulta',
                'verbose_name_plural': 'Históricos de Consultas',
                'ordering': ['-data_consulta'],
            },
        ),
        migrations.CreateModel(
            name='TicketSuporteConsumidor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('consumidor_email', models.EmailField(blank=True, max_length=254)),
                ('consumidor_nome', models.CharField(blank=True, max_length=150)),
                ('consumidor_cpf', models.CharField(blank=True, max_length=15)),
                ('protocolo_relacionado', models.CharField(blank=True, max_length=50)),
                ('assunto', models.CharField(max_length=200)),
                ('categoria', models.CharField(blank=True, max_length=60)),
                ('descricao', models.TextField()),
                ('status', models.CharField(choices=[('ABERTO', 'Aberto'), ('EM_ANALISE', 'Em análise'), ('RESPONDIDO', 'Respondido'), ('FECHADO', 'Fechado')], default='ABERTO', max_length=20)),
                ('prioridade', models.CharField(choices=[('BAIXA', 'Baixa'), ('MEDIA', 'Média'), ('ALTA', 'Alta'), ('URGENTE', 'Urgente')], default='MEDIA', max_length=15)),
                ('resposta', models.TextField(blank=True)),
                ('data_resposta', models.DateTimeField(blank=True, null=True)),
                ('tags', models.JSONField(blank=True, default=portal_consumidor.models.list_blank)),
                ('metadados', models.JSONField(blank=True, default=portal_consumidor.models.dict_blank)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('respondido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets_respondidos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ticket de Suporte do Consumidor',
                'verbose_name_plural': 'Tickets de Suporte dos Consumidores',
                'ordering': ['-data_criacao'],
                'indexes': [models.Index(fields=['consumidor_email'], name='portal_cons_consumi_081e19_idx'), models.Index(fields=['status'], name='portal_cons_status_39d782_idx'), models.Index(fields=['prioridade'], name='portal_cons_priorid_4eb3cc_idx')],
            },
        ),
    ]
