# Generated by Django 5.2.5 on 2025-10-25 16:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('portal_cidadao', '0007_alter_reclamacaodenuncia_auto_infracao_relacionado'),
        ('ppa', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TriagemDemanda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_protocolo', models.CharField(blank=True, max_length=30, unique=True, verbose_name='Número do Protocolo')),
                ('origem', models.CharField(choices=[('PORTAL', 'Portal Cidadão'), ('TELEFONE', 'Telefone'), ('PRESENCIAL', 'Presencial'), ('EMAIL', 'E-mail'), ('OFICIO', 'Ofício/Parceiro'), ('ROTINA', 'Planejamento / Fiscalização de Rotina')], default='PORTAL', max_length=20, verbose_name='Origem')),
                ('assunto', models.CharField(max_length=255, verbose_name='Assunto / Tema Principal')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição detalhada')),
                ('empresa_alvo', models.CharField(max_length=255, verbose_name='Empresa / Estabelecimento alvo')),
                ('cnpj_empresa', models.CharField(blank=True, max_length=18, verbose_name='CNPJ da empresa')),
                ('endereco_empresa', models.TextField(blank=True, verbose_name='Endereço do estabelecimento')),
                ('denunciante_nome', models.CharField(blank=True, max_length=255, verbose_name='Nome do denunciante')),
                ('denunciante_contato', models.CharField(blank=True, max_length=255, verbose_name='Contato do denunciante')),
                ('prioridade_sugerida', models.CharField(choices=[('baixa', 'Baixa'), ('media', 'Média'), ('alta', 'Alta'), ('critica', 'Crítica')], default='media', max_length=10, verbose_name='Prioridade sugerida')),
                ('prioridade_definida', models.CharField(blank=True, choices=[('baixa', 'Baixa'), ('media', 'Média'), ('alta', 'Alta'), ('critica', 'Crítica')], max_length=10, verbose_name='Prioridade definida')),
                ('prazo_atendimento', models.DateField(blank=True, null=True, verbose_name='Prazo sugerido para atendimento')),
                ('status', models.CharField(choices=[('em_triagem', 'Em triagem'), ('aguardando_complemento', 'Aguardando complementação'), ('encaminhado_fiscalizacao', 'Encaminhado para fiscalização'), ('encaminhado_juridico', 'Encaminhado para análise jurídica'), ('convertido_ppa', 'PPA criado/vinculado'), ('arquivado', 'Arquivado')], default='em_triagem', max_length=40, verbose_name='Status da triagem')),
                ('decisao', models.CharField(choices=[('pendente', 'Pendente'), ('solicitar_complemento', 'Solicitar complementação'), ('abrir_fiscalizacao', 'Abrir fiscalização'), ('encaminhar_juridico', 'Encaminhar para análise jurídica'), ('abrir_campanha', 'Incluir em operação de rotina'), ('arquivar', 'Arquivar')], default='pendente', max_length=30, verbose_name='Decisão principal')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações internas')),
                ('dados_extras', models.JSONField(blank=True, null=True, verbose_name='Dados extras')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='triagens_criadas', to=settings.AUTH_USER_MODEL)),
                ('denuncia_portal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='triagens', to='portal_cidadao.denunciacidadao', verbose_name='Denúncia do Portal')),
                ('ppa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='triagens', to='ppa.procedimentopreadministrativo', verbose_name='PPA vinculado')),
                ('responsavel_triagem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='triagens_responsavel', to=settings.AUTH_USER_MODEL)),
                ('ultima_atualizacao_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='triagens_atualizadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Triagem de Demanda',
                'verbose_name_plural': 'Triagens de Demandas',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='TriagemHistorico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evento', models.CharField(choices=[('criacao', 'Criação'), ('atualizacao', 'Atualização'), ('mudanca_status', 'Mudança de status'), ('mudanca_decisao', 'Mudança de decisão'), ('vinculo_ppa', 'Vinculação de PPA'), ('comentario', 'Comentário'), ('encaminhamento_fiscalizacao', 'Encaminhamento para fiscalização'), ('encaminhamento_juridico', 'Encaminhamento para análise jurídica')], default='comentario', max_length=50, verbose_name='Evento')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('dados_extras', models.JSONField(blank=True, null=True, verbose_name='Dados extras')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('triagem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico', to='triagem.triagemdemanda', verbose_name='Triagem')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historico_triagem', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Histórico de Triagem',
                'verbose_name_plural': 'Históricos de Triagem',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.AddIndex(
            model_name='triagemdemanda',
            index=models.Index(fields=['numero_protocolo'], name='triagem_tri_numero__26a3a0_idx'),
        ),
        migrations.AddIndex(
            model_name='triagemdemanda',
            index=models.Index(fields=['origem'], name='triagem_tri_origem_73ffa9_idx'),
        ),
        migrations.AddIndex(
            model_name='triagemdemanda',
            index=models.Index(fields=['status'], name='triagem_tri_status_0ae6c8_idx'),
        ),
        migrations.AddIndex(
            model_name='triagemdemanda',
            index=models.Index(fields=['prioridade_sugerida'], name='triagem_tri_priorid_4577e8_idx'),
        ),
        migrations.AddIndex(
            model_name='triagemdemanda',
            index=models.Index(fields=['prioridade_definida'], name='triagem_tri_priorid_f08f3f_idx'),
        ),
        migrations.AddIndex(
            model_name='triagemdemanda',
            index=models.Index(fields=['criado_em'], name='triagem_tri_criado__8df8b1_idx'),
        ),
    ]
