# Generated by Django 5.2.5 on 2025-10-26 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triagem', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='triagemdemanda',
            name='prazo_previsto_atendimento',
            field=models.DateField(blank=True, null=True, verbose_name='Prazo calculado para atendimento'),
        ),
        migrations.AddField(
            model_name='triagemdemanda',
            name='prioridade_calculada',
            field=models.CharField(blank=True, choices=[('baixa', 'Baixa'), ('media', 'Média'), ('alta', 'Alta'), ('critica', 'Crítica')], max_length=10, verbose_name='Prioridade calculada'),
        ),
    ]
