# Generated by Django 5.2.5 on 2025-10-28 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triagem', '0002_triagemdemanda_prazo_previsto_atendimento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='triagemhistorico',
            name='motivo',
            field=models.CharField(blank=True, max_length=255, verbose_name='Motivo'),
        ),
        migrations.AddField(
            model_name='triagemhistorico',
            name='observacao',
            field=models.TextField(blank=True, verbose_name='Observação'),
        ),
        migrations.AlterField(
            model_name='triagemhistorico',
            name='evento',
            field=models.CharField(choices=[('criacao', 'Criação'), ('atualizacao', 'Atualização'), ('mudanca_status', 'Mudança de status'), ('mudanca_decisao', 'Mudança de decisão'), ('vinculo_ppa', 'Vinculação de PPA'), ('comentario', 'Comentário'), ('encaminhamento_fiscalizacao', 'Encaminhamento para fiscalização'), ('encaminhamento_juridico', 'Encaminhamento para análise jurídica'), ('solicitacao_complemento', 'Solicitação de complemento'), ('arquivamento', 'Arquivamento')], default='comentario', max_length=50, verbose_name='Evento'),
        ),
    ]
