# Generated by Django 5.2.5 on 2025-10-28 18:57

import django.db.models.deletion
import triagem.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triagem', '0003_triagemhistorico_motivo_triagemhistorico_observacao_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='triagemhistorico',
            name='evento',
            field=models.CharField(choices=[('criacao', 'Criação'), ('atualizacao', 'Atualização'), ('mudanca_status', 'Mudança de status'), ('mudanca_decisao', 'Mudança de decisão'), ('vinculo_ppa', 'Vinculação de PPA'), ('comentario', 'Comentário'), ('encaminhamento_fiscalizacao', 'Encaminhamento para fiscalização'), ('encaminhamento_juridico', 'Encaminhamento para análise jurídica'), ('solicitacao_complemento', 'Solicitação de complemento'), ('arquivamento', 'Arquivamento'), ('anexo', 'Anexo de documento')], default='comentario', max_length=50, verbose_name='Evento'),
        ),
        migrations.CreateModel(
            name='TriagemAnexo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(upload_to=triagem.models.triagem_anexo_upload_path, verbose_name='Arquivo')),
                ('nome_original', models.CharField(blank=True, max_length=255, verbose_name='Nome original')),
                ('descricao', models.CharField(blank=True, max_length=255, verbose_name='Descrição')),
                ('tamanho', models.PositiveIntegerField(default=0, verbose_name='Tamanho (bytes)')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Enviado em')),
                ('enviado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='triagem_anexos', to=settings.AUTH_USER_MODEL, verbose_name='Enviado por')),
                ('triagem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anexos', to='triagem.triagemdemanda', verbose_name='Triagem')),
            ],
            options={
                'verbose_name': 'Anexo de Triagem',
                'verbose_name_plural': 'Anexos de Triagem',
                'ordering': ['-criado_em'],
            },
        ),
    ]
