# Generated by Django 4.2.11 on 2025-11-10 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triagem', '0004_alter_triagemhistorico_evento_triagemanexo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='triagemdemanda',
            name='status',
            field=models.CharField(choices=[('em_triagem', 'Em triagem'), ('aguardando_complemento', 'Aguardando complementação'), ('encaminhado_fiscalizacao', 'Encaminhado para fiscalização'), ('encaminhado_juridico', 'Encaminhado para análise jurídica'), ('convertido_ppa', 'PPA criado/vinculado'), ('fora_competencia', 'Fora da competencia'), ('arquivado', 'Arquivado')], default='em_triagem', max_length=40, verbose_name='Status da triagem'),
        ),
    ]
