# Generated by Django 5.2.1 on 2025-08-15 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessoJuridico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=50, unique=True, verbose_name='Número do Processo')),
                ('parte', models.CharField(max_length=200, verbose_name='Parte Envolvida')),
                ('data_abertura', models.DateField(auto_now_add=True, verbose_name='Data de Abertura')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
            ],
        ),
    ]
