# Generated by Django 4.2.11 on 2025-08-25 00:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('juridico', '0002_complete_models'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='processojuridico',
            options={'ordering': ['-data_abertura'], 'verbose_name': 'Processo Jurídico', 'verbose_name_plural': 'Processos Jurídicos'},
        ),
        migrations.RemoveField(
            model_name='prazojuridico',
            name='observacoes',
        ),
        migrations.AddField(
            model_name='prazojuridico',
            name='data_cumprimento',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data de Cumprimento'),
        ),
        migrations.AddField(
            model_name='prazojuridico',
            name='notificado',
            field=models.BooleanField(default=False, verbose_name='Notificado'),
        ),
        migrations.AddField(
            model_name='prazojuridico',
            name='notificar_antes',
            field=models.IntegerField(default=3, verbose_name='Notificar (dias antes)'),
        ),
        migrations.AddField(
            model_name='prazojuridico',
            name='responsavel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prazos_responsavel', to='juridico.analistajuridico'),
        ),
        migrations.AlterField(
            model_name='prazojuridico',
            name='status',
            field=models.CharField(choices=[('PENDENTE', 'Pendente'), ('CUMPRIDO', 'Cumprido'), ('VENCIDO', 'Vencido'), ('PRORROGADO', 'Prorrogado')], default='PENDENTE', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='prazojuridico',
            name='tipo_prazo',
            field=models.CharField(choices=[('RESPOSTA', 'Prazo para Resposta'), ('RECURSO', 'Prazo para Recurso'), ('DOCUMENTO', 'Prazo para Documento'), ('AUDIENCIA', 'Prazo para Audiência'), ('OUTROS', 'Outros')], max_length=20, verbose_name='Tipo de Prazo'),
        ),
        migrations.AlterField(
            model_name='processojuridico',
            name='assunto',
            field=models.CharField(max_length=200, verbose_name='Assunto'),
        ),
        migrations.AlterField(
            model_name='processojuridico',
            name='descricao',
            field=models.TextField(verbose_name='Descrição'),
        ),
    ]
