# Generated by Django 5.2.5 on 2025-08-25 16:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiscalizacao', '0001_initial'),
        ('juridico', '0003_alter_processojuridico_options_and_more'),
        ('multas', '0002_alter_multa_options_multa_atualizado_em_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RecursoAdministrativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=50, unique=True, verbose_name='Número do Recurso')),
                ('tipo_recurso', models.CharField(choices=[('MULTA', 'Recurso contra Multa'), ('AUTO_INFRACAO', 'Recurso contra Auto de Infração'), ('DECISAO', 'Recurso contra Decisão'), ('INDEFERIMENTO', 'Recurso contra Indeferimento'), ('OUTROS', 'Outros')], max_length=20, verbose_name='Tipo de Recurso')),
                ('status', models.CharField(choices=[('PROTOCOLADO', 'Protocolado'), ('EM_ANALISE', 'Em Análise'), ('AGUARDANDO_DOCUMENTO', 'Aguardando Documento'), ('PARECER_ELABORADO', 'Parecer Elaborado'), ('DEFERIDO', 'Deferido'), ('INDEFERIDO', 'Indeferido'), ('ARQUIVADO', 'Arquivado')], default='PROTOCOLADO', max_length=20, verbose_name='Status')),
                ('nome_recorrente', models.CharField(max_length=200, verbose_name='Nome do Recorrente')),
                ('cpf_cnpj_recorrente', models.CharField(max_length=18, verbose_name='CPF/CNPJ do Recorrente')),
                ('email_recorrente', models.EmailField(blank=True, max_length=254, verbose_name='Email do Recorrente')),
                ('telefone_recorrente', models.CharField(blank=True, max_length=20, verbose_name='Telefone do Recorrente')),
                ('fundamentacao', models.TextField(verbose_name='Fundamentação do Recurso')),
                ('pedido', models.TextField(verbose_name='Pedido')),
                ('valor_questionado', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Valor Questionado')),
                ('data_protocolo', models.DateTimeField(auto_now_add=True, verbose_name='Data de Protocolo')),
                ('data_limite_analise', models.DateTimeField(blank=True, null=True, verbose_name='Data Limite para Análise')),
                ('data_conclusao', models.DateTimeField(blank=True, null=True, verbose_name='Data de Conclusão')),
                ('data_modificacao', models.DateTimeField(auto_now=True, verbose_name='Data de Modificação')),
                ('analista_responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recursos_analisados', to='juridico.analistajuridico')),
                ('auto_infracao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recursos', to='fiscalizacao.autoinfracao')),
                ('criado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recursos_criados', to=settings.AUTH_USER_MODEL)),
                ('modificado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recursos_modificados', to=settings.AUTH_USER_MODEL)),
                ('multa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recursos', to='multas.multa')),
                ('processo_origem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recursos', to='juridico.processojuridico')),
            ],
            options={
                'verbose_name': 'Recurso Administrativo',
                'verbose_name_plural': 'Recursos Administrativos',
                'ordering': ['-data_protocolo'],
            },
        ),
        migrations.CreateModel(
            name='ParecerJuridico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_parecer', models.CharField(choices=[('INICIAL', 'Parecer Inicial'), ('TECNICO', 'Parecer Técnico'), ('FINAL', 'Parecer Final'), ('COMPLEMENTAR', 'Parecer Complementar')], max_length=20, verbose_name='Tipo de Parecer')),
                ('fundamentacao_juridica', models.TextField(verbose_name='Fundamentação Jurídica')),
                ('analise_fatos', models.TextField(verbose_name='Análise dos Fatos')),
                ('conclusao', models.TextField(verbose_name='Conclusão')),
                ('recomendacao', models.CharField(choices=[('DEFERIR', 'Deferir'), ('INDEFERIR', 'Indeferir'), ('PARCIALMENTE_DEFERIDO', 'Parcialmente Deferido'), ('ARQUIVAR', 'Arquivar'), ('SOLICITAR_MAIS_INFORMACOES', 'Solicitar Mais Informações')], max_length=30, verbose_name='Recomendação')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('data_elaboracao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Elaboração')),
                ('data_modificacao', models.DateTimeField(auto_now=True, verbose_name='Data de Modificação')),
                ('assinado', models.BooleanField(default=False, verbose_name='Assinado')),
                ('data_assinatura', models.DateTimeField(blank=True, null=True, verbose_name='Data de Assinatura')),
                ('analista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pareceres_elaborados', to='juridico.analistajuridico')),
                ('recurso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pareceres', to='juridico.recursoadministrativo')),
            ],
            options={
                'verbose_name': 'Parecer Jurídico',
                'verbose_name_plural': 'Pareceres Jurídicos',
                'ordering': ['-data_elaboracao'],
            },
        ),
        migrations.CreateModel(
            name='HistoricoRecurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acao', models.CharField(max_length=100, verbose_name='Ação')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('dados_anteriores', models.JSONField(blank=True, null=True, verbose_name='Dados Anteriores')),
                ('dados_novos', models.JSONField(blank=True, null=True, verbose_name='Dados Novos')),
                ('data_alteracao', models.DateTimeField(auto_now_add=True, verbose_name='Data da Alteração')),
                ('ip_origem', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP de Origem')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alteracoes_recursos', to=settings.AUTH_USER_MODEL)),
                ('recurso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico', to='juridico.recursoadministrativo')),
            ],
            options={
                'verbose_name': 'Histórico de Recurso',
                'verbose_name_plural': 'Históricos de Recurso',
                'ordering': ['-data_alteracao'],
            },
        ),
        migrations.CreateModel(
            name='DocumentoRecurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_documento', models.CharField(choices=[('RECURSO', 'Recurso'), ('DEFESA', 'Defesa'), ('PROVA', 'Prova'), ('DECISAO', 'Decisão'), ('PARECER', 'Parecer'), ('OUTROS', 'Outros')], max_length=20, verbose_name='Tipo de Documento')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('arquivo', models.FileField(upload_to='juridico/recursos/documentos/', verbose_name='Arquivo')),
                ('nome_arquivo', models.CharField(max_length=255, verbose_name='Nome do Arquivo')),
                ('tamanho_arquivo', models.IntegerField(blank=True, null=True, verbose_name='Tamanho (bytes)')),
                ('data_upload', models.DateTimeField(auto_now_add=True, verbose_name='Data de Upload')),
                ('upload_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos_recurso_upload', to=settings.AUTH_USER_MODEL)),
                ('recurso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='juridico.recursoadministrativo')),
            ],
            options={
                'verbose_name': 'Documento de Recurso',
                'verbose_name_plural': 'Documentos de Recurso',
                'ordering': ['-data_upload'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowJuridico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_workflow', models.CharField(choices=[('ANALISE_JURIDICA', 'Análise Jurídica'), ('APROVACAO_PARECER', 'Aprovação de Parecer'), ('DECISAO_RECURSO', 'Decisão de Recurso'), ('ASSINATURA_DOCUMENTO', 'Assinatura de Documento')], max_length=30, verbose_name='Tipo de Workflow')),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('EM_ANALISE', 'Em Análise'), ('APROVADO', 'Aprovado'), ('REPROVADO', 'Reprovado'), ('CANCELADO', 'Cancelado')], default='PENDENTE', max_length=20, verbose_name='Status')),
                ('data_inicio', models.DateTimeField(auto_now_add=True, verbose_name='Data de Início')),
                ('data_conclusao', models.DateTimeField(blank=True, null=True, verbose_name='Data de Conclusão')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('parecer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workflows', to='juridico.parecerjuridico')),
                ('processo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workflows', to='juridico.processojuridico')),
                ('recurso', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workflows', to='juridico.recursoadministrativo')),
                ('responsavel_atual', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workflows_responsavel', to='juridico.analistajuridico')),
            ],
            options={
                'verbose_name': 'Workflow Jurídico',
                'verbose_name_plural': 'Workflows Jurídicos',
                'ordering': ['-data_inicio'],
            },
        ),
    ]
