# Generated by Django 4.2.11 on 2025-09-21 04:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EventoAgenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('data_inicio', models.DateTimeField(verbose_name='Data/Hora Início')),
                ('data_fim', models.DateTimeField(verbose_name='Data/Hora Fim')),
                ('dia_inteiro', models.BooleanField(default=False, verbose_name='Dia Inteiro')),
                ('local', models.CharField(blank=True, max_length=255, verbose_name='Local')),
                ('endereco', models.TextField(blank=True, verbose_name='Endereço Completo')),
                ('observacoes_local', models.TextField(blank=True, verbose_name='Observações do Local')),
                ('prioridade', models.CharField(choices=[('baixa', 'Baixa'), ('normal', 'Normal'), ('alta', 'Alta'), ('urgente', 'Urgente')], default='normal', max_length=10, verbose_name='Prioridade')),
                ('status', models.CharField(choices=[('agendado', 'Agendado'), ('confirmado', 'Confirmado'), ('em_andamento', 'Em Andamento'), ('concluido', 'Concluído'), ('cancelado', 'Cancelado'), ('adiado', 'Adiado')], default='agendado', max_length=20, verbose_name='Status')),
                ('lembrete_antecedencia', models.IntegerField(default=30, help_text='0 = sem lembrete', verbose_name='Lembrete (min antes)')),
                ('lembrete_enviado', models.BooleanField(default=False, verbose_name='Lembrete Enviado')),
                ('recorrente', models.BooleanField(default=False, verbose_name='Recorrente')),
                ('tipo_recorrencia', models.CharField(blank=True, choices=[('diaria', 'Diária'), ('semanal', 'Semanal'), ('mensal', 'Mensal'), ('anual', 'Anual')], max_length=20, verbose_name='Tipo de Recorrência')),
                ('intervalo_recorrencia', models.IntegerField(default=1, help_text='A cada X períodos', verbose_name='Intervalo')),
                ('fim_recorrencia', models.DateField(blank=True, null=True, verbose_name='Fim da Recorrência')),
                ('empresa_relacionada', models.CharField(blank=True, max_length=18, verbose_name='CNPJ Empresa')),
                ('processo_relacionado', models.CharField(blank=True, max_length=50, verbose_name='Número Processo')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('criado_por', models.CharField(max_length=100, verbose_name='Criado por')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('evento_pai', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='agenda.eventoagenda', verbose_name='Evento Pai')),
            ],
            options={
                'verbose_name': 'Evento da Agenda',
                'verbose_name_plural': 'Eventos da Agenda',
                'ordering': ['data_inicio'],
            },
        ),
        migrations.CreateModel(
            name='Fiscal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome Completo')),
                ('matricula', models.CharField(max_length=20, unique=True, verbose_name='Matrícula')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('telefone', models.CharField(blank=True, max_length=20, verbose_name='Telefone')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Fiscal',
                'verbose_name_plural': 'Fiscais',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='TipoEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Nome')),
                ('cor', models.CharField(default='#007bff', help_text='Cor hexadecimal', max_length=7, verbose_name='Cor')),
                ('icone', models.CharField(blank=True, max_length=50, verbose_name='Ícone')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('duracao_padrao', models.IntegerField(default=60, verbose_name='Duração Padrão (min)')),
                ('permite_conflito', models.BooleanField(default=False, verbose_name='Permite Conflito de Horário')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Tipo de Evento',
                'verbose_name_plural': 'Tipos de Evento',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='ParticipacaoEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_participacao', models.CharField(choices=[('convidado', 'Convidado'), ('confirmado', 'Confirmado'), ('rejeitado', 'Rejeitado'), ('presente', 'Presente'), ('ausente', 'Ausente')], default='convidado', max_length=20, verbose_name='Status')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('data_confirmacao', models.DateTimeField(blank=True, null=True, verbose_name='Data de Confirmação')),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agenda.eventoagenda')),
                ('fiscal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agenda.fiscal')),
            ],
            options={
                'verbose_name': 'Participação em Evento',
                'verbose_name_plural': 'Participações em Eventos',
                'unique_together': {('evento', 'fiscal')},
            },
        ),
        migrations.CreateModel(
            name='LembreteEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('canal', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), ('sistema', 'Sistema')], default='email', max_length=20, verbose_name='Canal')),
                ('antecedencia_minutos', models.IntegerField(verbose_name='Antecedência (min)')),
                ('data_agendada', models.DateTimeField(verbose_name='Data Agendada')),
                ('data_envio', models.DateTimeField(blank=True, null=True, verbose_name='Data de Envio')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('enviado', 'Enviado'), ('falhado', 'Falhado'), ('cancelado', 'Cancelado')], default='pendente', max_length=20, verbose_name='Status')),
                ('erro_envio', models.TextField(blank=True, verbose_name='Erro de Envio')),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lembretes', to='agenda.eventoagenda')),
                ('fiscal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agenda.fiscal')),
            ],
            options={
                'verbose_name': 'Lembrete de Evento',
                'verbose_name_plural': 'Lembretes de Eventos',
                'ordering': ['data_agendada'],
            },
        ),
        migrations.AddField(
            model_name='eventoagenda',
            name='fiscais_participantes',
            field=models.ManyToManyField(blank=True, related_name='eventos_participantes', through='agenda.ParticipacaoEvento', to='agenda.fiscal', verbose_name='Fiscais Participantes'),
        ),
        migrations.AddField(
            model_name='eventoagenda',
            name='fiscal_responsavel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos_responsavel', to='agenda.fiscal', verbose_name='Fiscal Responsável'),
        ),
        migrations.AddField(
            model_name='eventoagenda',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agenda.tipoevento', verbose_name='Tipo'),
        ),
        migrations.CreateModel(
            name='CalendarioFiscalizacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome da Fiscalização')),
                ('tipo_fiscalizacao', models.CharField(choices=[('rotina', 'Fiscalização de Rotina'), ('denuncia', 'Atendimento a Denúncia'), ('operacao', 'Operação Especial'), ('reincidencia', 'Verificação de Reincidência'), ('monitoramento', 'Monitoramento de Preços')], max_length=20, verbose_name='Tipo')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('data_programada', models.DateField(verbose_name='Data Programada')),
                ('hora_inicio', models.TimeField(verbose_name='Hora Início')),
                ('hora_fim', models.TimeField(blank=True, null=True, verbose_name='Hora Fim')),
                ('empresas_alvo', models.TextField(help_text='CNPJs ou nomes, um por linha', verbose_name='Empresas Alvo')),
                ('setor_alvo', models.CharField(blank=True, max_length=100, verbose_name='Setor Alvo')),
                ('regiao_alvo', models.CharField(blank=True, max_length=100, verbose_name='Região')),
                ('status', models.CharField(choices=[('programada', 'Programada'), ('em_execucao', 'Em Execução'), ('concluida', 'Concluída'), ('cancelada', 'Cancelada'), ('adiada', 'Adiada')], default='programada', max_length=20, verbose_name='Status')),
                ('data_execucao', models.DateField(blank=True, null=True, verbose_name='Data de Execução')),
                ('estabelecimentos_visitados', models.IntegerField(default=0, verbose_name='Estabelecimentos Visitados')),
                ('autos_lavrados', models.IntegerField(default=0, verbose_name='Autos Lavrados')),
                ('observacoes_resultado', models.TextField(blank=True, verbose_name='Observações do Resultado')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('criado_por', models.CharField(max_length=100, verbose_name='Criado por')),
                ('fiscal_apoio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fiscalizacoes_apoio', to='agenda.fiscal')),
                ('fiscal_responsavel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fiscalizacoes_responsavel', to='agenda.fiscal')),
            ],
            options={
                'verbose_name': 'Calendário de Fiscalização',
                'verbose_name_plural': 'Calendário de Fiscalizações',
                'ordering': ['data_programada', 'hora_inicio'],
            },
        ),
        migrations.AddIndex(
            model_name='eventoagenda',
            index=models.Index(fields=['data_inicio', 'data_fim'], name='agenda_even_data_in_34cc32_idx'),
        ),
        migrations.AddIndex(
            model_name='eventoagenda',
            index=models.Index(fields=['fiscal_responsavel', 'data_inicio'], name='agenda_even_fiscal__18cc78_idx'),
        ),
        migrations.AddIndex(
            model_name='eventoagenda',
            index=models.Index(fields=['status'], name='agenda_even_status_cc6604_idx'),
        ),
    ]
