# Generated by Django 5.2.5 on 2025-10-09 14:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IntegrationConnector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120, verbose_name='Nome do Conector')),
                ('slug', models.SlugField(max_length=80, unique=True, verbose_name='Slug')),
                ('orgao_responsavel', models.CharField(max_length=150, verbose_name='Órgão Responsável')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('endpoint_base', models.URLField(verbose_name='Endpoint Base')),
                ('tipo_autenticacao', models.CharField(choices=[('JWT', 'JWT'), ('API_KEY', 'API Key'), ('CERTIFICATE', 'Certificado'), ('BASIC', 'Basic Auth'), ('NONE', 'Sem Autenticação')], default='API_KEY', max_length=20, verbose_name='Tipo de Autenticação')),
                ('configuracao_credenciais', models.JSONField(blank=True, default=dict, verbose_name='Configuração de Credenciais')),
                ('configuracao_headers', models.JSONField(blank=True, default=dict, verbose_name='Headers Padrão')),
                ('configuracao_parametros', models.JSONField(blank=True, default=dict, verbose_name='Parâmetros Padrão')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('ultima_sincronizacao', models.DateTimeField(blank=True, null=True, verbose_name='Última sincronização')),
                ('proxima_sincronizacao', models.DateTimeField(blank=True, null=True, verbose_name='Próxima sincronização')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('criado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='connectores_criados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Conector Governamental',
                'verbose_name_plural': 'Conectores Governamentais',
                'ordering': ['orgao_responsavel', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='IntegrationEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_evento', models.CharField(max_length=80, verbose_name='Tipo de Evento')),
                ('referencia_externa', models.CharField(blank=True, max_length=120, verbose_name='Identificador Externo')),
                ('payload', models.JSONField(blank=True, default=dict, verbose_name='Payload do Evento')),
                ('recebido_em', models.DateTimeField(auto_now_add=True, verbose_name='Recebido em')),
                ('processado', models.BooleanField(default=False, verbose_name='Processado')),
                ('processado_em', models.DateTimeField(blank=True, null=True, verbose_name='Processado em')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('connector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='government_integration.integrationconnector')),
            ],
            options={
                'verbose_name': 'Evento de Integração',
                'verbose_name_plural': 'Eventos de Integração',
                'ordering': ['-recebido_em'],
                'indexes': [models.Index(fields=['connector', '-recebido_em'], name='government__connect_150af6_idx'), models.Index(fields=['tipo_evento', 'processado'], name='government__tipo_ev_1f4428_idx')],
            },
        ),
        migrations.CreateModel(
            name='IntegrationSyncRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iniciado_em', models.DateTimeField(auto_now_add=True, verbose_name='Iniciado em')),
                ('finalizado_em', models.DateTimeField(blank=True, null=True, verbose_name='Finalizado em')),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('EXECUTANDO', 'Executando'), ('SUCESSO', 'Sucesso'), ('ERRO', 'Erro'), ('CANCELADO', 'Cancelado')], default='PENDENTE', max_length=12, verbose_name='Status')),
                ('payload_envio', models.JSONField(blank=True, default=dict, verbose_name='Payload Enviado')),
                ('retorno_bruto', models.JSONField(blank=True, default=dict, verbose_name='Retorno Bruto')),
                ('erros_encontrados', models.TextField(blank=True, verbose_name='Erros Encontrados')),
                ('registros_processados', models.PositiveIntegerField(default=0, verbose_name='Registros Processados')),
                ('connector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='execucoes', to='government_integration.integrationconnector')),
                ('responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='execucoes_integracao', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Execução de Integração',
                'verbose_name_plural': 'Execuções de Integração',
                'ordering': ['-iniciado_em'],
                'indexes': [models.Index(fields=['connector', '-iniciado_em'], name='government__connect_6d3729_idx'), models.Index(fields=['status'], name='government__status_7729ae_idx')],
            },
        ),
    ]
