# Generated by Django 4.2.11 on 2025-09-21 04:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AcessoEspecialCaixaEntrada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.CharField(choices=[('ANALISE_ESPECIAL', 'Análise Especial'), ('COORDENACAO', 'Coordenação de Processo'), ('AUDITORIA', 'Auditoria'), ('SUPORTE', 'Suporte Técnico'), ('OUTROS', 'Outros')], max_length=20, verbose_name='Motivo')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('pode_editar', models.BooleanField(default=False, verbose_name='Pode Editar')),
                ('pode_encaminhar', models.BooleanField(default=True, verbose_name='Pode Encaminhar')),
                ('pode_arquivar', models.BooleanField(default=False, verbose_name='Pode Arquivar')),
                ('data_inicio', models.DateTimeField(auto_now_add=True, verbose_name='Data de Início')),
                ('data_fim', models.DateTimeField(blank=True, null=True, verbose_name='Data de Fim')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
            ],
            options={
                'verbose_name': 'Acesso Especial - Caixa de Entrada',
                'verbose_name_plural': 'Acessos Especiais - Caixa de Entrada',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='AnexoCaixaEntrada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(upload_to='caixa_entrada/anexos/%Y/%m/%d/', verbose_name='Arquivo')),
                ('nome_original', models.CharField(max_length=255, verbose_name='Nome Original')),
                ('tipo_mime', models.CharField(max_length=100, verbose_name='Tipo MIME')),
                ('tamanho', models.PositiveIntegerField(verbose_name='Tamanho (bytes)')),
                ('descricao', models.CharField(blank=True, max_length=200, verbose_name='Descrição')),
                ('upload_em', models.DateTimeField(auto_now_add=True, verbose_name='Upload em')),
            ],
            options={
                'verbose_name': 'Anexo da Caixa de Entrada',
                'verbose_name_plural': 'Anexos da Caixa de Entrada',
                'ordering': ['-upload_em'],
            },
        ),
        migrations.CreateModel(
            name='CaixaEntrada',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('numero_protocolo', models.CharField(blank=True, max_length=50, unique=True, verbose_name='Número de Protocolo')),
                ('tipo_documento', models.CharField(choices=[('PETICAO', 'Petição'), ('RECURSO', 'Recurso'), ('DENUNCIA', 'Denúncia'), ('RECLAMACAO', 'Reclamação'), ('AUTO_INFRACAO', 'Auto de Infração'), ('MULTA', 'Multa'), ('PROTOCOLO', 'Protocolo'), ('DOCUMENTO_INTERNO', 'Documento Interno'), ('SOLICITACAO', 'Solicitação'), ('OUTROS', 'Outros')], max_length=20, verbose_name='Tipo de Documento')),
                ('assunto', models.CharField(max_length=200, verbose_name='Assunto')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('prioridade', models.CharField(choices=[('BAIXA', 'Baixa'), ('NORMAL', 'Normal'), ('ALTA', 'Alta'), ('URGENTE', 'Urgente')], default='NORMAL', max_length=10, verbose_name='Prioridade')),
                ('status', models.CharField(choices=[('NAO_LIDO', 'Não Lido'), ('LIDO', 'Lido'), ('EM_ANALISE', 'Em Análise'), ('RESPONDIDO', 'Respondido'), ('ARQUIVADO', 'Arquivado'), ('ENCAMINHADO', 'Encaminhado')], default='NAO_LIDO', max_length=15, verbose_name='Status')),
                ('lido_em', models.DateTimeField(blank=True, null=True, verbose_name='Lido em')),
                ('remetente_nome', models.CharField(max_length=200, verbose_name='Nome do Remetente')),
                ('remetente_documento', models.CharField(blank=True, max_length=20, verbose_name='CPF/CNPJ')),
                ('remetente_email', models.EmailField(blank=True, max_length=254, verbose_name='E-mail')),
                ('remetente_telefone', models.CharField(blank=True, max_length=20, verbose_name='Telefone')),
                ('empresa_nome', models.CharField(blank=True, max_length=200, verbose_name='Nome da Empresa')),
                ('empresa_cnpj', models.CharField(blank=True, max_length=18, verbose_name='CNPJ da Empresa')),
                ('setor_destino', models.CharField(max_length=100, verbose_name='Setor Destino')),
                ('setor_lotacao', models.CharField(blank=True, max_length=100, verbose_name='Setor de Lotação')),
                ('notificado_dte', models.BooleanField(default=False, verbose_name='Notificado no DTE')),
                ('data_notificacao_dte', models.DateTimeField(blank=True, null=True, verbose_name='Data Notificação DTE')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('origem', models.CharField(default='PORTAL_CIDADAO', max_length=50, verbose_name='Origem')),
                ('ip_origem', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP de Origem')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('prazo_resposta', models.DateTimeField(blank=True, null=True, verbose_name='Prazo para Resposta')),
                ('data_entrada', models.DateTimeField(auto_now_add=True, verbose_name='Data de Entrada')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('versao', models.PositiveIntegerField(default=1, verbose_name='Versão')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('destinatario_direto', models.ForeignKey(blank=True, help_text='Usuário destinatário direto do documento', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos_destinatario_direto', to=settings.AUTH_USER_MODEL)),
                ('documento_anterior', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='versoes_posteriores', to='caixa_entrada.caixaentrada')),
                ('lido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos_lidos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Documento na Caixa de Entrada',
                'verbose_name_plural': 'Documentos na Caixa de Entrada',
                'ordering': ['-data_entrada'],
            },
        ),
        migrations.CreateModel(
            name='ConfiguracaoCaixaEntrada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auto_distribuir', models.BooleanField(default=True, verbose_name='Distribuição Automática')),
                ('notificar_novos', models.BooleanField(default=True, verbose_name='Notificar Novos Documentos')),
                ('alerta_prazos', models.BooleanField(default=True, verbose_name='Alerta de Prazos')),
                ('dias_alerta_prazo', models.PositiveIntegerField(default=3, verbose_name='Dias para Alerta de Prazo')),
                ('formato_protocolo', models.CharField(default='PROT-{ANO}-{SEQUENCIAL:06d}', max_length=50, verbose_name='Formato do Protocolo')),
                ('sequencial_por_ano', models.BooleanField(default=True, verbose_name='Sequencial por Ano')),
                ('notificar_email', models.BooleanField(default=True, verbose_name='Notificar por Email')),
                ('notificar_sms', models.BooleanField(default=False, verbose_name='Notificar por SMS')),
                ('notificar_push', models.BooleanField(default=False, verbose_name='Notificar Push')),
                ('dias_retencao', models.PositiveIntegerField(default=365, verbose_name='Dias de Retenção')),
                ('auto_arquivar', models.BooleanField(default=True, verbose_name='Arquivamento Automático')),
            ],
            options={
                'verbose_name': 'Configuração da Caixa de Entrada',
                'verbose_name_plural': 'Configurações da Caixa de Entrada',
            },
        ),
        migrations.CreateModel(
            name='PermissaoSetorCaixaEntrada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('setor', models.CharField(choices=[('ATENDIMENTO', 'Atendimento/Protocolo'), ('FISCALIZACAO', 'Fiscalização'), ('JURIDICO', 'Jurídico'), ('DIRETORIA', 'Diretoria/Administração'), ('FINANCEIRO', 'Financeiro'), ('COBRANCA', 'Cobrança'), ('ADMINISTRATIVO', 'Administrativo'), ('GERAL', 'Acesso Geral')], max_length=20, unique=True, verbose_name='Setor')),
                ('pode_visualizar', models.BooleanField(default=True, verbose_name='Pode Visualizar')),
                ('pode_editar', models.BooleanField(default=False, verbose_name='Pode Editar')),
                ('pode_encaminhar', models.BooleanField(default=True, verbose_name='Pode Encaminhar')),
                ('pode_arquivar', models.BooleanField(default=False, verbose_name='Pode Arquivar')),
                ('pode_excluir', models.BooleanField(default=False, verbose_name='Pode Excluir')),
                ('pode_gerenciar_permissoes', models.BooleanField(default=False, verbose_name='Pode Gerenciar Permissões')),
                ('setores_permitidos', models.JSONField(blank=True, default=list, verbose_name='Setores Permitidos')),
                ('tipos_documento_permitidos', models.JSONField(blank=True, default=list, verbose_name='Tipos de Documento Permitidos')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('usuarios', models.ManyToManyField(related_name='permissoes_caixa_entrada', to=settings.AUTH_USER_MODEL, verbose_name='Usuários')),
            ],
            options={
                'verbose_name': 'Permissão de Setor - Caixa de Entrada',
                'verbose_name_plural': 'Permissões de Setor - Caixa de Entrada',
                'ordering': ['setor'],
            },
        ),
        migrations.CreateModel(
            name='HistoricoCaixaEntrada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acao', models.CharField(choices=[('CRIADO', 'Documento Criado'), ('LIDO', 'Documento Lido'), ('ENCAMINHADO', 'Documento Encaminhado'), ('RESPONDIDO', 'Documento Respondido'), ('ARQUIVADO', 'Documento Arquivado'), ('STATUS_ALTERADO', 'Status Alterado'), ('PRIORIDADE_ALTERADA', 'Prioridade Alterada'), ('RESPONSAVEL_ALTERADO', 'Responsável Alterado')], max_length=20, verbose_name='Ação')),
                ('detalhes', models.TextField(blank=True, verbose_name='Detalhes')),
                ('dados_anteriores', models.JSONField(blank=True, default=dict, verbose_name='Dados Anteriores')),
                ('dados_novos', models.JSONField(blank=True, default=dict, verbose_name='Dados Novos')),
                ('data_acao', models.DateTimeField(auto_now_add=True, verbose_name='Data da Ação')),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico', to='caixa_entrada.caixaentrada')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Histórico da Caixa de Entrada',
                'verbose_name_plural': 'Histórico da Caixa de Entrada',
                'ordering': ['-data_acao'],
            },
        ),
    ]
