# Generated by Django 4.2.11 on 2025-08-31 13:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('caixa_entrada', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracaocaixaentrada',
            name='dias_retencao',
            field=models.PositiveIntegerField(default=365, verbose_name='Dias de Retenção'),
        ),
        migrations.AlterField(
            model_name='configuracaocaixaentrada',
            name='formato_protocolo',
            field=models.CharField(default='PROT-{ANO}-{SEQUENCIAL:06d}', max_length=50, verbose_name='Formato do Protocolo'),
        ),
        migrations.AlterField(
            model_name='configuracaocaixaentrada',
            name='notificar_email',
            field=models.BooleanField(default=True, verbose_name='Notificar por Email'),
        ),
        migrations.AlterField(
            model_name='configuracaocaixaentrada',
            name='notificar_push',
            field=models.BooleanField(default=False, verbose_name='Notificar Push'),
        ),
        migrations.CreateModel(
            name='PermissaoSetorCaixaEntrada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('setor', models.CharField(choices=[('ATENDIMENTO', 'Atendimento/Protocolo'), ('FISCALIZACAO', 'Fiscalização'), ('JURIDICO', 'Jurídico'), ('DIRETORIA', 'Diretoria/Administração'), ('FINANCEIRO', 'Financeiro'), ('COBRANCA', 'Cobrança'), ('ADMINISTRATIVO', 'Administrativo'), ('GERAL', 'Acesso Geral')], max_length=20, unique=True, verbose_name='Setor')),
                ('pode_visualizar', models.BooleanField(default=True, verbose_name='Pode Visualizar')),
                ('pode_editar', models.BooleanField(default=False, verbose_name='Pode Editar')),
                ('pode_encaminhar', models.BooleanField(default=True, verbose_name='Pode Encaminhar')),
                ('pode_arquivar', models.BooleanField(default=False, verbose_name='Pode Arquivar')),
                ('pode_excluir', models.BooleanField(default=False, verbose_name='Pode Excluir')),
                ('pode_gerenciar_permissoes', models.BooleanField(default=False, verbose_name='Pode Gerenciar Permissões')),
                ('setores_permitidos', models.JSONField(blank=True, default=list, verbose_name='Setores Permitidos')),
                ('tipos_documento_permitidos', models.JSONField(blank=True, default=list, verbose_name='Tipos de Documento Permitidos')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('usuarios', models.ManyToManyField(related_name='permissoes_caixa_entrada', to=settings.AUTH_USER_MODEL, verbose_name='Usuários')),
            ],
            options={
                'verbose_name': 'Permissão de Setor - Caixa de Entrada',
                'verbose_name_plural': 'Permissões de Setor - Caixa de Entrada',
                'ordering': ['setor'],
            },
        ),
        migrations.CreateModel(
            name='AcessoEspecialCaixaEntrada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.CharField(choices=[('ANALISE_ESPECIAL', 'Análise Especial'), ('COORDENACAO', 'Coordenação de Processo'), ('AUDITORIA', 'Auditoria'), ('SUPORTE', 'Suporte Técnico'), ('OUTROS', 'Outros')], max_length=20, verbose_name='Motivo')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('pode_editar', models.BooleanField(default=False, verbose_name='Pode Editar')),
                ('pode_encaminhar', models.BooleanField(default=True, verbose_name='Pode Encaminhar')),
                ('pode_arquivar', models.BooleanField(default=False, verbose_name='Pode Arquivar')),
                ('data_inicio', models.DateTimeField(auto_now_add=True, verbose_name='Data de Início')),
                ('data_fim', models.DateTimeField(blank=True, null=True, verbose_name='Data de Fim')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('concedido_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acessos_especiais_concedidos', to=settings.AUTH_USER_MODEL, verbose_name='Concedido por')),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caixa_entrada.caixaentrada', verbose_name='Documento')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Acesso Especial - Caixa de Entrada',
                'verbose_name_plural': 'Acessos Especiais - Caixa de Entrada',
                'ordering': ['-criado_em'],
                'unique_together': {('usuario', 'documento', 'ativo')},
            },
        ),
    ]
