# Generated by Django 4.2.11 on 2025-09-21 04:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('protocolo_tramitacao', '0001_initial'),
        ('caixa_entrada', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='caixaentrada',
            name='protocolo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos_caixa', to='protocolo_tramitacao.protocolodocumento'),
        ),
        migrations.AddField(
            model_name='caixaentrada',
            name='responsavel_atual',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos_responsavel', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='anexocaixaentrada',
            name='documento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anexos', to='caixa_entrada.caixaentrada'),
        ),
        migrations.AddField(
            model_name='anexocaixaentrada',
            name='upload_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='acessoespecialcaixaentrada',
            name='concedido_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acessos_especiais_concedidos', to=settings.AUTH_USER_MODEL, verbose_name='Concedido por'),
        ),
        migrations.AddField(
            model_name='acessoespecialcaixaentrada',
            name='documento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caixa_entrada.caixaentrada', verbose_name='Documento'),
        ),
        migrations.AddField(
            model_name='acessoespecialcaixaentrada',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário'),
        ),
        migrations.AddIndex(
            model_name='caixaentrada',
            index=models.Index(fields=['status'], name='caixa_entra_status_a54b39_idx'),
        ),
        migrations.AddIndex(
            model_name='caixaentrada',
            index=models.Index(fields=['tipo_documento'], name='caixa_entra_tipo_do_1eebcf_idx'),
        ),
        migrations.AddIndex(
            model_name='caixaentrada',
            index=models.Index(fields=['setor_destino'], name='caixa_entra_setor_d_c66b01_idx'),
        ),
        migrations.AddIndex(
            model_name='caixaentrada',
            index=models.Index(fields=['prioridade'], name='caixa_entra_priorid_d06247_idx'),
        ),
        migrations.AddIndex(
            model_name='caixaentrada',
            index=models.Index(fields=['data_entrada'], name='caixa_entra_data_en_9eefe4_idx'),
        ),
        migrations.AddIndex(
            model_name='caixaentrada',
            index=models.Index(fields=['prazo_resposta'], name='caixa_entra_prazo_r_6458c2_idx'),
        ),
        migrations.AddIndex(
            model_name='caixaentrada',
            index=models.Index(fields=['remetente_documento'], name='caixa_entra_remeten_5f2d6c_idx'),
        ),
        migrations.AddIndex(
            model_name='caixaentrada',
            index=models.Index(fields=['empresa_cnpj'], name='caixa_entra_empresa_fba04d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='acessoespecialcaixaentrada',
            unique_together={('usuario', 'documento', 'ativo')},
        ),
    ]
