# Generated by Django 5.2.5 on 2025-08-31 13:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caixa_entrada', '0002_alter_configuracaocaixaentrada_dias_retencao_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='caixaentrada',
            name='data_notificacao_dte',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data Notificação DTE'),
        ),
        migrations.AddField(
            model_name='caixaentrada',
            name='destinatario_direto',
            field=models.ForeignKey(blank=True, help_text='Usuário destinatário direto do documento', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos_destinatario_direto', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='caixaentrada',
            name='notificado_dte',
            field=models.BooleanField(default=False, verbose_name='Notificado no DTE'),
        ),
        migrations.AddField(
            model_name='caixaentrada',
            name='setor_lotacao',
            field=models.CharField(blank=True, max_length=100, verbose_name='Setor de Lotação'),
        ),
    ]
