# Generated by Django 4.2.11 on 2026-01-11 19:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('caixa_entrada', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='caixaentrada',
            name='bloqueado',
            field=models.BooleanField(default=False, verbose_name='Bloqueado'),
        ),
        migrations.AddField(
            model_name='caixaentrada',
            name='bloqueado_em',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Bloqueado em'),
        ),
        migrations.AddField(
            model_name='caixaentrada',
            name='bloqueado_por',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='documentos_bloqueados',
                to=settings.AUTH_USER_MODEL,
                verbose_name='Bloqueado por',
            ),
        ),
        migrations.AddField(
            model_name='caixaentrada',
            name='motivo_bloqueio',
            field=models.TextField(blank=True, verbose_name='Motivo do bloqueio'),
        ),
        migrations.AddIndex(
            model_name='caixaentrada',
            index=models.Index(fields=['bloqueado'], name='caixa_entra_bloquea_idx'),
        ),
    ]
