# Generated by Django 4.2.11 on 2026-01-15 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('caixa_entrada', '0003_add_bloqueio_fields'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='caixaentrada',
            new_name='caixa_entra_bloquea_f31c09_idx',
            old_name='caixa_entra_bloquea_idx',
        ),
    ]
