# Generated by Django 5.2.5 on 2025-09-25 23:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardAlerta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('info', 'Informação'), ('warning', 'Aviso'), ('error', 'Erro'), ('success', 'Sucesso')], default='info', max_length=20, verbose_name='Tipo')),
                ('prioridade', models.CharField(choices=[('baixa', 'Baixa'), ('normal', 'Normal'), ('alta', 'Alta'), ('urgente', 'Urgente')], default='normal', max_length=20, verbose_name='Prioridade')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('mensagem', models.TextField(verbose_name='Mensagem')),
                ('acao', models.CharField(blank=True, max_length=100, verbose_name='Ação')),
                ('url_acao', models.URLField(blank=True, verbose_name='URL da Ação')),
                ('lido', models.BooleanField(default=False, verbose_name='Lido')),
                ('data_lido', models.DateTimeField(blank=True, null=True, verbose_name='Data de Leitura')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('data_expiracao', models.DateTimeField(blank=True, null=True, verbose_name='Data de Expiração')),
                ('usuario_destinatario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alertas_recebidos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Alerta do Dashboard',
                'verbose_name_plural': 'Alertas do Dashboard',
                'ordering': ['-data_criacao'],
            },
        ),
        migrations.CreateModel(
            name='DashboardAtividade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('processo', 'Processo'), ('multa', 'Multa'), ('fiscalizacao', 'Fiscalização'), ('protocolo', 'Protocolo'), ('usuario', 'Usuário'), ('sistema', 'Sistema'), ('relatorio', 'Relatório')], max_length=20, verbose_name='Tipo')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('dados_extras', models.JSONField(blank=True, default=dict, verbose_name='Dados Extras')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atividades', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Atividade do Dashboard',
                'verbose_name_plural': 'Atividades do Dashboard',
                'ordering': ['-data_criacao'],
            },
        ),
        migrations.CreateModel(
            name='DashboardCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chave', models.CharField(max_length=100, unique=True, verbose_name='Chave')),
                ('dados', models.JSONField(verbose_name='Dados')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('data_expiracao', models.DateTimeField(verbose_name='Data de Expiração')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Cache do Dashboard',
                'verbose_name_plural': 'Caches do Dashboard',
                'ordering': ['-data_criacao'],
            },
        ),
        migrations.CreateModel(
            name='DashboardConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tema', models.CharField(choices=[('claro', 'Claro'), ('escuro', 'Escuro'), ('auto', 'Automático')], default='claro', max_length=20, verbose_name='Tema')),
                ('atualizacao_automatica', models.BooleanField(default=True, verbose_name='Atualização Automática')),
                ('intervalo_atualizacao', models.IntegerField(default=300, verbose_name='Intervalo (segundos)')),
                ('alertas_ativos', models.BooleanField(default=True, verbose_name='Alertas Ativos')),
                ('notificacoes_email', models.BooleanField(default=True, verbose_name='Notificações por Email')),
                ('widgets_ativos', models.JSONField(default=list, verbose_name='Widgets Ativos')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_config', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Configuração do Dashboard',
                'verbose_name_plural': 'Configurações do Dashboard',
            },
        ),
        migrations.DeleteModel(
            name='Dashboard',
        ),
    ]
