# Generated by Django 5.2.5 on 2025-08-17 04:12

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoProtocolo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('formato_protocolo', models.CharField(default='YYYYMMDD-HHMMSS-XXX', max_length=50)),
                ('prefixo_protocolo', models.CharField(blank=True, max_length=10)),
                ('prazo_padrao_dias', models.IntegerField(default=30)),
                ('prazo_urgente_dias', models.IntegerField(default=5)),
                ('notificar_vencimento_dias', models.IntegerField(default=3)),
                ('notificar_responsavel', models.BooleanField(default=True)),
                ('notificar_setor', models.BooleanField(default=True)),
                ('tamanho_maximo_mb', models.IntegerField(default=10)),
                ('tipos_arquivo_permitidos', models.TextField(default='pdf,doc,docx,jpg,jpeg,png,txt', help_text='Tipos separados por vírgula')),
                ('dias_backup_automatico', models.IntegerField(default=1)),
                ('dias_arquivamento_automatico', models.IntegerField(default=365)),
            ],
            options={
                'verbose_name': 'Configuração do Protocolo',
                'verbose_name_plural': 'Configurações do Protocolo',
            },
        ),
        migrations.CreateModel(
            name='TipoDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True)),
                ('prazo_resposta_dias', models.IntegerField(default=30)),
                ('requer_assinatura', models.BooleanField(default=False)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Tipo de Documento',
                'verbose_name_plural': 'Tipos de Documentos',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='ProtocoloDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_protocolo', models.CharField(db_index=True, max_length=50, unique=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('origem', models.CharField(choices=[('EXTERNO', 'Documento Externo'), ('FISCALIZACAO', 'Auto de Fiscalização'), ('INTERNO', 'Documento Interno'), ('PETICIONAMENTO', 'Peticionamento'), ('DIGITAL', 'Documento Digital')], max_length=20)),
                ('assunto', models.CharField(max_length=200)),
                ('descricao', models.TextField()),
                ('status', models.CharField(choices=[('PROTOCOLADO', 'Protocolado'), ('EM_TRAMITACAO', 'Em Tramitação'), ('AGUARDANDO_ANALISE', 'Aguardando Análise'), ('EM_ANALISE', 'Em Análise'), ('AGUARDANDO_DECISAO', 'Aguardando Decisão'), ('DECIDIDO', 'Decidido'), ('ARQUIVADO', 'Arquivado'), ('CANCELADO', 'Cancelado')], default='PROTOCOLADO', max_length=20)),
                ('prioridade', models.CharField(choices=[('BAIXA', 'Baixa'), ('NORMAL', 'Normal'), ('ALTA', 'Alta'), ('URGENTE', 'Urgente')], default='NORMAL', max_length=10)),
                ('remetente_nome', models.CharField(max_length=200)),
                ('remetente_documento', models.CharField(help_text='CPF/CNPJ', max_length=50)),
                ('remetente_email', models.EmailField(blank=True, max_length=254)),
                ('remetente_telefone', models.CharField(blank=True, max_length=20)),
                ('remetente_endereco', models.TextField(blank=True)),
                ('prazo_resposta', models.DateTimeField(help_text='Prazo para resposta/análise')),
                ('data_protocolo', models.DateTimeField(auto_now_add=True)),
                ('data_conclusao', models.DateTimeField(blank=True, null=True)),
                ('observacoes', models.TextField(blank=True)),
                ('sigiloso', models.BooleanField(default=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('protocolado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documentos_protocolados', to=settings.AUTH_USER_MODEL)),
                ('responsavel_atual', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Protocolo de Documento',
                'verbose_name_plural': 'Protocolos de Documentos',
                'ordering': ['-data_protocolo'],
            },
        ),
        migrations.CreateModel(
            name='AnexoProtocolo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_arquivo', models.CharField(max_length=255)),
                ('arquivo', models.FileField(upload_to='protocolo/anexos/%Y/%m/%d/')),
                ('tipo_mime', models.CharField(max_length=100)),
                ('tamanho_bytes', models.BigIntegerField()),
                ('hash_arquivo', models.CharField(help_text='SHA-256 do arquivo', max_length=64)),
                ('upload_em', models.DateTimeField(auto_now_add=True)),
                ('descricao', models.TextField(blank=True)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('protocolo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anexos', to='protocolo_tramitacao.protocolodocumento')),
            ],
            options={
                'verbose_name': 'Anexo do Protocolo',
                'verbose_name_plural': 'Anexos dos Protocolos',
                'ordering': ['-upload_em'],
            },
        ),
        migrations.CreateModel(
            name='Setor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('sigla', models.CharField(max_length=10)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('pode_protocolar', models.BooleanField(default=True)),
                ('pode_tramitar', models.BooleanField(default=True)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Setor',
                'verbose_name_plural': 'Setores',
                'ordering': ['nome'],
            },
        ),
        migrations.AddField(
            model_name='protocolodocumento',
            name='setor_atual',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documentos_no_setor', to='protocolo_tramitacao.setor'),
        ),
        migrations.AddField(
            model_name='protocolodocumento',
            name='setor_origem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documentos_originados', to='protocolo_tramitacao.setor'),
        ),
        migrations.AddField(
            model_name='protocolodocumento',
            name='tipo_documento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='protocolo_tramitacao.tipodocumento'),
        ),
        migrations.CreateModel(
            name='TramitacaoDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acao', models.CharField(choices=[('PROTOCOLADO', 'Documento Protocolado'), ('ENCAMINHADO', 'Encaminhado para Setor'), ('RECEBIDO', 'Recebido pelo Setor'), ('EM_ANALISE', 'Colocado em Análise'), ('SOLICITACAO_INFO', 'Solicitação de Informações'), ('PARECER_EMITIDO', 'Parecer Emitido'), ('DECISAO_TOMADA', 'Decisão Tomada'), ('DEVOLVIDO', 'Devolvido ao Setor Anterior'), ('ARQUIVADO', 'Arquivado'), ('CANCELADO', 'Cancelado')], max_length=20)),
                ('motivo', models.TextField(help_text='Motivo da tramitação')),
                ('observacoes', models.TextField(blank=True)),
                ('prazo_dias', models.IntegerField(blank=True, help_text='Prazo em dias para retorno', null=True)),
                ('data_tramitacao', models.DateTimeField(auto_now_add=True)),
                ('data_recebimento', models.DateTimeField(blank=True, null=True)),
                ('hash_tramitacao', models.CharField(blank=True, max_length=64)),
                ('protocolo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tramitacoes', to='protocolo_tramitacao.protocolodocumento')),
                ('recebido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tramitacoes_recebidas', to=settings.AUTH_USER_MODEL)),
                ('setor_destino', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tramitacoes_recebidas', to='protocolo_tramitacao.setor')),
                ('setor_origem', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tramitacoes_enviadas', to='protocolo_tramitacao.setor')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tramitação de Documento',
                'verbose_name_plural': 'Tramitações de Documentos',
                'ordering': ['-data_tramitacao'],
            },
        ),
        migrations.AddIndex(
            model_name='protocolodocumento',
            index=models.Index(fields=['numero_protocolo'], name='protocolo_t_numero__5b5500_idx'),
        ),
        migrations.AddIndex(
            model_name='protocolodocumento',
            index=models.Index(fields=['status'], name='protocolo_t_status_ba5023_idx'),
        ),
        migrations.AddIndex(
            model_name='protocolodocumento',
            index=models.Index(fields=['setor_atual'], name='protocolo_t_setor_a_a501cd_idx'),
        ),
        migrations.AddIndex(
            model_name='protocolodocumento',
            index=models.Index(fields=['data_protocolo'], name='protocolo_t_data_pr_019c59_idx'),
        ),
        migrations.AddIndex(
            model_name='tramitacaodocumento',
            index=models.Index(fields=['protocolo', 'data_tramitacao'], name='protocolo_t_protoco_6ac568_idx'),
        ),
        migrations.AddIndex(
            model_name='tramitacaodocumento',
            index=models.Index(fields=['setor_destino', 'data_recebimento'], name='protocolo_t_setor_d_d8a319_idx'),
        ),
    ]
