# Generated by Django 5.2.5 on 2025-08-17 18:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiscalizacao', '0001_initial'),
        ('multas', '0002_alter_multa_options_multa_atualizado_em_and_more'),
        ('protocolo_tramitacao', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='protocolodocumento',
            name='auto_infracao',
            field=models.ForeignKey(blank=True, help_text='Auto de infração relacionado', null=True, on_delete=django.db.models.deletion.SET_NULL, to='fiscalizacao.autoinfracao'),
        ),
        migrations.AddField(
            model_name='protocolodocumento',
            name='multa_relacionada',
            field=models.ForeignKey(blank=True, help_text='Multa relacionada ao protocolo', null=True, on_delete=django.db.models.deletion.SET_NULL, to='multas.multa'),
        ),
        migrations.AddField(
            model_name='protocolodocumento',
            name='processo_fiscalizacao',
            field=models.ForeignKey(blank=True, help_text='Processo de fiscalização relacionado', null=True, on_delete=django.db.models.deletion.SET_NULL, to='fiscalizacao.processo'),
        ),
    ]
