# Generated by Django 4.2.11 on 2025-10-13 14:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('protocolo_tramitacao', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoNotificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('prioridade', models.CharField(choices=[('baixa', 'Baixa'), ('media', 'Média'), ('alta', 'Alta'), ('critica', 'Crítica')], default='media', max_length=10, verbose_name='Prioridade')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('enviar_email', models.BooleanField(default=True, verbose_name='Enviar por Email')),
                ('dias_antecedencia', models.IntegerField(default=3, verbose_name='Dias de Antecedência')),
            ],
            options={
                'verbose_name': 'Tipo de Notificação',
                'verbose_name_plural': 'Tipos de Notificações',
            },
        ),
        migrations.CreateModel(
            name='Notificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('mensagem', models.TextField(verbose_name='Mensagem')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('enviada', 'Enviada'), ('lida', 'Lida'), ('erro', 'Erro no Envio')], default='pendente', max_length=10, verbose_name='Status')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('data_envio', models.DateTimeField(blank=True, null=True, verbose_name='Enviado em')),
                ('data_leitura', models.DateTimeField(blank=True, null=True, verbose_name='Lido em')),
                ('objeto_tipo', models.CharField(blank=True, max_length=50, verbose_name='Tipo do Objeto')),
                ('objeto_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='ID do Objeto')),
                ('objeto_url', models.URLField(blank=True, verbose_name='URL do Objeto')),
                ('tentativas_envio', models.IntegerField(default=0, verbose_name='Tentativas de Envio')),
                ('ultimo_erro', models.TextField(blank=True, verbose_name='Último Erro')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='protocolo_tramitacao.tiponotificacao')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificacoes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notificação',
                'verbose_name_plural': 'Notificações',
                'ordering': ['-data_criacao'],
                'indexes': [models.Index(fields=['usuario', 'status'], name='protocolo_t_usuario_dcd37f_idx'), models.Index(fields=['data_criacao'], name='protocolo_t_data_cr_c111d2_idx'), models.Index(fields=['tipo', 'status'], name='protocolo_t_tipo_id_ec1e53_idx')],
            },
        ),
    ]
