# Generated by Django 5.2.5 on 2025-08-18 00:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analise_juridica', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='recursoadministrativo',
            name='relator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recursos_analise_relatados', to=settings.AUTH_USER_MODEL, verbose_name='Relator'),
        ),
    ]
