# Generated by Django 4.2.11 on 2025-09-21 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoFinanceira',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome da Configuração')),
                ('valor', models.CharField(max_length=255, verbose_name='Valor')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
            ],
            options={
                'verbose_name': 'Configuração Financeira',
                'verbose_name_plural': 'Configurações Financeiras',
            },
        ),
        migrations.CreateModel(
            name='Financeiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=200, verbose_name='Descrição')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor')),
                ('data', models.DateField(auto_now_add=True, verbose_name='Data')),
                ('tipo', models.CharField(choices=[('entrada', 'Entrada'), ('saida', 'Saída')], max_length=20, verbose_name='Tipo')),
            ],
            options={
                'verbose_name': 'Registro Financeiro (Legacy)',
                'verbose_name_plural': 'Registros Financeiros (Legacy)',
                'ordering': ['-data'],
            },
        ),
        migrations.CreateModel(
            name='RegistroFinanceiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_vencimento', models.DateField(help_text='Data limite para pagamento sem juros', verbose_name='Data de Vencimento')),
                ('data_pagamento', models.DateField(blank=True, help_text='Data em que o pagamento foi efetivado', null=True, verbose_name='Data de Pagamento')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('paga', 'Paga'), ('vencida', 'Vencida'), ('cancelada', 'Cancelada'), ('contestada', 'Contestada'), ('parcelada', 'Parcelada')], db_index=True, default='pendente', max_length=20, verbose_name='Status')),
                ('valor_original', models.DecimalField(decimal_places=2, help_text='Valor original da multa', max_digits=12, verbose_name='Valor Original')),
                ('valor_juros', models.DecimalField(decimal_places=2, default=0, help_text='Juros aplicados por atraso', max_digits=12, verbose_name='Valor de Juros')),
                ('valor_multa_atraso', models.DecimalField(decimal_places=2, default=0, help_text='Multa aplicada por atraso no pagamento', max_digits=12, verbose_name='Multa por Atraso')),
                ('valor_desconto', models.DecimalField(decimal_places=2, default=0, help_text='Desconto concedido (pagamento à vista, etc.)', max_digits=12, verbose_name='Valor de Desconto')),
                ('valor_pago', models.DecimalField(decimal_places=2, default=0, help_text='Valor que foi efetivamente pago', max_digits=12, verbose_name='Valor Efetivamente Pago')),
                ('tipo_pagamento', models.CharField(blank=True, choices=[('boleto', 'Boleto Bancário'), ('pix', 'PIX'), ('cartao', 'Cartão de Crédito/Débito'), ('transferencia', 'Transferência Bancária'), ('dinheiro', 'Dinheiro'), ('desconto_folha', 'Desconto em Folha')], max_length=20, null=True, verbose_name='Tipo de Pagamento')),
                ('numero_comprovante', models.CharField(blank=True, help_text='Número do boleto, código PIX, etc.', max_length=100, verbose_name='Número do Comprovante')),
                ('comprovante_pagamento', models.FileField(blank=True, help_text='Upload do comprovante de pagamento', null=True, upload_to='comprovantes_pagamento/%Y/%m/%d/', verbose_name='Comprovante de Pagamento')),
                ('observacoes', models.TextField(blank=True, help_text='Informações adicionais sobre o pagamento', verbose_name='Observações')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('criado_por', models.CharField(blank=True, help_text='Usuário que criou o registro', max_length=100, verbose_name='Criado por')),
            ],
            options={
                'verbose_name': 'Registro Financeiro de Multa',
                'verbose_name_plural': 'Registros Financeiros de Multas',
                'ordering': ['-criado_em'],
            },
        ),
    ]
