# Generated by Django 4.2.11 on 2025-09-21 04:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('multas', '0001_initial'),
        ('financeiro', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrofinanceiro',
            name='multa',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='registro_financeiro', to='multas.multa', verbose_name='Multa'),
        ),
        migrations.AddIndex(
            model_name='registrofinanceiro',
            index=models.Index(fields=['status'], name='financeiro__status_8ca393_idx'),
        ),
        migrations.AddIndex(
            model_name='registrofinanceiro',
            index=models.Index(fields=['data_vencimento'], name='financeiro__data_ve_1b3cab_idx'),
        ),
        migrations.AddIndex(
            model_name='registrofinanceiro',
            index=models.Index(fields=['data_pagamento'], name='financeiro__data_pa_ef9db0_idx'),
        ),
    ]
