# Generated by Django 4.2.11 on 2025-08-16 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoFinanceira',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome da Configuração')),
                ('valor', models.CharField(max_length=255, verbose_name='Valor')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
            ],
            options={
                'verbose_name': 'Configuração Financeira',
                'verbose_name_plural': 'Configurações Financeiras',
            },
        ),
        migrations.AlterModelOptions(
            name='financeiro',
            options={'ordering': ['-data'], 'verbose_name': 'Registro Financeiro', 'verbose_name_plural': 'Registros Financeiros'},
        ),
    ]
