# Generated by Django 4.2.11 on 2025-08-16 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0003_registrofinanceiro'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='financeiro',
            options={'ordering': ['-data'], 'verbose_name': 'Registro Financeiro (Legacy)', 'verbose_name_plural': 'Registros Financeiros (Legacy)'},
        ),
        migrations.RenameIndex(
            model_name='registrofinanceiro',
            new_name='financeiro__status_8ca393_idx',
            old_name='financeiro_r_status_c8fd6c_idx',
        ),
        migrations.RenameIndex(
            model_name='registrofinanceiro',
            new_name='financeiro__data_ve_1b3cab_idx',
            old_name='financeiro_r_data_ve_0a66d8_idx',
        ),
        migrations.RenameIndex(
            model_name='registrofinanceiro',
            new_name='financeiro__data_pa_ef9db0_idx',
            old_name='financeiro_r_data_pa_8e7ec8_idx',
        ),
    ]
