# Generated by Django 5.2.5 on 2025-08-25 17:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relatorios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoRelatorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('modulo', models.CharField(max_length=50, verbose_name='Módulo')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
            ],
            options={
                'verbose_name': 'Tipo de Relatório',
                'verbose_name_plural': 'Tipos de Relatórios',
            },
        ),
        migrations.RemoveField(
            model_name='logexecucaorelatorio',
            name='agendamento',
        ),
        migrations.RemoveField(
            model_name='relatoriopersonalizado',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='indicadorkpi',
            name='categoria',
        ),
        migrations.AlterUniqueTogether(
            name='dashboardkpi',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='dashboardkpi',
            name='dashboard',
        ),
        migrations.RemoveField(
            model_name='dashboardkpi',
            name='kpi',
        ),
        migrations.RemoveField(
            model_name='dashboardpersonalizado',
            name='kpis',
        ),
        migrations.RemoveField(
            model_name='dashboardpersonalizado',
            name='relatorios',
        ),
        migrations.RemoveField(
            model_name='dashboardrelatorio',
            name='dashboard',
        ),
        migrations.RemoveField(
            model_name='dashboardrelatorio',
            name='relatorio',
        ),
        migrations.RemoveField(
            model_name='logexecucaorelatorio',
            name='relatorio',
        ),
        migrations.CreateModel(
            name='ConfiguracaoRelatorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_relatorios_por_usuario', models.IntegerField(default=100, verbose_name='Máximo de Relatórios por Usuário')),
                ('max_tamanho_arquivo', models.IntegerField(default=50, verbose_name='Tamanho Máximo de Arquivo (MB)')),
                ('tempo_maximo_processamento', models.IntegerField(default=30, verbose_name='Tempo Máximo de Processamento (minutos)')),
                ('dias_retencao_relatorios', models.IntegerField(default=365, verbose_name='Dias de Retenção')),
                ('dias_retencao_agendados', models.IntegerField(default=730, verbose_name='Dias de Retenção Agendados')),
                ('notificar_conclusao', models.BooleanField(default=True, verbose_name='Notificar Conclusão')),
                ('notificar_erro', models.BooleanField(default=True, verbose_name='Notificar Erro')),
                ('formato_padrao', models.CharField(choices=[('PDF', 'PDF'), ('EXCEL', 'Excel'), ('CSV', 'CSV'), ('JSON', 'JSON'), ('HTML', 'HTML')], default='PDF', max_length=10, verbose_name='Formato Padrão')),
                ('compressao_arquivos', models.BooleanField(default=True, verbose_name='Comprimir Arquivos')),
                ('data_configuracao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Configuração')),
                ('configurado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='configuracoes_relatorios', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Configuração de Relatório',
                'verbose_name_plural': 'Configurações de Relatórios',
            },
        ),
        migrations.CreateModel(
            name='Relatorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('parametros', models.JSONField(blank=True, default=dict, verbose_name='Parâmetros')),
                ('filtros', models.JSONField(blank=True, default=dict, verbose_name='Filtros')),
                ('formato', models.CharField(choices=[('PDF', 'PDF'), ('EXCEL', 'Excel'), ('CSV', 'CSV'), ('JSON', 'JSON'), ('HTML', 'HTML')], default='PDF', max_length=10, verbose_name='Formato')),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('EM_PROCESSAMENTO', 'Em Processamento'), ('CONCLUIDO', 'Concluído'), ('ERRO', 'Erro'), ('CANCELADO', 'Cancelado')], default='PENDENTE', max_length=20, verbose_name='Status')),
                ('progresso', models.IntegerField(default=0, verbose_name='Progresso (%)')),
                ('data_solicitacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Solicitação')),
                ('data_conclusao', models.DateTimeField(blank=True, null=True, verbose_name='Data de Conclusão')),
                ('arquivo', models.FileField(blank=True, null=True, upload_to='relatorios/', verbose_name='Arquivo')),
                ('nome_arquivo', models.CharField(blank=True, max_length=255, verbose_name='Nome do Arquivo')),
                ('tamanho_arquivo', models.IntegerField(blank=True, null=True, verbose_name='Tamanho (bytes)')),
                ('tempo_processamento', models.FloatField(blank=True, null=True, verbose_name='Tempo de Processamento (segundos)')),
                ('registros_processados', models.IntegerField(blank=True, null=True, verbose_name='Registros Processados')),
                ('erro_mensagem', models.TextField(blank=True, verbose_name='Mensagem de Erro')),
                ('solicitado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relatorios_solicitados', to=settings.AUTH_USER_MODEL)),
                ('tipo_relatorio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relatorios', to='relatorios.tiporelatorio')),
            ],
            options={
                'verbose_name': 'Relatório',
                'verbose_name_plural': 'Relatórios',
                'ordering': ['-data_solicitacao'],
            },
        ),
        migrations.CreateModel(
            name='HistoricoRelatorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('EM_PROCESSAMENTO', 'Em Processamento'), ('CONCLUIDO', 'Concluído'), ('ERRO', 'Erro'), ('CANCELADO', 'Cancelado')], max_length=20, verbose_name='Status')),
                ('tempo_processamento', models.FloatField(blank=True, null=True, verbose_name='Tempo de Processamento (segundos)')),
                ('registros_processados', models.IntegerField(blank=True, null=True, verbose_name='Registros Processados')),
                ('erro_mensagem', models.TextField(blank=True, verbose_name='Mensagem de Erro')),
                ('data_execucao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Execução')),
                ('ip_origem', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP de Origem')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='execucoes_relatorios', to=settings.AUTH_USER_MODEL)),
                ('relatorio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico', to='relatorios.relatorio')),
            ],
            options={
                'verbose_name': 'Histórico de Relatório',
                'verbose_name_plural': 'Históricos de Relatórios',
                'ordering': ['-data_execucao'],
            },
        ),
        migrations.CreateModel(
            name='RelatorioCompartilhado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pode_visualizar', models.BooleanField(default=True, verbose_name='Pode Visualizar')),
                ('pode_baixar', models.BooleanField(default=True, verbose_name='Pode Baixar')),
                ('pode_compartilhar', models.BooleanField(default=False, verbose_name='Pode Compartilhar')),
                ('data_compartilhamento', models.DateTimeField(auto_now_add=True, verbose_name='Data de Compartilhamento')),
                ('data_expiracao', models.DateTimeField(blank=True, null=True, verbose_name='Data de Expiração')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('compartilhado_com', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relatorios_recebidos', to=settings.AUTH_USER_MODEL)),
                ('compartilhado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relatorios_compartilhados', to=settings.AUTH_USER_MODEL)),
                ('relatorio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compartilhamentos', to='relatorios.relatorio')),
            ],
            options={
                'verbose_name': 'Relatório Compartilhado',
                'verbose_name_plural': 'Relatórios Compartilhados',
                'unique_together': {('relatorio', 'compartilhado_com')},
            },
        ),
        migrations.CreateModel(
            name='TemplateRelatorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('configuracao', models.JSONField(default=dict, verbose_name='Configuração')),
                ('layout', models.TextField(blank=True, verbose_name='Layout HTML')),
                ('css', models.TextField(blank=True, verbose_name='CSS')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('padrao', models.BooleanField(default=False, verbose_name='Padrão')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='templates_criados', to=settings.AUTH_USER_MODEL)),
                ('tipo_relatorio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='templates', to='relatorios.tiporelatorio')),
            ],
            options={
                'verbose_name': 'Template de Relatório',
                'verbose_name_plural': 'Templates de Relatórios',
            },
        ),
        migrations.CreateModel(
            name='RelatorioAgendado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('parametros', models.JSONField(blank=True, default=dict, verbose_name='Parâmetros')),
                ('filtros', models.JSONField(blank=True, default=dict, verbose_name='Filtros')),
                ('formato', models.CharField(choices=[('PDF', 'PDF'), ('EXCEL', 'Excel'), ('CSV', 'CSV'), ('JSON', 'JSON'), ('HTML', 'HTML')], default='PDF', max_length=10, verbose_name='Formato')),
                ('frequencia', models.CharField(choices=[('DIARIA', 'Diária'), ('SEMANAL', 'Semanal'), ('MENSAL', 'Mensal'), ('TRIMESTRAL', 'Trimestral'), ('SEMESTRAL', 'Semestral'), ('ANUAL', 'Anual')], max_length=20, verbose_name='Frequência')),
                ('proxima_execucao', models.DateTimeField(verbose_name='Próxima Execução')),
                ('ultima_execucao', models.DateTimeField(blank=True, null=True, verbose_name='Última Execução')),
                ('status', models.CharField(choices=[('ATIVO', 'Ativo'), ('INATIVO', 'Inativo'), ('PAUSADO', 'Pausado')], default='ATIVO', max_length=20, verbose_name='Status')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('data_modificacao', models.DateTimeField(auto_now=True, verbose_name='Data de Modificação')),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relatorios_agendados', to=settings.AUTH_USER_MODEL)),
                ('tipo_relatorio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agendamentos', to='relatorios.tiporelatorio')),
            ],
            options={
                'verbose_name': 'Relatório Agendado',
                'verbose_name_plural': 'Relatórios Agendados',
                'ordering': ['proxima_execucao'],
            },
        ),
        migrations.CreateModel(
            name='FiltroRelatorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('tipo_filtro', models.CharField(choices=[('TEXTO', 'Texto'), ('NUMERO', 'Número'), ('DATA', 'Data'), ('SELECT', 'Seleção'), ('MULTISELECT', 'Múltipla Seleção'), ('BOOLEAN', 'Booleano'), ('RANGE', 'Intervalo')], max_length=20, verbose_name='Tipo de Filtro')),
                ('campo', models.CharField(max_length=100, verbose_name='Campo')),
                ('opcoes', models.JSONField(blank=True, default=list, verbose_name='Opções')),
                ('obrigatorio', models.BooleanField(default=False, verbose_name='Obrigatório')),
                ('valor_padrao', models.CharField(blank=True, max_length=200, verbose_name='Valor Padrão')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('ordem', models.IntegerField(default=0, verbose_name='Ordem')),
                ('tipo_relatorio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filtros', to='relatorios.tiporelatorio')),
            ],
            options={
                'verbose_name': 'Filtro de Relatório',
                'verbose_name_plural': 'Filtros de Relatórios',
                'ordering': ['tipo_relatorio', 'ordem'],
            },
        ),
        migrations.DeleteModel(
            name='AgendamentoRelatorio',
        ),
        migrations.DeleteModel(
            name='CategoriaRelatorio',
        ),
        migrations.DeleteModel(
            name='DashboardKPI',
        ),
        migrations.DeleteModel(
            name='IndicadorKPI',
        ),
        migrations.DeleteModel(
            name='DashboardPersonalizado',
        ),
        migrations.DeleteModel(
            name='DashboardRelatorio',
        ),
        migrations.DeleteModel(
            name='LogExecucaoRelatorio',
        ),
        migrations.DeleteModel(
            name='RelatorioPersonalizado',
        ),
    ]
