# Generated by Django 5.2.5 on 2025-08-25 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('relatorios', '0002_tiporelatorio_and_more'),
    ]

    operations = [
    ]
