# Generated by Django 5.2.5 on 2025-09-01 00:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiscalizacao', '0006_alter_notificacaoeletronica_destinatario_email'),
        ('portal_cidadao', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DenunciaCidadao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_denuncia', models.CharField(blank=True, max_length=20, unique=True, verbose_name='Número da Denúncia')),
                ('empresa_denunciada', models.CharField(max_length=255, verbose_name='Empresa Denunciada')),
                ('cnpj_empresa', models.CharField(blank=True, max_length=18, verbose_name='CNPJ da Empresa')),
                ('endereco_empresa', models.CharField(blank=True, max_length=500, verbose_name='Endereço da Empresa')),
                ('telefone_empresa', models.CharField(blank=True, max_length=20, verbose_name='Telefone da Empresa')),
                ('email_empresa', models.EmailField(blank=True, max_length=254, verbose_name='E-mail da Empresa')),
                ('descricao_fatos', models.TextField(verbose_name='Descrição dos Fatos')),
                ('data_ocorrencia', models.DateField(blank=True, null=True, verbose_name='Data da Ocorrência')),
                ('tipo_infracao', models.CharField(default='outros', max_length=100, verbose_name='Tipo de Infração')),
                ('nome_denunciante', models.CharField(max_length=255, verbose_name='Nome do Denunciante')),
                ('cpf_cnpj', models.CharField(max_length=20, verbose_name='CPF/CNPJ do Denunciante')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail do Denunciante')),
                ('telefone', models.CharField(blank=True, max_length=20, verbose_name='Telefone do Denunciante')),
                ('status', models.CharField(choices=[('denuncia_recebida', 'Denúncia Recebida'), ('em_analise', 'Em Análise'), ('encaminhada_fiscal', 'Encaminhada para Fiscal'), ('auto_criado', 'Auto de Infração Criado'), ('arquivada', 'Arquivada')], default='denuncia_recebida', max_length=20, verbose_name='Status')),
                ('origem_denuncia', models.CharField(default='PORTAL_CIDADAO', max_length=20, verbose_name='Origem da Denúncia')),
                ('ip_origem', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP de Origem')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('auto_infracao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='denuncias_cidadao', to='fiscalizacao.autoinfracao')),
            ],
            options={
                'verbose_name': 'Denúncia do Cidadão',
                'verbose_name_plural': 'Denúncias do Cidadão',
                'ordering': ['-criado_em'],
                'indexes': [models.Index(fields=['numero_denuncia'], name='portal_cida_numero__9e0f64_idx'), models.Index(fields=['status'], name='portal_cida_status_d2b389_idx'), models.Index(fields=['origem_denuncia'], name='portal_cida_origem__4d6c6c_idx'), models.Index(fields=['criado_em'], name='portal_cida_criado__fd96e5_idx')],
            },
        ),
    ]
