# Generated by Django 5.2.5 on 2025-09-01 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal_cidadao', '0002_denunciacidadao'),
    ]

    operations = [
        migrations.AddField(
            model_name='denunciacidadao',
            name='denuncia_anonima',
            field=models.BooleanField(default=False, verbose_name='Denúncia Anônima'),
        ),
        migrations.AddField(
            model_name='denunciacidadao',
            name='motivo_anonimato',
            field=models.TextField(blank=True, verbose_name='Motivo do Anonimato'),
        ),
        migrations.AlterField(
            model_name='denunciacidadao',
            name='cpf_cnpj',
            field=models.CharField(blank=True, max_length=20, verbose_name='CPF/CNPJ do Denunciante'),
        ),
        migrations.AlterField(
            model_name='denunciacidadao',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='E-mail do Denunciante'),
        ),
        migrations.AlterField(
            model_name='denunciacidadao',
            name='nome_denunciante',
            field=models.CharField(blank=True, max_length=255, verbose_name='Nome do Denunciante'),
        ),
    ]
