# Generated by Django 5.2.5 on 2025-09-01 01:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal_cidadao', '0003_denunciacidadao_denuncia_anonima_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='denunciacidadao',
            name='motivo_anonimato',
        ),
    ]
