# Generated by Django 5.2.5 on 2025-10-15 00:27

import portal_cidadao.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal_cidadao', '0003_reclamacaodenuncia_historicoreclamacao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='anexoreclamacao',
            name='armazenamento_origem',
            field=models.CharField(default='local', editable=False, max_length=50, verbose_name='Origem Armazenamento'),
        ),
        migrations.AddField(
            model_name='anexoreclamacao',
            name='checksum_sha256',
            field=models.CharField(blank=True, editable=False, max_length=64, verbose_name='Checksum SHA256'),
        ),
        migrations.AddField(
            model_name='anexoreclamacao',
            name='content_type',
            field=models.CharField(blank=True, editable=False, max_length=120, verbose_name='MIME Type'),
        ),
        migrations.AddField(
            model_name='anexoreclamacao',
            name='removido_em',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Removido em'),
        ),
        migrations.AddField(
            model_name='anexoreclamacao',
            name='tamanho_bytes',
            field=models.BigIntegerField(default=0, editable=False, verbose_name='Tamanho (bytes)'),
        ),
        migrations.AlterField(
            model_name='anexoreclamacao',
            name='arquivo',
            field=models.FileField(blank=True, null=True, upload_to=portal_cidadao.models.anexo_reclamacao_upload_path, verbose_name='Arquivo'),
        ),
    ]
