# Generated by Django 5.2.5 on 2025-09-01 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal_cidadao', '0004_remove_motivo_anonimato'),
    ]

    operations = [
        migrations.AddField(
            model_name='denunciacidadao',
            name='motivo_anonimato',
            field=models.TextField(blank=True, verbose_name='Motivo do Anonimato'),
        ),
    ]
