# Generated by Django 5.2.5 on 2025-10-21 14:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiscalizacao', '0002_mobiledevicetoken_mobileupload_and_more'),
        ('portal_cidadao', '0006_reclamacaodenuncia_ata_conciliacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reclamacaodenuncia',
            name='auto_infracao_relacionado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reclamacoes_origem', to='fiscalizacao.autoinfracao'),
        ),
    ]
