# Generated by Django 4.2.11 on 2025-11-14 01:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('portal_cidadao', '0007_alter_reclamacaodenuncia_auto_infracao_relacionado'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricoAtividade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificador', models.CharField(blank=True, max_length=255, verbose_name='Identificador (Email/CPF)')),
                ('tipo', models.CharField(choices=[('denuncia', 'Denúncia'), ('consulta', 'Consulta'), ('peticao', 'Petição'), ('download', 'Download'), ('contato', 'Contato')], max_length=20, verbose_name='Tipo')),
                ('titulo', models.CharField(max_length=255, verbose_name='Título')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('numero_protocolo', models.CharField(blank=True, max_length=50, verbose_name='Número do Protocolo')),
                ('denuncia_id', models.IntegerField(blank=True, null=True, verbose_name='ID da Denúncia')),
                ('peticao_id', models.IntegerField(blank=True, null=True, verbose_name='ID da Petição')),
                ('ip_origem', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP de Origem')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='historico_atividades', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Histórico de Atividade',
                'verbose_name_plural': 'Histórico de Atividades',
                'ordering': ['-criado_em'],
                'indexes': [models.Index(fields=['usuario', '-criado_em'], name='portal_cida_usuario_15f262_idx'), models.Index(fields=['identificador', '-criado_em'], name='portal_cida_identif_2f9a55_idx'), models.Index(fields=['tipo', '-criado_em'], name='portal_cida_tipo_1c8eab_idx')],
            },
        ),
    ]
