# Generated by Django 4.2.11 on 2026-01-15 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal_cidadao', '0009_denuncia_resposta_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='denunciacidadao',
            name='status',
            field=models.CharField(choices=[('denuncia_recebida', 'Denúncia Recebida'), ('em_analise', 'Em Análise'), ('encaminhada_fiscal', 'Encaminhada para Fiscal'), ('auto_criado', 'Auto de Infração Criado'), ('arquivada', 'Arquivada'), ('respondida', 'Respondida')], default='denuncia_recebida', max_length=20, verbose_name='Status'),
        ),
    ]
