# Generated by Codex on 2026-02-04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portal_cidadao", "0010_alter_denunciacidadao_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="denunciacidadao",
            name="destino_denuncia",
            field=models.CharField(
                choices=[
                    ("FISCALIZACAO", "Fiscalização"),
                    ("ATENDIMENTO", "Atendimento"),
                ],
                default="FISCALIZACAO",
                max_length=20,
                verbose_name="Destino da Denúncia",
            ),
        ),
    ]

