# Generated by Django 5.2.5 on 2025-08-25 00:51

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('multas', '0002_alter_multa_options_multa_atualizado_em_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoCobranca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prazo_vencimento_boleto', models.IntegerField(default=30, verbose_name='Prazo Vencimento Boleto (dias)')),
                ('prazo_primeira_cobranca', models.IntegerField(default=15, verbose_name='Primeira Cobrança (dias)')),
                ('prazo_segunda_cobranca', models.IntegerField(default=30, verbose_name='Segunda Cobrança (dias)')),
                ('prazo_terceira_cobranca', models.IntegerField(default=45, verbose_name='Terceira Cobrança (dias)')),
                ('taxa_juros_mensal', models.DecimalField(decimal_places=2, default=1.0, max_digits=5, verbose_name='Taxa de Juros Mensal (%)')),
                ('taxa_multa_atraso', models.DecimalField(decimal_places=2, default=2.0, max_digits=5, verbose_name='Multa por Atraso (%)')),
                ('beneficiario_nome', models.CharField(default='PROCON', max_length=255, verbose_name='Nome do Beneficiário')),
                ('beneficiario_cnpj', models.CharField(max_length=18, verbose_name='CNPJ do Beneficiário')),
                ('beneficiario_endereco', models.TextField(verbose_name='Endereço do Beneficiário')),
                ('banco_codigo', models.CharField(default='001', max_length=3, verbose_name='Código do Banco')),
                ('banco_nome', models.CharField(default='Banco do Brasil', max_length=100, verbose_name='Nome do Banco')),
                ('agencia', models.CharField(max_length=10, verbose_name='Agência')),
                ('conta', models.CharField(max_length=15, verbose_name='Conta')),
                ('carteira', models.CharField(default='18', max_length=10, verbose_name='Carteira')),
                ('enviar_boleto_email', models.BooleanField(default=True, verbose_name='Enviar Boleto por E-mail')),
                ('enviar_cobranca_sms', models.BooleanField(default=False, verbose_name='Enviar Cobrança por SMS')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Configuração de Cobrança',
                'verbose_name_plural': 'Configurações de Cobrança',
            },
        ),
        migrations.CreateModel(
            name='BoletoMulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('numero_boleto', models.CharField(blank=True, max_length=20, unique=True, verbose_name='Número do Boleto')),
                ('nosso_numero', models.CharField(blank=True, max_length=20, verbose_name='Nosso Número')),
                ('pagador_nome', models.CharField(max_length=255, verbose_name='Nome do Pagador')),
                ('pagador_documento', models.CharField(max_length=18, verbose_name='CPF/CNPJ')),
                ('pagador_endereco', models.TextField(verbose_name='Endereço')),
                ('pagador_email', models.EmailField(blank=True, max_length=254, verbose_name='E-mail')),
                ('pagador_telefone', models.CharField(blank=True, max_length=20, verbose_name='Telefone')),
                ('valor_principal', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Valor Principal')),
                ('valor_juros', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Valor Juros')),
                ('valor_multa', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Valor Multa')),
                ('valor_desconto', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Valor Desconto')),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor Total')),
                ('data_emissao', models.DateField(auto_now_add=True, verbose_name='Data de Emissão')),
                ('data_vencimento', models.DateField(verbose_name='Data de Vencimento')),
                ('data_pagamento', models.DateTimeField(blank=True, null=True, verbose_name='Data de Pagamento')),
                ('data_envio', models.DateTimeField(blank=True, null=True, verbose_name='Data de Envio')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('enviado', 'Enviado'), ('pago', 'Pago'), ('vencido', 'Vencido'), ('cancelado', 'Cancelado'), ('protestado', 'Protestado')], default='pendente', max_length=15, verbose_name='Status')),
                ('forma_pagamento', models.CharField(blank=True, choices=[('boleto', 'Boleto Bancário'), ('pix', 'PIX'), ('cartao', 'Cartão'), ('dinheiro', 'Dinheiro'), ('transferencia', 'Transferência')], max_length=15, verbose_name='Forma de Pagamento')),
                ('codigo_barras', models.CharField(blank=True, max_length=54, verbose_name='Código de Barras')),
                ('linha_digitavel', models.CharField(blank=True, max_length=54, verbose_name='Linha Digitável')),
                ('instrucoes', models.TextField(blank=True, verbose_name='Instruções')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('pix_codigo', models.TextField(blank=True, verbose_name='Código PIX')),
                ('pix_qr_code', models.ImageField(blank=True, upload_to='cobranca/pix/%Y/%m/', verbose_name='QR Code PIX')),
                ('tentativas_envio', models.IntegerField(default=0, verbose_name='Tentativas de Envio')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('criado_por', models.CharField(blank=True, max_length=100, verbose_name='Criado por')),
                ('multa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boletos', to='multas.multa', verbose_name='Multa')),
            ],
            options={
                'verbose_name': 'Boleto de Multa',
                'verbose_name_plural': 'Boletos de Multas',
                'ordering': ['-data_emissao'],
            },
        ),
        migrations.CreateModel(
            name='CobrancaMulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_cobranca', models.CharField(choices=[('primeira', 'Primeira Cobrança'), ('segunda', 'Segunda Cobrança'), ('terceira', 'Terceira Cobrança'), ('final', 'Cobrança Final'), ('protesto', 'Aviso de Protesto')], max_length=15, verbose_name='Tipo de Cobrança')),
                ('canal', models.CharField(choices=[('email', 'E-mail'), ('sms', 'SMS'), ('correios', 'Correios'), ('whatsapp', 'WhatsApp'), ('oficial', 'Oficial de Justiça')], max_length=15, verbose_name='Canal')),
                ('data_agendamento', models.DateTimeField(verbose_name='Data de Agendamento')),
                ('data_envio', models.DateTimeField(blank=True, null=True, verbose_name='Data de Envio')),
                ('data_entrega', models.DateTimeField(blank=True, null=True, verbose_name='Data de Entrega')),
                ('assunto', models.CharField(max_length=255, verbose_name='Assunto')),
                ('mensagem', models.TextField(verbose_name='Mensagem')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('enviada', 'Enviada'), ('entregue', 'Entregue'), ('falhada', 'Falhada')], default='pendente', max_length=15, verbose_name='Status')),
                ('tentativas', models.IntegerField(default=0, verbose_name='Tentativas')),
                ('max_tentativas', models.IntegerField(default=3, verbose_name='Máximo Tentativas')),
                ('log_envio', models.TextField(blank=True, verbose_name='Log de Envio')),
                ('erro_envio', models.TextField(blank=True, verbose_name='Erro de Envio')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('criado_por', models.CharField(blank=True, max_length=100, verbose_name='Criado por')),
                ('boleto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cobrancas', to='cobranca.boletomulta', verbose_name='Boleto')),
            ],
            options={
                'verbose_name': 'Cobrança de Multa',
                'verbose_name_plural': 'Cobranças de Multas',
                'ordering': ['-data_agendamento'],
            },
        ),
        migrations.CreateModel(
            name='PagamentoMulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('numero_pagamento', models.CharField(blank=True, max_length=20, unique=True, verbose_name='Número do Pagamento')),
                ('valor_pago', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Valor Pago')),
                ('forma_pagamento', models.CharField(choices=[('boleto', 'Boleto Bancário'), ('pix', 'PIX'), ('cartao', 'Cartão'), ('dinheiro', 'Dinheiro'), ('transferencia', 'Transferência')], max_length=15, verbose_name='Forma de Pagamento')),
                ('data_pagamento', models.DateTimeField(verbose_name='Data do Pagamento')),
                ('comprovante', models.FileField(blank=True, upload_to='cobranca/comprovantes/%Y/%m/', verbose_name='Comprovante')),
                ('numero_transacao', models.CharField(blank=True, max_length=100, verbose_name='Número da Transação')),
                ('status', models.CharField(choices=[('pendente', 'Pendente Confirmação'), ('confirmado', 'Confirmado'), ('rejeitado', 'Rejeitado'), ('estornado', 'Estornado')], default='pendente', max_length=15, verbose_name='Status')),
                ('data_confirmacao', models.DateTimeField(blank=True, null=True, verbose_name='Data de Confirmação')),
                ('confirmado_por', models.CharField(blank=True, max_length=100, verbose_name='Confirmado por')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('motivo_rejeicao', models.TextField(blank=True, verbose_name='Motivo da Rejeição')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('criado_por', models.CharField(blank=True, max_length=100, verbose_name='Criado por')),
                ('boleto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagamentos', to='cobranca.boletomulta', verbose_name='Boleto')),
            ],
            options={
                'verbose_name': 'Pagamento de Multa',
                'verbose_name_plural': 'Pagamentos de Multas',
                'ordering': ['-data_pagamento'],
            },
        ),
        migrations.CreateModel(
            name='LogCobranca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acao', models.CharField(choices=[('boleto_gerado', 'Boleto Gerado'), ('boleto_enviado', 'Boleto Enviado'), ('cobranca_enviada', 'Cobrança Enviada'), ('pagamento_registrado', 'Pagamento Registrado'), ('pagamento_confirmado', 'Pagamento Confirmado'), ('boleto_cancelado', 'Boleto Cancelado'), ('erro_envio', 'Erro no Envio')], max_length=25, verbose_name='Ação')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('dados_extras', models.JSONField(blank=True, default=dict, verbose_name='Dados Extras')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Timestamp')),
                ('usuario', models.CharField(blank=True, max_length=100, verbose_name='Usuário')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Address')),
                ('boleto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='cobranca.boletomulta')),
                ('cobranca', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='cobranca.cobrancamulta')),
                ('pagamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='cobranca.pagamentomulta')),
            ],
            options={
                'verbose_name': 'Log de Cobrança',
                'verbose_name_plural': 'Logs de Cobrança',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='TemplateCobranca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Nome')),
                ('tipo_cobranca', models.CharField(choices=[('primeira', 'Primeira Cobrança'), ('segunda', 'Segunda Cobrança'), ('terceira', 'Terceira Cobrança'), ('final', 'Cobrança Final'), ('protesto', 'Aviso de Protesto')], max_length=15, verbose_name='Tipo de Cobrança')),
                ('canal', models.CharField(choices=[('email', 'E-mail'), ('sms', 'SMS'), ('correios', 'Correios'), ('whatsapp', 'WhatsApp'), ('oficial', 'Oficial de Justiça')], max_length=15, verbose_name='Canal')),
                ('assunto_template', models.CharField(max_length=255, verbose_name='Template do Assunto')),
                ('mensagem_template', models.TextField(verbose_name='Template da Mensagem')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('padrao', models.BooleanField(default=False, verbose_name='Padrão')),
                ('variaveis_disponiveis', models.TextField(default='{{nome}}, {{valor}}, {{vencimento}}, {{numero_boleto}}, {{dias_atraso}}', help_text='Lista das variáveis que podem ser usadas', verbose_name='Variáveis Disponíveis')),
            ],
            options={
                'verbose_name': 'Template de Cobrança',
                'verbose_name_plural': 'Templates de Cobrança',
                'ordering': ['tipo_cobranca', 'nome'],
                'unique_together': {('tipo_cobranca', 'canal', 'padrao')},
            },
        ),
        migrations.AddIndex(
            model_name='boletomulta',
            index=models.Index(fields=['numero_boleto'], name='cobranca_bo_numero__f772b5_idx'),
        ),
        migrations.AddIndex(
            model_name='boletomulta',
            index=models.Index(fields=['multa'], name='cobranca_bo_multa_i_0e3880_idx'),
        ),
        migrations.AddIndex(
            model_name='boletomulta',
            index=models.Index(fields=['status'], name='cobranca_bo_status_1811af_idx'),
        ),
        migrations.AddIndex(
            model_name='boletomulta',
            index=models.Index(fields=['data_vencimento'], name='cobranca_bo_data_ve_cc40a6_idx'),
        ),
        migrations.AddIndex(
            model_name='boletomulta',
            index=models.Index(fields=['pagador_documento'], name='cobranca_bo_pagador_39db42_idx'),
        ),
        migrations.AddIndex(
            model_name='cobrancamulta',
            index=models.Index(fields=['boleto'], name='cobranca_co_boleto__1cec53_idx'),
        ),
        migrations.AddIndex(
            model_name='cobrancamulta',
            index=models.Index(fields=['tipo_cobranca'], name='cobranca_co_tipo_co_55c0dd_idx'),
        ),
        migrations.AddIndex(
            model_name='cobrancamulta',
            index=models.Index(fields=['status'], name='cobranca_co_status_0c3295_idx'),
        ),
        migrations.AddIndex(
            model_name='cobrancamulta',
            index=models.Index(fields=['data_agendamento'], name='cobranca_co_data_ag_4c6470_idx'),
        ),
        migrations.AddIndex(
            model_name='pagamentomulta',
            index=models.Index(fields=['numero_pagamento'], name='cobranca_pa_numero__1a3c55_idx'),
        ),
        migrations.AddIndex(
            model_name='pagamentomulta',
            index=models.Index(fields=['boleto'], name='cobranca_pa_boleto__b59a36_idx'),
        ),
        migrations.AddIndex(
            model_name='pagamentomulta',
            index=models.Index(fields=['status'], name='cobranca_pa_status_235317_idx'),
        ),
        migrations.AddIndex(
            model_name='pagamentomulta',
            index=models.Index(fields=['data_pagamento'], name='cobranca_pa_data_pa_d212b5_idx'),
        ),
        migrations.AddIndex(
            model_name='logcobranca',
            index=models.Index(fields=['boleto', 'timestamp'], name='cobranca_lo_boleto__ebdf57_idx'),
        ),
        migrations.AddIndex(
            model_name='logcobranca',
            index=models.Index(fields=['acao', 'timestamp'], name='cobranca_lo_acao_7390d6_idx'),
        ),
    ]
