# Generated by Django 4.2.11 on 2025-09-21 04:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('multas', '0001_initial'),
        ('cobranca', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='boletomulta',
            name='multa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boletos', to='multas.multa', verbose_name='Multa'),
        ),
        migrations.AddIndex(
            model_name='remessa',
            index=models.Index(fields=['numero'], name='cobranca_re_numero_bb7a76_idx'),
        ),
        migrations.AddIndex(
            model_name='remessa',
            index=models.Index(fields=['banco'], name='cobranca_re_banco_i_b671c7_idx'),
        ),
        migrations.AddIndex(
            model_name='remessa',
            index=models.Index(fields=['status'], name='cobranca_re_status_9098f4_idx'),
        ),
        migrations.AddIndex(
            model_name='remessa',
            index=models.Index(fields=['data_geracao'], name='cobranca_re_data_ge_cfcc42_idx'),
        ),
        migrations.AddIndex(
            model_name='pagamentomulta',
            index=models.Index(fields=['numero_pagamento'], name='cobranca_pa_numero__1a3c55_idx'),
        ),
        migrations.AddIndex(
            model_name='pagamentomulta',
            index=models.Index(fields=['boleto'], name='cobranca_pa_boleto__b59a36_idx'),
        ),
        migrations.AddIndex(
            model_name='pagamentomulta',
            index=models.Index(fields=['status'], name='cobranca_pa_status_235317_idx'),
        ),
        migrations.AddIndex(
            model_name='pagamentomulta',
            index=models.Index(fields=['data_pagamento'], name='cobranca_pa_data_pa_d212b5_idx'),
        ),
        migrations.AddIndex(
            model_name='logcobranca',
            index=models.Index(fields=['boleto', 'timestamp'], name='cobranca_lo_boleto__ebdf57_idx'),
        ),
        migrations.AddIndex(
            model_name='logcobranca',
            index=models.Index(fields=['acao', 'timestamp'], name='cobranca_lo_acao_7390d6_idx'),
        ),
        migrations.AddIndex(
            model_name='cobrancamulta',
            index=models.Index(fields=['boleto'], name='cobranca_co_boleto__1cec53_idx'),
        ),
        migrations.AddIndex(
            model_name='cobrancamulta',
            index=models.Index(fields=['tipo_cobranca'], name='cobranca_co_tipo_co_55c0dd_idx'),
        ),
        migrations.AddIndex(
            model_name='cobrancamulta',
            index=models.Index(fields=['status'], name='cobranca_co_status_0c3295_idx'),
        ),
        migrations.AddIndex(
            model_name='cobrancamulta',
            index=models.Index(fields=['data_agendamento'], name='cobranca_co_data_ag_4c6470_idx'),
        ),
        migrations.AddIndex(
            model_name='boletomulta',
            index=models.Index(fields=['numero_boleto'], name='cobranca_bo_numero__f772b5_idx'),
        ),
        migrations.AddIndex(
            model_name='boletomulta',
            index=models.Index(fields=['multa'], name='cobranca_bo_multa_i_0e3880_idx'),
        ),
        migrations.AddIndex(
            model_name='boletomulta',
            index=models.Index(fields=['status'], name='cobranca_bo_status_1811af_idx'),
        ),
        migrations.AddIndex(
            model_name='boletomulta',
            index=models.Index(fields=['data_vencimento'], name='cobranca_bo_data_ve_cc40a6_idx'),
        ),
        migrations.AddIndex(
            model_name='boletomulta',
            index=models.Index(fields=['pagador_documento'], name='cobranca_bo_pagador_39db42_idx'),
        ),
    ]
