# Generated by Django 4.2.11 on 2025-08-30 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cobranca', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=3, unique=True, verbose_name='Código')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Banco',
                'verbose_name_plural': 'Bancos',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Remessa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=20, unique=True, verbose_name='Número da Remessa')),
                ('tipo', models.CharField(choices=[('remessa', 'Remessa'), ('retorno', 'Retorno')], default='remessa', max_length=10, verbose_name='Tipo')),
                ('quantidade_boletos', models.IntegerField(default=0, verbose_name='Quantidade de Boletos')),
                ('valor_total', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Valor Total')),
                ('arquivo_remessa', models.FileField(blank=True, upload_to='cobranca/remessas/%Y/%m/', verbose_name='Arquivo de Remessa')),
                ('arquivo_retorno', models.FileField(blank=True, upload_to='cobranca/retornos/%Y/%m/', verbose_name='Arquivo de Retorno')),
                ('data_geracao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Geração')),
                ('data_envio', models.DateTimeField(blank=True, null=True, verbose_name='Data de Envio')),
                ('data_processamento', models.DateTimeField(blank=True, null=True, verbose_name='Data de Processamento')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('gerado', 'Gerado'), ('enviado', 'Enviado ao Banco'), ('processado', 'Processado'), ('erro', 'Erro'), ('cancelado', 'Cancelado')], default='pendente', max_length=15, verbose_name='Status')),
                ('sequencial', models.IntegerField(default=1, verbose_name='Sequencial')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('erro_processamento', models.TextField(blank=True, verbose_name='Erro de Processamento')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('criado_por', models.CharField(blank=True, max_length=100, verbose_name='Criado por')),
                ('banco', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cobranca.banco', verbose_name='Banco')),
            ],
            options={
                'verbose_name': 'Remessa',
                'verbose_name_plural': 'Remessas',
                'ordering': ['-data_geracao'],
                'indexes': [models.Index(fields=['numero'], name='cobranca_re_numero_bb7a76_idx'), models.Index(fields=['banco'], name='cobranca_re_banco_i_b671c7_idx'), models.Index(fields=['status'], name='cobranca_re_status_9098f4_idx'), models.Index(fields=['data_geracao'], name='cobranca_re_data_ge_cfcc42_idx')],
            },
        ),
    ]
