# Generated by Django 5.2.5 on 2026-01-28 21:18

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cobranca', '0002_initial'),
        ('fiscalizacao', '0020_alter_documentoprocesso_tipo'),
        ('multas', '0003_alter_multa_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuiaRecolhimentoMulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_guia', models.CharField(blank=True, max_length=30, unique=True, verbose_name='Número da Guia')),
                ('departamento_emissor', models.CharField(default='DAF', max_length=50, verbose_name='Departamento Emissor')),
                ('recebedor_nome', models.CharField(default='Instituto de Defesa do Consumidor - PROCON AM', max_length=255, verbose_name='Recebedor')),
                ('recebedor_cnpj', models.CharField(blank=True, max_length=18, verbose_name='CNPJ Recebedor')),
                ('banco_nome', models.CharField(blank=True, max_length=100, verbose_name='Banco')),
                ('banco_agencia', models.CharField(blank=True, max_length=20, verbose_name='Agência')),
                ('banco_conta', models.CharField(blank=True, max_length=30, verbose_name='Conta')),
                ('autuado_nome', models.CharField(blank=True, max_length=255, verbose_name='Autuado')),
                ('autuado_documento', models.CharField(blank=True, max_length=18, verbose_name='CPF/CNPJ Autuado')),
                ('numero_auto_infracao', models.CharField(blank=True, max_length=30, verbose_name='Número do Auto de Infração')),
                ('numero_processo', models.CharField(blank=True, max_length=50, verbose_name='Número do Processo')),
                ('valor_integral', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Valor Integral')),
                ('valor_a_vista', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Valor à Vista')),
                ('valor_parcelado', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Valor Parcelado')),
                ('quantidade_parcelas', models.IntegerField(blank=True, null=True, verbose_name='Quantidade de Parcelas')),
                ('valor_parcela', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Valor da Parcela')),
                ('vencimento', models.DateField(blank=True, null=True, verbose_name='Vencimento')),
                ('observacao_texto', models.TextField(blank=True, verbose_name='Observação')),
                ('arquivo_grm', models.FileField(blank=True, null=True, upload_to='cobranca/grm/%Y/%m/', verbose_name='Arquivo GRM')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('criado_por', models.CharField(blank=True, max_length=100, verbose_name='Criado por')),
                ('auto_infracao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grms', to='fiscalizacao.autoinfracao', verbose_name='Auto de Infração')),
                ('multa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grms', to='multas.multa', verbose_name='Multa')),
                ('processo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grms', to='fiscalizacao.processo', verbose_name='Processo')),
            ],
            options={
                'verbose_name': 'Guia de Recolhimento de Multa',
                'verbose_name_plural': 'Guias de Recolhimento de Multa',
                'ordering': ['-criado_em'],
                'indexes': [models.Index(fields=['numero_guia'], name='cobranca_gu_numero__881e5a_idx'), models.Index(fields=['numero_processo'], name='cobranca_gu_numero__f2ecad_idx'), models.Index(fields=['numero_auto_infracao'], name='cobranca_gu_numero__5af213_idx')],
            },
        ),
    ]
