# Generated by Django 5.2.5 on 2025-08-31 01:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cobranca', '0002_banco_remessa'),
    ]

    operations = [
        migrations.AddField(
            model_name='boletomulta',
            name='banco',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cobranca.banco', verbose_name='Banco'),
        ),
    ]
