# Generated by Django 5.2.5 on 2025-10-09 14:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GeoDataLayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120, verbose_name='Nome da Camada')),
                ('slug', models.SlugField(max_length=80, unique=True, verbose_name='Slug')),
                ('tipo_camada', models.CharField(choices=[('REGIAO_ADMINISTRATIVA', 'Região Administrativa'), ('BAIRRO', 'Bairro'), ('MUNICIPIO', 'Município'), ('ZONA', 'Zona'), ('PONTO_INTERESSE', 'Ponto de Interesse'), ('CUSTOM', 'Personalizada')], default='CUSTOM', max_length=30, verbose_name='Tipo de Camada')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('fonte_dados', models.CharField(blank=True, max_length=200, verbose_name='Fonte dos Dados')),
                ('srid', models.CharField(default='4326', max_length=20, verbose_name='SRID')),
                ('atributos_disponiveis', models.JSONField(blank=True, default=list, verbose_name='Atributos Disponíveis')),
                ('configuracoes_estilo', models.JSONField(blank=True, default=dict, verbose_name='Configuração de Estilo')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('criado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='camadas_geograficas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Camada Geográfica',
                'verbose_name_plural': 'Camadas Geográficas',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='GeoMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificador_geografico', models.CharField(max_length=100, verbose_name='Identificador Geográfico')),
                ('indicador', models.CharField(max_length=100, verbose_name='Indicador')),
                ('valor', models.DecimalField(decimal_places=4, max_digits=20, verbose_name='Valor')),
                ('periodo_referencia', models.DateField(verbose_name='Período de Referência')),
                ('metadados', models.JSONField(blank=True, default=dict, verbose_name='Metadados')),
                ('calculado_em', models.DateTimeField(auto_now_add=True)),
                ('layer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metricas', to='geospatial_analytics.geodatalayer')),
            ],
            options={
                'verbose_name': 'Métrica Geoespacial',
                'verbose_name_plural': 'Métricas Geoespaciais',
                'ordering': ['-periodo_referencia', 'indicador'],
                'indexes': [models.Index(fields=['layer', 'indicador'], name='geospatial__layer_i_7811a0_idx'), models.Index(fields=['identificador_geografico', 'indicador'], name='geospatial__identif_cf5a34_idx')],
                'unique_together': {('layer', 'identificador_geografico', 'indicador', 'periodo_referencia')},
            },
        ),
        migrations.CreateModel(
            name='HeatmapSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indicador', models.CharField(max_length=100, verbose_name='Indicador')),
                ('gerado_em', models.DateTimeField(auto_now_add=True, verbose_name='Gerado em')),
                ('parametros', models.JSONField(blank=True, default=dict, verbose_name='Parâmetros')),
                ('dados_geojson', models.JSONField(blank=True, default=dict, verbose_name='GeoJSON')),
                ('legenda', models.JSONField(blank=True, default=dict, verbose_name='Legenda')),
                ('expiracao', models.DateTimeField(blank=True, null=True, verbose_name='Expiração')),
                ('layer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots_heatmap', to='geospatial_analytics.geodatalayer')),
            ],
            options={
                'verbose_name': 'Heatmap Snapshot',
                'verbose_name_plural': 'Heatmap Snapshots',
                'ordering': ['-gerado_em'],
                'indexes': [models.Index(fields=['layer', 'indicador'], name='geospatial__layer_i_26b2d0_idx'), models.Index(fields=['expiracao'], name='geospatial__expirac_444617_idx')],
            },
        ),
    ]
