# Generated by Django 4.2.11 on 2026-01-27 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peticionamento', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anexopeticao',
            name='tipo',
            field=models.CharField(choices=[('DOCUMENTO', 'Documento'), ('COMPROVANTE', 'Comprovante'), ('FOTO', 'Foto'), ('VIDEO', 'Vídeo'), ('AUDIO', 'Áudio'), ('PARECER', 'Parecer'), ('DECISAO', 'Decisão'), ('OUTROS', 'Outros')], default='DOCUMENTO', max_length=20, verbose_name='Tipo'),
        ),
    ]
