# Generated by Django 5.2.6 on 2025-10-02 23:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('portal_cidadao', '0003_reclamacaodenuncia_historicoreclamacao_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoAtendimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_sistema', models.CharField(default='Sistema PROCON', max_length=100, verbose_name='Nome do Sistema')),
                ('versao', models.CharField(default='1.0.0', max_length=20, verbose_name='Versão')),
                ('prefixo_protocolo', models.CharField(default='REC', max_length=10, verbose_name='Prefixo do Protocolo')),
                ('sequencia_ano', models.BooleanField(default=True, verbose_name='Sequência por Ano')),
                ('prazo_resposta_dias', models.IntegerField(default=10, verbose_name='Prazo para Resposta (dias)')),
                ('prazo_conciliacao_dias', models.IntegerField(default=30, verbose_name='Prazo para Conciliação (dias)')),
                ('prazo_decisao_dias', models.IntegerField(default=60, verbose_name='Prazo para Decisão (dias)')),
                ('notificar_consumidor', models.BooleanField(default=True, verbose_name='Notificar Consumidor')),
                ('notificar_empresa', models.BooleanField(default=True, verbose_name='Notificar Empresa')),
                ('notificar_atendente', models.BooleanField(default=True, verbose_name='Notificar Atendente')),
                ('consultar_receita_federal', models.BooleanField(default=True, verbose_name='Consultar Receita Federal')),
                ('validar_cnpj_automatico', models.BooleanField(default=True, verbose_name='Validar CNPJ Automaticamente')),
                ('classificacao_automatica', models.BooleanField(default=True, verbose_name='Classificação Automática')),
                ('assuntos_predefinidos', models.JSONField(blank=True, default=list, verbose_name='Assuntos Predefinidos')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Configuração do Atendimento',
                'verbose_name_plural': 'Configurações do Atendimento',
            },
        ),
        migrations.CreateModel(
            name='Atendimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_atendimento', models.CharField(blank=True, max_length=50, unique=True, verbose_name='Número do Atendimento')),
                ('data_atendimento', models.DateTimeField(auto_now_add=True, verbose_name='Data do Atendimento')),
                ('consumidor_nome', models.CharField(max_length=255, verbose_name='Nome do Consumidor')),
                ('consumidor_cpf', models.CharField(max_length=14, verbose_name='CPF do Consumidor')),
                ('consumidor_telefone', models.CharField(blank=True, max_length=20, verbose_name='Telefone do Consumidor')),
                ('consumidor_email', models.EmailField(blank=True, max_length=254, verbose_name='E-mail do Consumidor')),
                ('tipo_atendimento', models.CharField(choices=[('ORIENTACAO', 'Orientação'), ('RECLAMACAO', 'Reclamação'), ('DENUNCIA', 'Denúncia'), ('CONSULTA', 'Consulta'), ('OUTROS', 'Outros')], max_length=20, verbose_name='Tipo de Atendimento')),
                ('canal_atendimento', models.CharField(choices=[('BALCAO', 'Balcao Presencial'), ('TELEFONE', 'Telefone'), ('ONLINE', 'Portal/Online')], default='BALCAO', max_length=20, verbose_name='Canal do Atendimento')),
                ('status', models.CharField(choices=[('EM_ANDAMENTO', 'Em Andamento'), ('FINALIZADO', 'Finalizado'), ('ENCAMINHADO', 'Encaminhado'), ('CANCELADO', 'Cancelado')], default='EM_ANDAMENTO', max_length=15, verbose_name='Status')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('resolucao', models.TextField(blank=True, verbose_name='Resolução')),
                ('duracao_minutos', models.IntegerField(blank=True, null=True, verbose_name='Duração (minutos)')),
                ('satisfacao_consumidor', models.IntegerField(blank=True, choices=[(1, 'Muito Insatisfeito'), (2, 'Insatisfeito'), (3, 'Neutro'), (4, 'Satisfeito'), (5, 'Muito Satisfeito')], null=True, verbose_name='Satisfação do Consumidor')),
                ('atendente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='atendimentos_realizados', to=settings.AUTH_USER_MODEL)),
                ('reclamacao', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='atendimento', to='portal_cidadao.reclamacaodenuncia', verbose_name='Reclamacao/Denuncia')),
            ],
            options={
                'verbose_name': 'Atendimento',
                'verbose_name_plural': 'Atendimentos',
                'ordering': ['-data_atendimento'],
            },
        ),
    ]
