# Generated by Django 5.2.5 on 2025-10-15 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atendimento', '0002_filaatendimento'),
    ]

    operations = [
        migrations.AddField(
            model_name='atendimento',
            name='consentimento_origem',
            field=models.CharField(choices=[('TOTEM', 'Totem de Autoatendimento'), ('PORTAL', 'Portal Online'), ('GUICHE', 'Guich� Presencial'), ('IMPORTACAO', 'Importa��o de Dados')], default='GUICHE', max_length=20, verbose_name='Origem do Consentimento'),
        ),
        migrations.AddField(
            model_name='atendimento',
            name='consentimento_registrado_em',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Consentimento Registrado em'),
        ),
        migrations.AddField(
            model_name='atendimento',
            name='dados_remocao_observacoes',
            field=models.TextField(blank=True, verbose_name='Observa��es Remo��o de Dados'),
        ),
        migrations.AddField(
            model_name='atendimento',
            name='dados_remocao_solicitada_em',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Remo��o Solicitada em'),
        ),
        migrations.AddField(
            model_name='atendimento',
            name='dados_removidos_em',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Dados Removidos em'),
        ),
    ]
