# Generated by Django 5.2.5 on 2025-08-17 19:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ComissaoJulgamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('tipo_instancia', models.CharField(choices=[('primeira', 'Primeira Instância'), ('segunda', 'Segunda Instância'), ('especial', 'Instância Especial')], max_length=15, verbose_name='Instância')),
                ('presidente', models.CharField(max_length=255, verbose_name='Presidente')),
                ('membros', models.TextField(help_text='Um por linha', verbose_name='Membros')),
                ('ativa', models.BooleanField(default=True, verbose_name='Ativa')),
            ],
            options={
                'verbose_name': 'Comissão de Julgamento',
                'verbose_name_plural': 'Comissões de Julgamento',
                'ordering': ['tipo_instancia', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='TipoRecurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Nome')),
                ('codigo', models.CharField(max_length=20, unique=True, verbose_name='Código')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('prazo_dias', models.IntegerField(verbose_name='Prazo em Dias')),
                ('permite_segunda_instancia', models.BooleanField(default=True, verbose_name='Permite Segunda Instância')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('ordem', models.IntegerField(default=0, verbose_name='Ordem')),
            ],
            options={
                'verbose_name': 'Tipo de Recurso',
                'verbose_name_plural': 'Tipos de Recurso',
                'ordering': ['ordem', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='Recurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_protocolo', models.CharField(max_length=50, unique=True, verbose_name='Número do Protocolo')),
                ('instancia', models.CharField(choices=[('primeira', 'Primeira Instância'), ('segunda', 'Segunda Instância'), ('especial', 'Instância Especial')], default='primeira', max_length=15, verbose_name='Instância')),
                ('numero_processo', models.CharField(max_length=50, verbose_name='Número do Processo')),
                ('numero_auto', models.CharField(blank=True, max_length=50, verbose_name='Número do Auto')),
                ('requerente_nome', models.CharField(max_length=255, verbose_name='Nome do Requerente')),
                ('requerente_tipo', models.CharField(choices=[('pessoa_fisica', 'Pessoa Física'), ('pessoa_juridica', 'Pessoa Jurídica'), ('representante', 'Representante Legal')], default='pessoa_juridica', max_length=20, verbose_name='Tipo')),
                ('requerente_documento', models.CharField(max_length=18, verbose_name='CPF/CNPJ')),
                ('requerente_endereco', models.TextField(verbose_name='Endereço')),
                ('requerente_telefone', models.CharField(blank=True, max_length=20, verbose_name='Telefone')),
                ('requerente_email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('tem_advogado', models.BooleanField(default=False, verbose_name='Tem Advogado')),
                ('advogado_nome', models.CharField(blank=True, max_length=255, verbose_name='Nome do Advogado')),
                ('advogado_oab', models.CharField(blank=True, max_length=20, verbose_name='OAB')),
                ('procuracao_anexada', models.BooleanField(default=False, verbose_name='Procuração Anexada')),
                ('data_protocolo', models.DateTimeField(verbose_name='Data do Protocolo')),
                ('data_limite_analise', models.DateField(verbose_name='Data Limite para Análise')),
                ('data_julgamento', models.DateField(blank=True, null=True, verbose_name='Data de Julgamento')),
                ('assunto', models.CharField(max_length=255, verbose_name='Assunto')),
                ('fundamentacao', models.TextField(verbose_name='Fundamentação')),
                ('pedido', models.TextField(verbose_name='Pedido')),
                ('valor_causa', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Valor da Causa')),
                ('peticao_inicial', models.FileField(upload_to='recursos/peticoes/%Y/%m/', verbose_name='Petição Inicial')),
                ('documentos_complementares', models.TextField(blank=True, help_text='Lista de documentos anexados', verbose_name='Documentos Complementares')),
                ('status', models.CharField(choices=[('protocolado', 'Protocolado'), ('em_analise', 'Em Análise'), ('com_parecer', 'Com Parecer'), ('deferido', 'Deferido'), ('indeferido', 'Indeferido'), ('parcialmente_deferido', 'Parcialmente Deferido'), ('anulado', 'Anulado'), ('arquivado', 'Arquivado')], default='protocolado', max_length=25, verbose_name='Status')),
                ('decisao', models.TextField(blank=True, verbose_name='Decisão')),
                ('fundamentacao_decisao', models.TextField(blank=True, verbose_name='Fundamentação da Decisão')),
                ('data_decisao', models.DateField(blank=True, null=True, verbose_name='Data da Decisão')),
                ('relator', models.CharField(blank=True, max_length=255, verbose_name='Relator')),
                ('parecer_tecnico', models.TextField(blank=True, verbose_name='Parecer Técnico')),
                ('data_parecer', models.DateField(blank=True, null=True, verbose_name='Data do Parecer')),
                ('requerente_notificado', models.BooleanField(default=False, verbose_name='Requerente Notificado')),
                ('data_notificacao', models.DateField(blank=True, null=True, verbose_name='Data da Notificação')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('criado_por', models.CharField(max_length=100, verbose_name='Criado por')),
                ('recurso_hierarquico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recursos_origem', to='recursos.recurso', verbose_name='Recurso Hierárquico')),
                ('tipo_recurso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recursos.tiporecurso', verbose_name='Tipo de Recurso')),
            ],
            options={
                'verbose_name': 'Recurso',
                'verbose_name_plural': 'Recursos',
                'ordering': ['-data_protocolo'],
            },
        ),
        migrations.CreateModel(
            name='PrazoRecurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prazo_analise', models.IntegerField(verbose_name='Prazo para Análise (dias)')),
                ('data_inicio_prazo', models.DateField(verbose_name='Início do Prazo')),
                ('data_limite_prazo', models.DateField(verbose_name='Limite do Prazo')),
                ('dias_suspensos', models.IntegerField(default=0, verbose_name='Dias Suspensos')),
                ('motivo_suspensao', models.TextField(blank=True, verbose_name='Motivo da Suspensão')),
                ('alerta_5_dias', models.BooleanField(default=False, verbose_name='Alerta 5 Dias')),
                ('alerta_1_dia', models.BooleanField(default=False, verbose_name='Alerta 1 Dia')),
                ('alerta_vencido', models.BooleanField(default=False, verbose_name='Alerta Vencido')),
                ('recurso', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='controle_prazo', to='recursos.recurso')),
            ],
            options={
                'verbose_name': 'Controle de Prazo',
                'verbose_name_plural': 'Controle de Prazos',
            },
        ),
        migrations.CreateModel(
            name='MovimentacaoRecurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_movimentacao', models.CharField(choices=[('protocolo', 'Protocolo'), ('distribuicao', 'Distribuição'), ('parecer', 'Parecer Técnico'), ('julgamento', 'Julgamento'), ('decisao', 'Decisão'), ('notificacao', 'Notificação'), ('recurso_hierarquico', 'Recurso Hierárquico'), ('arquivamento', 'Arquivamento'), ('observacao', 'Observação')], max_length=20, verbose_name='Tipo')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('data_movimentacao', models.DateTimeField(auto_now_add=True, verbose_name='Data/Hora')),
                ('responsavel', models.CharField(max_length=255, verbose_name='Responsável')),
                ('documento_anexo', models.FileField(blank=True, null=True, upload_to='recursos/movimentacoes/%Y/%m/', verbose_name='Documento')),
                ('recurso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimentacoes', to='recursos.recurso')),
            ],
            options={
                'verbose_name': 'Movimentação de Recurso',
                'verbose_name_plural': 'Movimentações de Recurso',
                'ordering': ['-data_movimentacao'],
            },
        ),
        migrations.CreateModel(
            name='RecursoJulgado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordem_julgamento', models.IntegerField(verbose_name='Ordem de Julgamento')),
                ('decisao', models.CharField(choices=[('indeferido', 'Indeferido'), ('parcialmente_deferido', 'Parcialmente Deferido'), ('anulado', 'Anulado'), ('arquivado', 'Arquivado')], max_length=25, verbose_name='Decisão')),
                ('relator', models.CharField(max_length=255, verbose_name='Relator')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('recurso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recursos.recurso')),
            ],
            options={
                'verbose_name': 'Recurso Julgado',
                'verbose_name_plural': 'Recursos Julgados',
                'ordering': ['sessao', 'ordem_julgamento'],
            },
        ),
        migrations.CreateModel(
            name='SessaoJulgamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_sessao', models.CharField(max_length=20, verbose_name='Número da Sessão')),
                ('data_sessao', models.DateField(verbose_name='Data da Sessão')),
                ('hora_inicio', models.TimeField(verbose_name='Hora de Início')),
                ('hora_fim', models.TimeField(blank=True, null=True, verbose_name='Hora de Fim')),
                ('local_sessao', models.CharField(max_length=255, verbose_name='Local')),
                ('ata_sessao', models.TextField(blank=True, verbose_name='Ata da Sessão')),
                ('ata_arquivo', models.FileField(blank=True, null=True, upload_to='recursos/atas/%Y/%m/', verbose_name='Arquivo da Ata')),
                ('realizada', models.BooleanField(default=False, verbose_name='Realizada')),
                ('publicada', models.BooleanField(default=False, verbose_name='Publicada')),
                ('comissao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recursos.comissaojulgamento', verbose_name='Comissão')),
                ('recursos', models.ManyToManyField(through='recursos.RecursoJulgado', to='recursos.recurso', verbose_name='Recursos')),
            ],
            options={
                'verbose_name': 'Sessão de Julgamento',
                'verbose_name_plural': 'Sessões de Julgamento',
                'ordering': ['-data_sessao'],
            },
        ),
        migrations.AddField(
            model_name='recursojulgado',
            name='sessao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recursos.sessaojulgamento'),
        ),
        migrations.CreateModel(
            name='ModeloDecisao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do Modelo')),
                ('tipo_decisao', models.CharField(choices=[('deferido', 'Deferido'), ('indeferido', 'Indeferido'), ('parcialmente_deferido', 'Parcialmente Deferido')], max_length=25, verbose_name='Tipo de Decisão')),
                ('template_decisao', models.TextField(verbose_name='Template da Decisão')),
                ('template_fundamentacao', models.TextField(verbose_name='Template da Fundamentação')),
                ('variaveis_disponiveis', models.TextField(help_text='Lista das variáveis que podem ser usadas', verbose_name='Variáveis Disponíveis')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('padrao', models.BooleanField(default=False, help_text='Modelo padrão para este tipo', verbose_name='Padrão')),
                ('tipo_recurso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recursos.tiporecurso', verbose_name='Tipo de Recurso')),
            ],
            options={
                'verbose_name': 'Modelo de Decisão',
                'verbose_name_plural': 'Modelos de Decisão',
                'ordering': ['tipo_recurso', 'nome'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='recursojulgado',
            unique_together={('sessao', 'recurso')},
        ),
        migrations.AddIndex(
            model_name='recurso',
            index=models.Index(fields=['numero_protocolo'], name='recursos_re_numero__d16d92_idx'),
        ),
        migrations.AddIndex(
            model_name='recurso',
            index=models.Index(fields=['numero_processo'], name='recursos_re_numero__ee1c96_idx'),
        ),
        migrations.AddIndex(
            model_name='recurso',
            index=models.Index(fields=['status'], name='recursos_re_status_891917_idx'),
        ),
        migrations.AddIndex(
            model_name='recurso',
            index=models.Index(fields=['data_limite_analise'], name='recursos_re_data_li_259139_idx'),
        ),
    ]
