/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/agendamentos`; params?: Router.UnknownInputParams; } | { pathname: `/home`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/login`; params?: Router.UnknownInputParams; } | { pathname: `/offline`; params?: Router.UnknownInputParams; } | { pathname: `/../src/constants/bancoChecklist`; params?: Router.UnknownInputParams; } | { pathname: `/../src/constants/autoFormConfig`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/autos/infracao`; params?: Router.UnknownInputParams; } | { pathname: `/autos/new`; params?: Router.UnknownInputParams; } | { pathname: `/notificacoes/new`; params?: Router.UnknownInputParams; } | { pathname: `/sync/pending`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/agendamentos`; params?: Router.UnknownOutputParams; } | { pathname: `/home`; params?: Router.UnknownOutputParams; } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/login`; params?: Router.UnknownOutputParams; } | { pathname: `/offline`; params?: Router.UnknownOutputParams; } | { pathname: `/../src/constants/bancoChecklist`; params?: Router.UnknownOutputParams; } | { pathname: `/../src/constants/autoFormConfig`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `/autos/infracao`; params?: Router.UnknownOutputParams; } | { pathname: `/autos/new`; params?: Router.UnknownOutputParams; } | { pathname: `/notificacoes/new`; params?: Router.UnknownOutputParams; } | { pathname: `/sync/pending`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/agendamentos${`?${string}` | `#${string}` | ''}` | `/home${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `/login${`?${string}` | `#${string}` | ''}` | `/offline${`?${string}` | `#${string}` | ''}` | `/../src/constants/bancoChecklist${`?${string}` | `#${string}` | ''}` | `/../src/constants/autoFormConfig${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `/autos/infracao${`?${string}` | `#${string}` | ''}` | `/autos/new${`?${string}` | `#${string}` | ''}` | `/notificacoes/new${`?${string}` | `#${string}` | ''}` | `/sync/pending${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/agendamentos`; params?: Router.UnknownInputParams; } | { pathname: `/home`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/login`; params?: Router.UnknownInputParams; } | { pathname: `/offline`; params?: Router.UnknownInputParams; } | { pathname: `/../src/constants/bancoChecklist`; params?: Router.UnknownInputParams; } | { pathname: `/../src/constants/autoFormConfig`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/autos/infracao`; params?: Router.UnknownInputParams; } | { pathname: `/autos/new`; params?: Router.UnknownInputParams; } | { pathname: `/notificacoes/new`; params?: Router.UnknownInputParams; } | { pathname: `/sync/pending`; params?: Router.UnknownInputParams; };
    }
  }
}
