# Generated by Django 5.2.5 on 2025-08-18 00:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fiscalizacao', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoRecursos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prazo_defesa_dias', models.IntegerField(default=15, verbose_name='Prazo para Defesa (dias)')),
                ('prazo_recurso_dias', models.IntegerField(default=10, verbose_name='Prazo para Recurso (dias)')),
                ('prazo_analise_dias', models.IntegerField(default=30, verbose_name='Prazo para Análise (dias)')),
                ('prazo_julgamento_dias', models.IntegerField(default=60, verbose_name='Prazo para Julgamento (dias)')),
                ('notificar_prazos', models.BooleanField(default=True, verbose_name='Notificar Prazos')),
                ('dias_antecedencia_notificacao', models.IntegerField(default=3, verbose_name='Dias de Antecedência')),
                ('tamanho_maximo_arquivo_mb', models.IntegerField(default=10, verbose_name='Tamanho Máximo Arquivo (MB)')),
                ('tipos_arquivo_permitidos', models.TextField(default='pdf,doc,docx,jpg,jpeg,png', help_text='Separados por vírgula', verbose_name='Tipos de Arquivo Permitidos')),
            ],
            options={
                'verbose_name': 'Configuração de Recursos',
                'verbose_name_plural': 'Configurações de Recursos',
            },
        ),
        migrations.CreateModel(
            name='TipoDefesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('prazo_dias', models.IntegerField(default=15, verbose_name='Prazo em Dias')),
                ('requer_documentos', models.BooleanField(default=True, verbose_name='Requer Documentos')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Tipo de Defesa',
                'verbose_name_plural': 'Tipos de Defesas',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='DefesaAdministrativa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_defesa', models.CharField(blank=True, max_length=25, unique=True, verbose_name='Número da Defesa')),
                ('data_protocolo', models.DateTimeField(auto_now_add=True, verbose_name='Data de Protocolo')),
                ('data_apresentacao', models.DateField(auto_now_add=True, verbose_name='Data de Apresentação')),
                ('forma_apresentacao', models.CharField(choices=[('presencial', 'Presencial'), ('digital', 'Digital'), ('correios', 'Correios'), ('protocolo', 'Protocolo')], max_length=20, verbose_name='Forma de Apresentação')),
                ('requerente_nome', models.CharField(max_length=255, verbose_name='Nome do Requerente')),
                ('requerente_cpf_cnpj', models.CharField(max_length=18, verbose_name='CPF/CNPJ')),
                ('requerente_oab', models.CharField(blank=True, help_text='Se apresentado por advogado', max_length=20, verbose_name='OAB')),
                ('argumentos', models.TextField(verbose_name='Argumentos da Defesa')),
                ('pedidos', models.TextField(help_text='O que está sendo solicitado', verbose_name='Pedidos')),
                ('status', models.CharField(choices=[('protocolada', 'Protocolada'), ('em_analise', 'Em Análise'), ('deferida', 'Deferida'), ('indeferida', 'Indeferida'), ('parcialmente_deferida', 'Parcialmente Deferida')], default='protocolada', max_length=25, verbose_name='Status')),
                ('data_analise', models.DateField(blank=True, null=True, verbose_name='Data da Análise')),
                ('resultado_analise', models.TextField(blank=True, verbose_name='Resultado da Análise')),
                ('prazo_resposta', models.DateField(blank=True, null=True, verbose_name='Prazo para Resposta')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('analista_responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='defesas_analisadas', to=settings.AUTH_USER_MODEL, verbose_name='Analista Responsável')),
                ('processo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='defesas', to='fiscalizacao.processo', verbose_name='Processo Administrativo')),
                ('tipo_defesa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='recursos_defesas.tipodefesa', verbose_name='Tipo de Defesa')),
            ],
            options={
                'verbose_name': 'Defesa Administrativa',
                'verbose_name_plural': 'Defesas Administrativas',
                'ordering': ['-data_protocolo'],
            },
        ),
        migrations.CreateModel(
            name='DocumentoDefesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('procuracao', 'Procuração'), ('contrato_social', 'Contrato Social'), ('certidao', 'Certidão'), ('nota_fiscal', 'Nota Fiscal'), ('foto', 'Fotografia'), ('laudo', 'Laudo Técnico'), ('outros', 'Outros')], max_length=20, verbose_name='Tipo')),
                ('nome_arquivo', models.CharField(max_length=255, verbose_name='Nome do Arquivo')),
                ('arquivo', models.FileField(upload_to='defesas/documentos/%Y/%m/', verbose_name='Arquivo')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('upload_em', models.DateTimeField(auto_now_add=True, verbose_name='Upload em')),
                ('tamanho_bytes', models.BigIntegerField(blank=True, null=True, verbose_name='Tamanho (bytes)')),
                ('defesa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='recursos_defesas.defesaadministrativa')),
            ],
            options={
                'verbose_name': 'Documento da Defesa',
                'verbose_name_plural': 'Documentos das Defesas',
                'ordering': ['-upload_em'],
            },
        ),
        migrations.CreateModel(
            name='RecursoAdministrativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_recurso', models.CharField(blank=True, max_length=25, unique=True, verbose_name='Número do Recurso')),
                ('instancia', models.CharField(choices=[('primeira', 'Primeira Instância'), ('segunda', 'Segunda Instância'), ('terceira', 'Terceira Instância')], max_length=15, verbose_name='Instância')),
                ('data_protocolo', models.DateTimeField(auto_now_add=True, verbose_name='Data de Protocolo')),
                ('data_apresentacao', models.DateField(auto_now_add=True, verbose_name='Data de Apresentação')),
                ('recorrente_nome', models.CharField(max_length=255, verbose_name='Nome do Recorrente')),
                ('recorrente_oab', models.CharField(blank=True, max_length=20, verbose_name='OAB')),
                ('fundamentos', models.TextField(verbose_name='Fundamentos do Recurso')),
                ('pedidos', models.TextField(verbose_name='Pedidos')),
                ('status', models.CharField(choices=[('protocolado', 'Protocolado'), ('em_analise', 'Em Análise'), ('deferido', 'Deferido'), ('indeferido', 'Indeferido'), ('parcialmente_deferido', 'Parcialmente Deferido')], default='protocolado', max_length=25, verbose_name='Status')),
                ('data_julgamento', models.DateField(blank=True, null=True, verbose_name='Data do Julgamento')),
                ('resultado_julgamento', models.TextField(blank=True, verbose_name='Resultado do Julgamento')),
                ('prazo_julgamento', models.DateField(blank=True, null=True, verbose_name='Prazo para Julgamento')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('defesa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recursos', to='recursos_defesas.defesaadministrativa', verbose_name='Defesa Administrativa')),
                ('relator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recursos_defesas_relatados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Recurso Administrativo',
                'verbose_name_plural': 'Recursos Administrativos',
                'ordering': ['-data_protocolo'],
            },
        ),
        migrations.CreateModel(
            name='AnaliseJuridica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('defesa', 'Análise de Defesa'), ('recurso_1', 'Análise de Recurso 1ª Instância'), ('recurso_2', 'Análise de Recurso 2ª Instância')], max_length=15, verbose_name='Tipo de Análise')),
                ('numero_analise', models.CharField(blank=True, max_length=25, unique=True, verbose_name='Número da Análise')),
                ('relatorio_fatos', models.TextField(verbose_name='Relatório dos Fatos')),
                ('fundamentacao_juridica', models.TextField(verbose_name='Fundamentação Jurídica')),
                ('conclusao', models.TextField(verbose_name='Conclusão')),
                ('recomendacao', models.CharField(choices=[('deferir', 'Deferir'), ('indeferir', 'Indeferir'), ('deferir_parcial', 'Deferir Parcialmente')], max_length=15, verbose_name='Recomendação')),
                ('justificativa_recomendacao', models.TextField(verbose_name='Justificativa da Recomendação')),
                ('data_analise', models.DateField(auto_now_add=True, verbose_name='Data da Análise')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('analista', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='analises_juridicas', to=settings.AUTH_USER_MODEL)),
                ('defesa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='analises', to='recursos_defesas.defesaadministrativa')),
                ('recurso', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='analises', to='recursos_defesas.recursoadministrativo')),
            ],
            options={
                'verbose_name': 'Análise Jurídica',
                'verbose_name_plural': 'Análises Jurídicas',
                'ordering': ['-data_analise'],
            },
        ),
        migrations.AddIndex(
            model_name='recursoadministrativo',
            index=models.Index(fields=['numero_recurso'], name='recursos_de_numero__5e7cad_idx'),
        ),
        migrations.AddIndex(
            model_name='recursoadministrativo',
            index=models.Index(fields=['defesa', 'status'], name='recursos_de_defesa__7fd87f_idx'),
        ),
        migrations.AddIndex(
            model_name='recursoadministrativo',
            index=models.Index(fields=['instancia'], name='recursos_de_instanc_5f439a_idx'),
        ),
        migrations.AddIndex(
            model_name='defesaadministrativa',
            index=models.Index(fields=['numero_defesa'], name='recursos_de_numero__a1aabf_idx'),
        ),
        migrations.AddIndex(
            model_name='defesaadministrativa',
            index=models.Index(fields=['processo', 'status'], name='recursos_de_process_e39024_idx'),
        ),
        migrations.AddIndex(
            model_name='defesaadministrativa',
            index=models.Index(fields=['data_apresentacao'], name='recursos_de_data_ap_9f6b2c_idx'),
        ),
        migrations.AddIndex(
            model_name='defesaadministrativa',
            index=models.Index(fields=['status'], name='recursos_de_status_13c79c_idx'),
        ),
    ]
