# Generated by Django 5.2.5 on 2025-08-17 19:41

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PorteEmpresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True, verbose_name='Nome do Porte')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('faturamento_min', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Faturamento Mínimo')),
                ('faturamento_max', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Faturamento Máximo')),
            ],
            options={
                'verbose_name': 'Porte de Empresa',
                'verbose_name_plural': 'Portes de Empresa',
                'ordering': ['faturamento_min'],
            },
        ),
        migrations.CreateModel(
            name='SegmentoEconomico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Nome do Segmento')),
                ('codigo', models.CharField(blank=True, max_length=20, verbose_name='Código')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Segmento Econômico',
                'verbose_name_plural': 'Segmentos Econômicos',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razao_social', models.CharField(max_length=255, verbose_name='Razão Social')),
                ('nome_fantasia', models.CharField(blank=True, max_length=255, verbose_name='Nome Fantasia')),
                ('cnpj', models.CharField(max_length=18, unique=True, validators=[django.core.validators.RegexValidator('^\\d{2}\\.\\d{3}\\.\\d{3}/\\d{4}-\\d{2}$', 'CNPJ deve estar no formato XX.XXX.XXX/XXXX-XX')], verbose_name='CNPJ')),
                ('inscricao_estadual', models.CharField(blank=True, max_length=20, verbose_name='Inscrição Estadual')),
                ('inscricao_municipal', models.CharField(blank=True, max_length=20, verbose_name='Inscrição Municipal')),
                ('tipo', models.CharField(choices=[('matriz', 'Matriz'), ('filial', 'Filial')], default='matriz', max_length=10, verbose_name='Tipo')),
                ('situacao', models.CharField(choices=[('ativa', 'Ativa'), ('inativa', 'Inativa'), ('suspensa', 'Suspensa'), ('baixada', 'Baixada')], default='ativa', max_length=10, verbose_name='Situação')),
                ('classificacao_risco', models.CharField(choices=[('baixo', 'Baixo Risco'), ('medio', 'Médio Risco'), ('alto', 'Alto Risco'), ('critico', 'Crítico')], default='baixo', max_length=10, verbose_name='Classificação de Risco')),
                ('endereco', models.CharField(max_length=255, verbose_name='Endereço')),
                ('numero', models.CharField(max_length=20, verbose_name='Número')),
                ('complemento', models.CharField(blank=True, max_length=100, verbose_name='Complemento')),
                ('bairro', models.CharField(max_length=100, verbose_name='Bairro')),
                ('cep', models.CharField(max_length=10, verbose_name='CEP')),
                ('cidade', models.CharField(max_length=100, verbose_name='Cidade')),
                ('estado', models.CharField(default='AM', max_length=2, verbose_name='Estado')),
                ('telefone', models.CharField(blank=True, max_length=20, verbose_name='Telefone')),
                ('celular', models.CharField(blank=True, max_length=20, verbose_name='Celular')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-mail')),
                ('site', models.URLField(blank=True, verbose_name='Site')),
                ('data_abertura', models.DateField(blank=True, null=True, verbose_name='Data de Abertura')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True, verbose_name='Data de Cadastro')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('matriz', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='filiais', to='empresas.empresa', verbose_name='Empresa Matriz')),
                ('porte', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='empresas.porteempresa', verbose_name='Porte')),
                ('segmento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='empresas.segmentoeconomico', verbose_name='Segmento')),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
                'ordering': ['razao_social'],
            },
        ),
        migrations.CreateModel(
            name='EnderecoFilial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome/Identificação')),
                ('endereco', models.CharField(max_length=255, verbose_name='Endereço')),
                ('numero', models.CharField(max_length=20, verbose_name='Número')),
                ('complemento', models.CharField(blank=True, max_length=100, verbose_name='Complemento')),
                ('bairro', models.CharField(max_length=100, verbose_name='Bairro')),
                ('cep', models.CharField(max_length=10, verbose_name='CEP')),
                ('cidade', models.CharField(max_length=100, verbose_name='Cidade')),
                ('estado', models.CharField(default='AM', max_length=2, verbose_name='Estado')),
                ('telefone', models.CharField(blank=True, max_length=20, verbose_name='Telefone')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enderecos_adicionais', to='empresas.empresa', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Endereço Adicional',
                'verbose_name_plural': 'Endereços Adicionais',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='HistoricoEmpresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_evento', models.CharField(choices=[('cadastro', 'Cadastro'), ('atualizacao', 'Atualização de Dados'), ('infracao', 'Infração'), ('multa', 'Aplicação de Multa'), ('pagamento', 'Pagamento de Multa'), ('recurso', 'Interposição de Recurso'), ('suspensao', 'Suspensão'), ('reativacao', 'Reativação'), ('observacao', 'Observação Geral')], max_length=20, verbose_name='Tipo de Evento')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('data_evento', models.DateTimeField(auto_now_add=True, verbose_name='Data do Evento')),
                ('usuario', models.CharField(blank=True, max_length=100, verbose_name='Usuário')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico', to='empresas.empresa', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Histórico da Empresa',
                'verbose_name_plural': 'Histórico das Empresas',
                'ordering': ['-data_evento'],
            },
        ),
        migrations.CreateModel(
            name='ResponsavelLegal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome Completo')),
                ('cpf', models.CharField(max_length=14, validators=[django.core.validators.RegexValidator('^\\d{3}\\.\\d{3}\\.\\d{3}-\\d{2}$', 'CPF deve estar no formato XXX.XXX.XXX-XX')], verbose_name='CPF')),
                ('rg', models.CharField(blank=True, max_length=20, verbose_name='RG')),
                ('cargo', models.CharField(max_length=100, verbose_name='Cargo')),
                ('telefone', models.CharField(blank=True, max_length=20, verbose_name='Telefone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-mail')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('data_inicio', models.DateField(default=django.utils.timezone.now, verbose_name='Data de Início')),
                ('data_fim', models.DateField(blank=True, null=True, verbose_name='Data de Fim')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responsaveis', to='empresas.empresa', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Responsável Legal',
                'verbose_name_plural': 'Responsáveis Legais',
                'ordering': ['-ativo', 'nome'],
            },
        ),
        migrations.AddIndex(
            model_name='empresa',
            index=models.Index(fields=['cnpj'], name='empresas_em_cnpj_fe5b68_idx'),
        ),
        migrations.AddIndex(
            model_name='empresa',
            index=models.Index(fields=['razao_social'], name='empresas_em_razao_s_25558e_idx'),
        ),
        migrations.AddIndex(
            model_name='empresa',
            index=models.Index(fields=['classificacao_risco'], name='empresas_em_classif_b9ea80_idx'),
        ),
        migrations.AddIndex(
            model_name='empresa',
            index=models.Index(fields=['situacao'], name='empresas_em_situaca_1b99dd_idx'),
        ),
    ]
