# Generated by Django 5.2.5 on 2025-10-21 14:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='enderecofilial',
            options={'ordering': ['nome'], 'verbose_name': 'EndereÃ§o Adicional', 'verbose_name_plural': 'EndereÃ§os Adicionais'},
        ),
        migrations.AlterModelOptions(
            name='historicoempresa',
            options={'ordering': ['-data_evento'], 'verbose_name': 'HistÃ³rico da Empresa', 'verbose_name_plural': 'HistÃ³rico das Empresas'},
        ),
        migrations.AlterModelOptions(
            name='responsavellegal',
            options={'ordering': ['-ativo', 'nome'], 'verbose_name': 'ResponsÃ¡vel Legal', 'verbose_name_plural': 'ResponsÃ¡veis Legais'},
        ),
        migrations.AlterModelOptions(
            name='segmentoeconomico',
            options={'ordering': ['nome'], 'verbose_name': 'Segmento EconÃ´mico', 'verbose_name_plural': 'Segmentos EconÃ´micos'},
        ),
        migrations.AddField(
            model_name='empresa',
            name='uuid_local',
            field=models.UUIDField(blank=True, help_text='Identificador de rascunhos da aplicacao mobile', null=True, unique=True, verbose_name='UUID mobile'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='classificacao_risco',
            field=models.CharField(choices=[('baixo', 'Baixo Risco'), ('medio', 'MÃ©dio Risco'), ('alto', 'Alto Risco'), ('critico', 'CrÃ\xadtico')], default='baixo', max_length=10, verbose_name='ClassificaÃ§Ã£o de Risco'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='data_atualizacao',
            field=models.DateTimeField(auto_now=True, verbose_name='Ã\x9altima AtualizaÃ§Ã£o'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='endereco',
            field=models.CharField(max_length=255, verbose_name='EndereÃ§o'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='inscricao_estadual',
            field=models.CharField(blank=True, max_length=20, verbose_name='InscriÃ§Ã£o Estadual'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='inscricao_municipal',
            field=models.CharField(blank=True, max_length=20, verbose_name='InscriÃ§Ã£o Municipal'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='numero',
            field=models.CharField(max_length=20, verbose_name='NÃºmero'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='observacoes',
            field=models.TextField(blank=True, verbose_name='ObservaÃ§Ãµes'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='razao_social',
            field=models.CharField(max_length=255, verbose_name='RazÃ£o Social'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='situacao',
            field=models.CharField(choices=[('ativa', 'Ativa'), ('inativa', 'Inativa'), ('suspensa', 'Suspensa'), ('baixada', 'Baixada')], default='ativa', max_length=10, verbose_name='SituaÃ§Ã£o'),
        ),
        migrations.AlterField(
            model_name='enderecofilial',
            name='endereco',
            field=models.CharField(max_length=255, verbose_name='EndereÃ§o'),
        ),
        migrations.AlterField(
            model_name='enderecofilial',
            name='nome',
            field=models.CharField(max_length=100, verbose_name='Nome/IdentificaÃ§Ã£o'),
        ),
        migrations.AlterField(
            model_name='enderecofilial',
            name='numero',
            field=models.CharField(max_length=20, verbose_name='NÃºmero'),
        ),
        migrations.AlterField(
            model_name='historicoempresa',
            name='descricao',
            field=models.TextField(verbose_name='DescriÃ§Ã£o'),
        ),
        migrations.AlterField(
            model_name='historicoempresa',
            name='tipo_evento',
            field=models.CharField(choices=[('cadastro', 'Cadastro'), ('atualizacao', 'AtualizaÃ§Ã£o de Dados'), ('infracao', 'InfraÃ§Ã£o'), ('multa', 'AplicaÃ§Ã£o de Multa'), ('pagamento', 'Pagamento de Multa'), ('recurso', 'InterposiÃ§Ã£o de Recurso'), ('suspensao', 'SuspensÃ£o'), ('reativacao', 'ReativaÃ§Ã£o'), ('observacao', 'ObservaÃ§Ã£o Geral')], max_length=20, verbose_name='Tipo de Evento'),
        ),
        migrations.AlterField(
            model_name='historicoempresa',
            name='usuario',
            field=models.CharField(blank=True, max_length=100, verbose_name='UsuÃ¡rio'),
        ),
        migrations.AlterField(
            model_name='porteempresa',
            name='descricao',
            field=models.TextField(blank=True, verbose_name='DescriÃ§Ã£o'),
        ),
        migrations.AlterField(
            model_name='porteempresa',
            name='faturamento_max',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Faturamento MÃ¡ximo'),
        ),
        migrations.AlterField(
            model_name='porteempresa',
            name='faturamento_min',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Faturamento MÃ\xadnimo'),
        ),
        migrations.AlterField(
            model_name='responsavellegal',
            name='data_inicio',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Data de InÃ\xadcio'),
        ),
        migrations.AlterField(
            model_name='segmentoeconomico',
            name='codigo',
            field=models.CharField(blank=True, max_length=20, verbose_name='CÃ³digo'),
        ),
        migrations.AlterField(
            model_name='segmentoeconomico',
            name='descricao',
            field=models.TextField(blank=True, verbose_name='DescriÃ§Ã£o'),
        ),
        migrations.AddIndex(
            model_name='empresa',
            index=models.Index(fields=['uuid_local'], name='empresas_em_uuid_lo_873ff3_idx'),
        ),
    ]
